// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;

namespace CommunityStarter.Domain.GeneratedFeatures;

public sealed record AdministerCommunitySettingsRequest(
    Guid SubjectId,
    string Action,
    long ExpectedVersion,
    Guid? CommunityId,
    IReadOnlyDictionary<string, string> Values)
{
    public FeatureInput ToInput() => new(SubjectId, Action, ExpectedVersion, CommunityId, Values);
}

public sealed record AdministerCommunitySettingsRecord(
    Guid Id,
    Guid? CommunityId,
    string State,
    long Version,
    bool IsAuthorized,
    bool IsAvailable)
{
    public FeatureState ToState() => new(Id, CommunityId, State, Version, IsAuthorized, IsAvailable);
}

public sealed record AdministerCommunitySettingsDecision(
    string RequirementId,
    FeatureDecisionKind Kind,
    string Code,
    string ResultingState,
    long ResultingVersion)
{
    public bool IsAccepted => Kind == FeatureDecisionKind.Accepted;

    public static AdministerCommunitySettingsDecision From(FeatureDecision decision) =>
        new(decision.RequirementId, decision.Kind, decision.Code, decision.ResultingState, decision.ResultingVersion);
}

public sealed class AdministerCommunitySettingsPolicy
{
    public AdministerCommunitySettingsDecision ChangeVersionedCommunitySettings(
        AdministerCommunitySettingsRecord record,
        AdministerCommunitySettingsRequest request) =>
        AdministerCommunitySettingsDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-ADMN-001", record.ToState(), request.ToInput()));

    public AdministerCommunitySettingsDecision DelegateRolesWithoutPrivilegeEscalation(
        AdministerCommunitySettingsRecord record,
        AdministerCommunitySettingsRequest request) =>
        AdministerCommunitySettingsDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-ADMN-002", record.ToState(), request.ToInput()));

    public AdministerCommunitySettingsDecision PreviewAndExecuteHighImpactOperations(
        AdministerCommunitySettingsRecord record,
        AdministerCommunitySettingsRequest request) =>
        AdministerCommunitySettingsDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-ADMN-003", record.ToState(), request.ToInput()));
}

public static class AdministerCommunitySettingsDescriptor
{
    public const string Subsystem = "administration-insights";
    public const string Slug = "administer-community-settings";
    public const string Title = "Bounded Community administration";

    public static IReadOnlyList<FeatureOperationDescriptor> Operations { get; } =
    [
        new("L2-ADMN-001", "ChangeVersionedCommunitySettings"),
        new("L2-ADMN-002", "DelegateRolesWithoutPrivilegeEscalation"),
        new("L2-ADMN-003", "PreviewAndExecuteHighImpactOperations")
    ];
}
