// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;

namespace CommunityStarter.Domain.GeneratedFeatures;

public sealed record AuthorizeConversationAccessRequest(
    Guid SubjectId,
    string Action,
    long ExpectedVersion,
    Guid? CommunityId,
    IReadOnlyDictionary<string, string> Values)
{
    public FeatureInput ToInput() => new(SubjectId, Action, ExpectedVersion, CommunityId, Values);
}

public sealed record AuthorizeConversationAccessRecord(
    Guid Id,
    Guid? CommunityId,
    string State,
    long Version,
    bool IsAuthorized,
    bool IsAvailable)
{
    public FeatureState ToState() => new(Id, CommunityId, State, Version, IsAuthorized, IsAvailable);
}

public sealed record AuthorizeConversationAccessDecision(
    string RequirementId,
    FeatureDecisionKind Kind,
    string Code,
    string ResultingState,
    long ResultingVersion)
{
    public bool IsAccepted => Kind == FeatureDecisionKind.Accepted;

    public static AuthorizeConversationAccessDecision From(FeatureDecision decision) =>
        new(decision.RequirementId, decision.Kind, decision.Code, decision.ResultingState, decision.ResultingVersion);
}

public sealed class AuthorizeConversationAccessPolicy
{
    public AuthorizeConversationAccessDecision StartAnAuthorizedConversation(
        AuthorizeConversationAccessRecord record,
        AuthorizeConversationAccessRequest request) =>
        AuthorizeConversationAccessDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-MESS-001", record.ToState(), request.ToInput()));

    public AuthorizeConversationAccessDecision EnforceMessageRequestAndBlockPolicy(
        AuthorizeConversationAccessRecord record,
        AuthorizeConversationAccessRequest request) =>
        AuthorizeConversationAccessDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-MESS-002", record.ToState(), request.ToInput()));

    public AuthorizeConversationAccessDecision EndAndReEnterDirectConversationsDeterministically(
        AuthorizeConversationAccessRecord record,
        AuthorizeConversationAccessRequest request) =>
        AuthorizeConversationAccessDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-MESS-016", record.ToState(), request.ToInput()));
}

public static class AuthorizeConversationAccessDescriptor
{
    public const string Subsystem = "messaging-realtime";
    public const string Slug = "authorize-conversation-access";
    public const string Title = "Consent-based Conversation access";

    public static IReadOnlyList<FeatureOperationDescriptor> Operations { get; } =
    [
        new("L2-MESS-001", "StartAnAuthorizedConversation"),
        new("L2-MESS-002", "EnforceMessageRequestAndBlockPolicy"),
        new("L2-MESS-016", "EndAndReEnterDirectConversationsDeterministically")
    ];
}
