// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;

namespace CommunityStarter.Domain.GeneratedFeatures;

public sealed record BuildLayeredRiskEvidenceRequest(
    Guid SubjectId,
    string Action,
    long ExpectedVersion,
    Guid? CommunityId,
    IReadOnlyDictionary<string, string> Values)
{
    public FeatureInput ToInput() => new(SubjectId, Action, ExpectedVersion, CommunityId, Values);
}

public sealed record BuildLayeredRiskEvidenceRecord(
    Guid Id,
    Guid? CommunityId,
    string State,
    long Version,
    bool IsAuthorized,
    bool IsAvailable)
{
    public FeatureState ToState() => new(Id, CommunityId, State, Version, IsAuthorized, IsAvailable);
}

public sealed record BuildLayeredRiskEvidenceDecision(
    string RequirementId,
    FeatureDecisionKind Kind,
    string Code,
    string ResultingState,
    long ResultingVersion)
{
    public bool IsAccepted => Kind == FeatureDecisionKind.Accepted;

    public static BuildLayeredRiskEvidenceDecision From(FeatureDecision decision) =>
        new(decision.RequirementId, decision.Kind, decision.Code, decision.ResultingState, decision.ResultingVersion);
}

public sealed class BuildLayeredRiskEvidencePolicy
{
    public BuildLayeredRiskEvidenceDecision TestSelectionFollowsRiskAndEvidenceScope(
        BuildLayeredRiskEvidenceRecord record,
        BuildLayeredRiskEvidenceRequest request) =>
        BuildLayeredRiskEvidenceDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-QUAL-001", record.ToState(), request.ToInput()));

    public BuildLayeredRiskEvidenceDecision ProductRulesAndComponentBehaviorHaveFocusedTests(
        BuildLayeredRiskEvidenceRecord record,
        BuildLayeredRiskEvidenceRequest request) =>
        BuildLayeredRiskEvidenceDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-QUAL-002", record.ToState(), request.ToInput()));

    public BuildLayeredRiskEvidenceDecision IntegrationTestsUseRealProviderBehaviorWhereItMatters(
        BuildLayeredRiskEvidenceRecord record,
        BuildLayeredRiskEvidenceRequest request) =>
        BuildLayeredRiskEvidenceDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-QUAL-003", record.ToState(), request.ToInput()));

    public BuildLayeredRiskEvidenceDecision ContractsJourneysAndDeploymentsReceiveCrossStackEvidence(
        BuildLayeredRiskEvidenceRecord record,
        BuildLayeredRiskEvidenceRequest request) =>
        BuildLayeredRiskEvidenceDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-QUAL-004", record.ToState(), request.ToInput()));
}

public static class BuildLayeredRiskEvidenceDescriptor
{
    public const string Subsystem = "delivery-quality";
    public const string Slug = "build-layered-risk-evidence";
    public const string Title = "Build layered evidence around product risk";

    public static IReadOnlyList<FeatureOperationDescriptor> Operations { get; } =
    [
        new("L2-QUAL-001", "TestSelectionFollowsRiskAndEvidenceScope"),
        new("L2-QUAL-002", "ProductRulesAndComponentBehaviorHaveFocusedTests"),
        new("L2-QUAL-003", "IntegrationTestsUseRealProviderBehaviorWhereItMatters"),
        new("L2-QUAL-004", "ContractsJourneysAndDeploymentsReceiveCrossStackEvidence")
    ];
}
