// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;

namespace CommunityStarter.Domain.GeneratedFeatures;

public sealed record ConstrainUntrustedBoundariesRequest(
    Guid SubjectId,
    string Action,
    long ExpectedVersion,
    Guid? CommunityId,
    IReadOnlyDictionary<string, string> Values)
{
    public FeatureInput ToInput() => new(SubjectId, Action, ExpectedVersion, CommunityId, Values);
}

public sealed record ConstrainUntrustedBoundariesRecord(
    Guid Id,
    Guid? CommunityId,
    string State,
    long Version,
    bool IsAuthorized,
    bool IsAvailable)
{
    public FeatureState ToState() => new(Id, CommunityId, State, Version, IsAuthorized, IsAvailable);
}

public sealed record ConstrainUntrustedBoundariesDecision(
    string RequirementId,
    FeatureDecisionKind Kind,
    string Code,
    string ResultingState,
    long ResultingVersion)
{
    public bool IsAccepted => Kind == FeatureDecisionKind.Accepted;

    public static ConstrainUntrustedBoundariesDecision From(FeatureDecision decision) =>
        new(decision.RequirementId, decision.Kind, decision.Code, decision.ResultingState, decision.ResultingVersion);
}

public sealed class ConstrainUntrustedBoundariesPolicy
{
    public ConstrainUntrustedBoundariesDecision UntrustedInputIsValidatedAndResourceBounded(
        ConstrainUntrustedBoundariesRecord record,
        ConstrainUntrustedBoundariesRequest request) =>
        ConstrainUntrustedBoundariesDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-SECU-007", record.ToState(), request.ToInput()));

    public ConstrainUntrustedBoundariesDecision UploadsValidateContentAndIsolateStoragePaths(
        ConstrainUntrustedBoundariesRecord record,
        ConstrainUntrustedBoundariesRequest request) =>
        ConstrainUntrustedBoundariesDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-SECU-008", record.ToState(), request.ToInput()));

    public ConstrainUntrustedBoundariesDecision SecuritySensitiveWorkflowTransitionsFailClosed(
        ConstrainUntrustedBoundariesRecord record,
        ConstrainUntrustedBoundariesRequest request) =>
        ConstrainUntrustedBoundariesDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-SECU-009", record.ToState(), request.ToInput()));

    public ConstrainUntrustedBoundariesDecision RenderUntrustedTextLinksAndExportsSafely(
        ConstrainUntrustedBoundariesRecord record,
        ConstrainUntrustedBoundariesRequest request) =>
        ConstrainUntrustedBoundariesDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-SECU-017", record.ToState(), request.ToInput()));
}

public static class ConstrainUntrustedBoundariesDescriptor
{
    public const string Subsystem = "security";
    public const string Slug = "constrain-untrusted-boundaries";
    public const string Title = "Constrain every untrusted boundary";

    public static IReadOnlyList<FeatureOperationDescriptor> Operations { get; } =
    [
        new("L2-SECU-007", "UntrustedInputIsValidatedAndResourceBounded"),
        new("L2-SECU-008", "UploadsValidateContentAndIsolateStoragePaths"),
        new("L2-SECU-009", "SecuritySensitiveWorkflowTransitionsFailClosed"),
        new("L2-SECU-017", "RenderUntrustedTextLinksAndExportsSafely")
    ];
}
