// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;

namespace CommunityStarter.Domain.GeneratedFeatures;

public sealed record ControlMembershipLifecycleRequest(
    Guid SubjectId,
    string Action,
    long ExpectedVersion,
    Guid? CommunityId,
    IReadOnlyDictionary<string, string> Values)
{
    public FeatureInput ToInput() => new(SubjectId, Action, ExpectedVersion, CommunityId, Values);
}

public sealed record ControlMembershipLifecycleRecord(
    Guid Id,
    Guid? CommunityId,
    string State,
    long Version,
    bool IsAuthorized,
    bool IsAvailable)
{
    public FeatureState ToState() => new(Id, CommunityId, State, Version, IsAuthorized, IsAvailable);
}

public sealed record ControlMembershipLifecycleDecision(
    string RequirementId,
    FeatureDecisionKind Kind,
    string Code,
    string ResultingState,
    long ResultingVersion)
{
    public bool IsAccepted => Kind == FeatureDecisionKind.Accepted;

    public static ControlMembershipLifecycleDecision From(FeatureDecision decision) =>
        new(decision.RequirementId, decision.Kind, decision.Code, decision.ResultingState, decision.ResultingVersion);
}

public sealed class ControlMembershipLifecyclePolicy
{
    public ControlMembershipLifecycleDecision JoinAnOpenCommunity(
        ControlMembershipLifecycleRecord record,
        ControlMembershipLifecycleRequest request) =>
        ControlMembershipLifecycleDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-COMM-004", record.ToState(), request.ToInput()));

    public ControlMembershipLifecycleDecision RequestGatedMembership(
        ControlMembershipLifecycleRecord record,
        ControlMembershipLifecycleRequest request) =>
        ControlMembershipLifecycleDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-COMM-005", record.ToState(), request.ToInput()));

    public ControlMembershipLifecycleDecision InviteAnAccount(
        ControlMembershipLifecycleRecord record,
        ControlMembershipLifecycleRequest request) =>
        ControlMembershipLifecycleDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-COMM-006", record.ToState(), request.ToInput()));

    public ControlMembershipLifecycleDecision LeaveRemoveAndSuspend(
        ControlMembershipLifecycleRecord record,
        ControlMembershipLifecycleRequest request) =>
        ControlMembershipLifecycleDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-COMM-007", record.ToState(), request.ToInput()));

    public ControlMembershipLifecycleDecision RejoinWithoutDuplicatingMembershipIdentity(
        ControlMembershipLifecycleRecord record,
        ControlMembershipLifecycleRequest request) =>
        ControlMembershipLifecycleDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-COMM-017", record.ToState(), request.ToInput()));
}

public static class ControlMembershipLifecycleDescriptor
{
    public const string Subsystem = "communities-membership";
    public const string Slug = "control-membership-lifecycle";
    public const string Title = "Control Membership lifecycle";

    public static IReadOnlyList<FeatureOperationDescriptor> Operations { get; } =
    [
        new("L2-COMM-004", "JoinAnOpenCommunity"),
        new("L2-COMM-005", "RequestGatedMembership"),
        new("L2-COMM-006", "InviteAnAccount"),
        new("L2-COMM-007", "LeaveRemoveAndSuspend"),
        new("L2-COMM-017", "RejoinWithoutDuplicatingMembershipIdentity")
    ];
}
