// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;

namespace CommunityStarter.Domain.GeneratedFeatures;

public sealed record ControlPersonalDataRequest(
    Guid SubjectId,
    string Action,
    long ExpectedVersion,
    Guid? CommunityId,
    IReadOnlyDictionary<string, string> Values)
{
    public FeatureInput ToInput() => new(SubjectId, Action, ExpectedVersion, CommunityId, Values);
}

public sealed record ControlPersonalDataRecord(
    Guid Id,
    Guid? CommunityId,
    string State,
    long Version,
    bool IsAuthorized,
    bool IsAvailable)
{
    public FeatureState ToState() => new(Id, CommunityId, State, Version, IsAuthorized, IsAvailable);
}

public sealed record ControlPersonalDataDecision(
    string RequirementId,
    FeatureDecisionKind Kind,
    string Code,
    string ResultingState,
    long ResultingVersion)
{
    public bool IsAccepted => Kind == FeatureDecisionKind.Accepted;

    public static ControlPersonalDataDecision From(FeatureDecision decision) =>
        new(decision.RequirementId, decision.Kind, decision.Code, decision.ResultingState, decision.ResultingVersion);
}

public sealed class ControlPersonalDataPolicy
{
    public ControlPersonalDataDecision CorrectControllablePersonalData(
        ControlPersonalDataRecord record,
        ControlPersonalDataRequest request) =>
        ControlPersonalDataDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-PRIV-005", record.ToState(), request.ToInput()));

    public ControlPersonalDataDecision ExportPersonalDataSecurely(
        ControlPersonalDataRecord record,
        ControlPersonalDataRequest request) =>
        ControlPersonalDataDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-PRIV-006", record.ToState(), request.ToInput()));

    public ControlPersonalDataDecision DeactivateAndRestoreAnAccount(
        ControlPersonalDataRecord record,
        ControlPersonalDataRequest request) =>
        ControlPersonalDataDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-PRIV-007", record.ToState(), request.ToInput()));

    public ControlPersonalDataDecision CompleteAnAccountDeletionRequest(
        ControlPersonalDataRecord record,
        ControlPersonalDataRequest request) =>
        ControlPersonalDataDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-PRIV-008", record.ToState(), request.ToInput()));

    public ControlPersonalDataDecision ResolveDependentResponsibilitiesBeforeAccountExit(
        ControlPersonalDataRecord record,
        ControlPersonalDataRequest request) =>
        ControlPersonalDataDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-PRIV-016", record.ToState(), request.ToInput()));
}

public static class ControlPersonalDataDescriptor
{
    public const string Subsystem = "privacy-data-lifecycle";
    public const string Slug = "control-personal-data";
    public const string Title = "People can access and control their data";

    public static IReadOnlyList<FeatureOperationDescriptor> Operations { get; } =
    [
        new("L2-PRIV-005", "CorrectControllablePersonalData"),
        new("L2-PRIV-006", "ExportPersonalDataSecurely"),
        new("L2-PRIV-007", "DeactivateAndRestoreAnAccount"),
        new("L2-PRIV-008", "CompleteAnAccountDeletionRequest"),
        new("L2-PRIV-016", "ResolveDependentResponsibilitiesBeforeAccountExit")
    ];
}
