// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;

namespace CommunityStarter.Domain.GeneratedFeatures;

public sealed record ControlPlatformConfigurationRequest(
    Guid SubjectId,
    string Action,
    long ExpectedVersion,
    Guid? CommunityId,
    IReadOnlyDictionary<string, string> Values)
{
    public FeatureInput ToInput() => new(SubjectId, Action, ExpectedVersion, CommunityId, Values);
}

public sealed record ControlPlatformConfigurationRecord(
    Guid Id,
    Guid? CommunityId,
    string State,
    long Version,
    bool IsAuthorized,
    bool IsAvailable)
{
    public FeatureState ToState() => new(Id, CommunityId, State, Version, IsAuthorized, IsAvailable);
}

public sealed record ControlPlatformConfigurationDecision(
    string RequirementId,
    FeatureDecisionKind Kind,
    string Code,
    string ResultingState,
    long ResultingVersion)
{
    public bool IsAccepted => Kind == FeatureDecisionKind.Accepted;

    public static ControlPlatformConfigurationDecision From(FeatureDecision decision) =>
        new(decision.RequirementId, decision.Kind, decision.Code, decision.ResultingState, decision.ResultingVersion);
}

public sealed class ControlPlatformConfigurationPolicy
{
    public ControlPlatformConfigurationDecision PreserveConfigurationHistoryAndRollback(
        ControlPlatformConfigurationRecord record,
        ControlPlatformConfigurationRequest request) =>
        ControlPlatformConfigurationDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-ADMN-008", record.ToState(), request.ToInput()));

    public ControlPlatformConfigurationDecision GovernFeatureFlagsAndKillSwitches(
        ControlPlatformConfigurationRecord record,
        ControlPlatformConfigurationRequest request) =>
        ControlPlatformConfigurationDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-ADMN-009", record.ToState(), request.ToInput()));
}

public static class ControlPlatformConfigurationDescriptor
{
    public const string Subsystem = "administration-insights";
    public const string Slug = "control-platform-configuration";
    public const string Title = "Controlled platform configuration";

    public static IReadOnlyList<FeatureOperationDescriptor> Operations { get; } =
    [
        new("L2-ADMN-008", "PreserveConfigurationHistoryAndRollback"),
        new("L2-ADMN-009", "GovernFeatureFlagsAndKillSwitches")
    ];
}
