// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;

namespace CommunityStarter.Domain.GeneratedFeatures;

public sealed record ControlPlatformSupportAccessRequest(
    Guid SubjectId,
    string Action,
    long ExpectedVersion,
    Guid? CommunityId,
    IReadOnlyDictionary<string, string> Values)
{
    public FeatureInput ToInput() => new(SubjectId, Action, ExpectedVersion, CommunityId, Values);
}

public sealed record ControlPlatformSupportAccessRecord(
    Guid Id,
    Guid? CommunityId,
    string State,
    long Version,
    bool IsAuthorized,
    bool IsAvailable)
{
    public FeatureState ToState() => new(Id, CommunityId, State, Version, IsAuthorized, IsAvailable);
}

public sealed record ControlPlatformSupportAccessDecision(
    string RequirementId,
    FeatureDecisionKind Kind,
    string Code,
    string ResultingState,
    long ResultingVersion)
{
    public bool IsAccepted => Kind == FeatureDecisionKind.Accepted;

    public static ControlPlatformSupportAccessDecision From(FeatureDecision decision) =>
        new(decision.RequirementId, decision.Kind, decision.Code, decision.ResultingState, decision.ResultingVersion);
}

public sealed class ControlPlatformSupportAccessPolicy
{
    public ControlPlatformSupportAccessDecision SeparateOperatorResponsibilities(
        ControlPlatformSupportAccessRecord record,
        ControlPlatformSupportAccessRequest request) =>
        ControlPlatformSupportAccessDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-ADMN-004", record.ToState(), request.ToInput()));

    public ControlPlatformSupportAccessDecision GrantPurposeBoundSupportAccess(
        ControlPlatformSupportAccessRecord record,
        ControlPlatformSupportAccessRequest request) =>
        ControlPlatformSupportAccessDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-ADMN-005", record.ToState(), request.ToInput()));

    public ControlPlatformSupportAccessDecision MaintainSupportCaseLifecycle(
        ControlPlatformSupportAccessRecord record,
        ControlPlatformSupportAccessRequest request) =>
        ControlPlatformSupportAccessDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-ADMN-013", record.ToState(), request.ToInput()));

    public ControlPlatformSupportAccessDecision ProvisionAndPreserveOperatorAuthority(
        ControlPlatformSupportAccessRecord record,
        ControlPlatformSupportAccessRequest request) =>
        ControlPlatformSupportAccessDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-ADMN-014", record.ToState(), request.ToInput()));
}

public static class ControlPlatformSupportAccessDescriptor
{
    public const string Subsystem = "administration-insights";
    public const string Slug = "control-platform-support-access";
    public const string Title = "Least-privilege platform and support access";

    public static IReadOnlyList<FeatureOperationDescriptor> Operations { get; } =
    [
        new("L2-ADMN-004", "SeparateOperatorResponsibilities"),
        new("L2-ADMN-005", "GrantPurposeBoundSupportAccess"),
        new("L2-ADMN-013", "MaintainSupportCaseLifecycle"),
        new("L2-ADMN-014", "ProvisionAndPreserveOperatorAuthority")
    ];
}
