// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;

namespace CommunityStarter.Domain.GeneratedFeatures;

public sealed record CoordinateSafeParticipationRequest(
    Guid SubjectId,
    string Action,
    long ExpectedVersion,
    Guid? CommunityId,
    IReadOnlyDictionary<string, string> Values)
{
    public FeatureInput ToInput() => new(SubjectId, Action, ExpectedVersion, CommunityId, Values);
}

public sealed record CoordinateSafeParticipationRecord(
    Guid Id,
    Guid? CommunityId,
    string State,
    long Version,
    bool IsAuthorized,
    bool IsAvailable)
{
    public FeatureState ToState() => new(Id, CommunityId, State, Version, IsAuthorized, IsAvailable);
}

public sealed record CoordinateSafeParticipationDecision(
    string RequirementId,
    FeatureDecisionKind Kind,
    string Code,
    string ResultingState,
    long ResultingVersion)
{
    public bool IsAccepted => Kind == FeatureDecisionKind.Accepted;

    public static CoordinateSafeParticipationDecision From(FeatureDecision decision) =>
        new(decision.RequirementId, decision.Kind, decision.Code, decision.ResultingState, decision.ResultingVersion);
}

public sealed class CoordinateSafeParticipationPolicy
{
    public CoordinateSafeParticipationDecision NotifyEligibleAttendeesOfChanges(
        CoordinateSafeParticipationRecord record,
        CoordinateSafeParticipationRequest request) =>
        CoordinateSafeParticipationDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-EVNT-010", record.ToState(), request.ToInput()));

    public CoordinateSafeParticipationDecision ReportAndModerateEventHarm(
        CoordinateSafeParticipationRecord record,
        CoordinateSafeParticipationRequest request) =>
        CoordinateSafeParticipationDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-EVNT-012", record.ToState(), request.ToInput()));
}

public static class CoordinateSafeParticipationDescriptor
{
    public const string Subsystem = "community-events";
    public const string Slug = "coordinate-safe-participation";
    public const string Title = "Coordinated and safe participation";

    public static IReadOnlyList<FeatureOperationDescriptor> Operations { get; } =
    [
        new("L2-EVNT-010", "NotifyEligibleAttendeesOfChanges"),
        new("L2-EVNT-012", "ReportAndModerateEventHarm")
    ];
}
