// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;

namespace CommunityStarter.Domain.GeneratedFeatures;

public sealed record DelegateCommunityAuthorityRequest(
    Guid SubjectId,
    string Action,
    long ExpectedVersion,
    Guid? CommunityId,
    IReadOnlyDictionary<string, string> Values)
{
    public FeatureInput ToInput() => new(SubjectId, Action, ExpectedVersion, CommunityId, Values);
}

public sealed record DelegateCommunityAuthorityRecord(
    Guid Id,
    Guid? CommunityId,
    string State,
    long Version,
    bool IsAuthorized,
    bool IsAvailable)
{
    public FeatureState ToState() => new(Id, CommunityId, State, Version, IsAuthorized, IsAvailable);
}

public sealed record DelegateCommunityAuthorityDecision(
    string RequirementId,
    FeatureDecisionKind Kind,
    string Code,
    string ResultingState,
    long ResultingVersion)
{
    public bool IsAccepted => Kind == FeatureDecisionKind.Accepted;

    public static DelegateCommunityAuthorityDecision From(FeatureDecision decision) =>
        new(decision.RequirementId, decision.Kind, decision.Code, decision.ResultingState, decision.ResultingVersion);
}

public sealed class DelegateCommunityAuthorityPolicy
{
    public DelegateCommunityAuthorityDecision ManageRolesAndPermissions(
        DelegateCommunityAuthorityRecord record,
        DelegateCommunityAuthorityRequest request) =>
        DelegateCommunityAuthorityDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-COMM-008", record.ToState(), request.ToInput()));

    public DelegateCommunityAuthorityDecision AssignARoleSafely(
        DelegateCommunityAuthorityRecord record,
        DelegateCommunityAuthorityRequest request) =>
        DelegateCommunityAuthorityDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-COMM-009", record.ToState(), request.ToInput()));

    public DelegateCommunityAuthorityDecision PreserveAdministrativeContinuity(
        DelegateCommunityAuthorityRecord record,
        DelegateCommunityAuthorityRequest request) =>
        DelegateCommunityAuthorityDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-COMM-010", record.ToState(), request.ToInput()));
}

public static class DelegateCommunityAuthorityDescriptor
{
    public const string Subsystem = "communities-membership";
    public const string Slug = "delegate-community-authority";
    public const string Title = "Delegate Community authority";

    public static IReadOnlyList<FeatureOperationDescriptor> Operations { get; } =
    [
        new("L2-COMM-008", "ManageRolesAndPermissions"),
        new("L2-COMM-009", "AssignARoleSafely"),
        new("L2-COMM-010", "PreserveAdministrativeContinuity")
    ];
}
