// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;

namespace CommunityStarter.Domain.GeneratedFeatures;

public sealed record DeliverUsefulFeedsRequest(
    Guid SubjectId,
    string Action,
    long ExpectedVersion,
    Guid? CommunityId,
    IReadOnlyDictionary<string, string> Values)
{
    public FeatureInput ToInput() => new(SubjectId, Action, ExpectedVersion, CommunityId, Values);
}

public sealed record DeliverUsefulFeedsRecord(
    Guid Id,
    Guid? CommunityId,
    string State,
    long Version,
    bool IsAuthorized,
    bool IsAvailable)
{
    public FeatureState ToState() => new(Id, CommunityId, State, Version, IsAuthorized, IsAvailable);
}

public sealed record DeliverUsefulFeedsDecision(
    string RequirementId,
    FeatureDecisionKind Kind,
    string Code,
    string ResultingState,
    long ResultingVersion)
{
    public bool IsAccepted => Kind == FeatureDecisionKind.Accepted;

    public static DeliverUsefulFeedsDecision From(FeatureDecision decision) =>
        new(decision.RequirementId, decision.Kind, decision.Code, decision.ResultingState, decision.ResultingVersion);
}

public sealed class DeliverUsefulFeedsPolicy
{
    public DeliverUsefulFeedsDecision BuildTheAccountFeed(
        DeliverUsefulFeedsRecord record,
        DeliverUsefulFeedsRequest request) =>
        DeliverUsefulFeedsDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-DISC-001", record.ToState(), request.ToInput()));

    public DeliverUsefulFeedsDecision BuildACommunityFeed(
        DeliverUsefulFeedsRecord record,
        DeliverUsefulFeedsRequest request) =>
        DeliverUsefulFeedsDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-DISC-002", record.ToState(), request.ToInput()));

    public DeliverUsefulFeedsDecision PageAFeedConsistently(
        DeliverUsefulFeedsRecord record,
        DeliverUsefulFeedsRequest request) =>
        DeliverUsefulFeedsDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-DISC-003", record.ToState(), request.ToInput()));

    public DeliverUsefulFeedsDecision ExplainAndControlRanking(
        DeliverUsefulFeedsRecord record,
        DeliverUsefulFeedsRequest request) =>
        DeliverUsefulFeedsDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-DISC-004", record.ToState(), request.ToInput()));
}

public static class DeliverUsefulFeedsDescriptor
{
    public const string Subsystem = "feeds-search-engagement";
    public const string Slug = "deliver-useful-feeds";
    public const string Title = "Deliver useful Feeds";

    public static IReadOnlyList<FeatureOperationDescriptor> Operations { get; } =
    [
        new("L2-DISC-001", "BuildTheAccountFeed"),
        new("L2-DISC-002", "BuildACommunityFeed"),
        new("L2-DISC-003", "PageAFeedConsistently"),
        new("L2-DISC-004", "ExplainAndControlRanking")
    ];
}
