// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;

namespace CommunityStarter.Domain.GeneratedFeatures;

public sealed record DeliverExternalNotificationsRequest(
    Guid SubjectId,
    string Action,
    long ExpectedVersion,
    Guid? CommunityId,
    IReadOnlyDictionary<string, string> Values)
{
    public FeatureInput ToInput() => new(SubjectId, Action, ExpectedVersion, CommunityId, Values);
}

public sealed record DeliverExternalNotificationsRecord(
    Guid Id,
    Guid? CommunityId,
    string State,
    long Version,
    bool IsAuthorized,
    bool IsAvailable)
{
    public FeatureState ToState() => new(Id, CommunityId, State, Version, IsAuthorized, IsAvailable);
}

public sealed record DeliverExternalNotificationsDecision(
    string RequirementId,
    FeatureDecisionKind Kind,
    string Code,
    string ResultingState,
    long ResultingVersion)
{
    public bool IsAccepted => Kind == FeatureDecisionKind.Accepted;

    public static DeliverExternalNotificationsDecision From(FeatureDecision decision) =>
        new(decision.RequirementId, decision.Kind, decision.Code, decision.ResultingState, decision.ResultingVersion);
}

public sealed class DeliverExternalNotificationsPolicy
{
    public DeliverExternalNotificationsDecision AttemptEachDeliveryIdempotently(
        DeliverExternalNotificationsRecord record,
        DeliverExternalNotificationsRequest request) =>
        DeliverExternalNotificationsDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-NOTF-007", record.ToState(), request.ToInput()));

    public DeliverExternalNotificationsDecision RetryAndQuarantineTerminalFailures(
        DeliverExternalNotificationsRecord record,
        DeliverExternalNotificationsRequest request) =>
        DeliverExternalNotificationsDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-NOTF-008", record.ToState(), request.ToInput()));

    public DeliverExternalNotificationsDecision ProcessUnsubscribeAndProviderFeedback(
        DeliverExternalNotificationsRecord record,
        DeliverExternalNotificationsRequest request) =>
        DeliverExternalNotificationsDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-NOTF-009", record.ToState(), request.ToInput()));

    public DeliverExternalNotificationsDecision VerifyAndRetireEmailDestinations(
        DeliverExternalNotificationsRecord record,
        DeliverExternalNotificationsRequest request) =>
        DeliverExternalNotificationsDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-NOTF-013", record.ToState(), request.ToInput()));
}

public static class DeliverExternalNotificationsDescriptor
{
    public const string Subsystem = "notifications-delivery";
    public const string Slug = "deliver-external-notifications";
    public const string Title = "Durable external Delivery";

    public static IReadOnlyList<FeatureOperationDescriptor> Operations { get; } =
    [
        new("L2-NOTF-007", "AttemptEachDeliveryIdempotently"),
        new("L2-NOTF-008", "RetryAndQuarantineTerminalFailures"),
        new("L2-NOTF-009", "ProcessUnsubscribeAndProviderFeedback"),
        new("L2-NOTF-013", "VerifyAndRetireEmailDestinations")
    ];
}
