// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;

namespace CommunityStarter.Domain.GeneratedFeatures;

public sealed record DeliverTruthfulPublicSurfaceRequest(
    Guid SubjectId,
    string Action,
    long ExpectedVersion,
    Guid? CommunityId,
    IReadOnlyDictionary<string, string> Values)
{
    public FeatureInput ToInput() => new(SubjectId, Action, ExpectedVersion, CommunityId, Values);
}

public sealed record DeliverTruthfulPublicSurfaceRecord(
    Guid Id,
    Guid? CommunityId,
    string State,
    long Version,
    bool IsAuthorized,
    bool IsAvailable)
{
    public FeatureState ToState() => new(Id, CommunityId, State, Version, IsAuthorized, IsAvailable);
}

public sealed record DeliverTruthfulPublicSurfaceDecision(
    string RequirementId,
    FeatureDecisionKind Kind,
    string Code,
    string ResultingState,
    long ResultingVersion)
{
    public bool IsAccepted => Kind == FeatureDecisionKind.Accepted;

    public static DeliverTruthfulPublicSurfaceDecision From(FeatureDecision decision) =>
        new(decision.RequirementId, decision.Kind, decision.Code, decision.ResultingState, decision.ResultingVersion);
}

public sealed class DeliverTruthfulPublicSurfacePolicy
{
    public DeliverTruthfulPublicSurfaceDecision MarketingRemainsStaticAndRuntimeIndependent(
        DeliverTruthfulPublicSurfaceRecord record,
        DeliverTruthfulPublicSurfaceRequest request) =>
        DeliverTruthfulPublicSurfaceDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-MKTG-001", record.ToState(), request.ToInput()));

    public DeliverTruthfulPublicSurfaceDecision ContentFollowsAClearOutcomeToActionNarrative(
        DeliverTruthfulPublicSurfaceRecord record,
        DeliverTruthfulPublicSurfaceRequest request) =>
        DeliverTruthfulPublicSurfaceDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-MKTG-002", record.ToState(), request.ToInput()));

    public DeliverTruthfulPublicSurfaceDecision CallsToActionAndProductClaimsAreHonestAndStable(
        DeliverTruthfulPublicSurfaceRecord record,
        DeliverTruthfulPublicSurfaceRequest request) =>
        DeliverTruthfulPublicSurfaceDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-MKTG-003", record.ToState(), request.ToInput()));
}

public static class DeliverTruthfulPublicSurfaceDescriptor
{
    public const string Subsystem = "marketing-public-web";
    public const string Slug = "deliver-truthful-public-surface";
    public const string Title = "Deliver an independent and truthful public surface";

    public static IReadOnlyList<FeatureOperationDescriptor> Operations { get; } =
    [
        new("L2-MKTG-001", "MarketingRemainsStaticAndRuntimeIndependent"),
        new("L2-MKTG-002", "ContentFollowsAClearOutcomeToActionNarrative"),
        new("L2-MKTG-003", "CallsToActionAndProductClaimsAreHonestAndStable")
    ];
}
