// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;

namespace CommunityStarter.Domain.GeneratedFeatures;

public sealed record DeliverDurableMessagesRequest(
    Guid SubjectId,
    string Action,
    long ExpectedVersion,
    Guid? CommunityId,
    IReadOnlyDictionary<string, string> Values)
{
    public FeatureInput ToInput() => new(SubjectId, Action, ExpectedVersion, CommunityId, Values);
}

public sealed record DeliverDurableMessagesRecord(
    Guid Id,
    Guid? CommunityId,
    string State,
    long Version,
    bool IsAuthorized,
    bool IsAvailable)
{
    public FeatureState ToState() => new(Id, CommunityId, State, Version, IsAuthorized, IsAvailable);
}

public sealed record DeliverDurableMessagesDecision(
    string RequirementId,
    FeatureDecisionKind Kind,
    string Code,
    string ResultingState,
    long ResultingVersion)
{
    public bool IsAccepted => Kind == FeatureDecisionKind.Accepted;

    public static DeliverDurableMessagesDecision From(FeatureDecision decision) =>
        new(decision.RequirementId, decision.Kind, decision.Code, decision.ResultingState, decision.ResultingVersion);
}

public sealed class DeliverDurableMessagesPolicy
{
    public DeliverDurableMessagesDecision CommitOneValidatedMessage(
        DeliverDurableMessagesRecord record,
        DeliverDurableMessagesRequest request) =>
        DeliverDurableMessagesDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-MESS-004", record.ToState(), request.ToInput()));

    public DeliverDurableMessagesDecision PageMessagesAndTrackReadingPrivately(
        DeliverDurableMessagesRecord record,
        DeliverDurableMessagesRequest request) =>
        DeliverDurableMessagesDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-MESS-006", record.ToState(), request.ToInput()));

    public DeliverDurableMessagesDecision ApplyEditDeletionAndRetentionPolicy(
        DeliverDurableMessagesRecord record,
        DeliverDurableMessagesRequest request) =>
        DeliverDurableMessagesDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-MESS-007", record.ToState(), request.ToInput()));

    public DeliverDurableMessagesDecision ReportAMessageWithoutLosingEvidence(
        DeliverDurableMessagesRecord record,
        DeliverDurableMessagesRequest request) =>
        DeliverDurableMessagesDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-MESS-008", record.ToState(), request.ToInput()));
}

public static class DeliverDurableMessagesDescriptor
{
    public const string Subsystem = "messaging-realtime";
    public const string Slug = "deliver-durable-messages";
    public const string Title = "Durable and safe Messages";

    public static IReadOnlyList<FeatureOperationDescriptor> Operations { get; } =
    [
        new("L2-MESS-004", "CommitOneValidatedMessage"),
        new("L2-MESS-006", "PageMessagesAndTrackReadingPrivately"),
        new("L2-MESS-007", "ApplyEditDeletionAndRetentionPolicy"),
        new("L2-MESS-008", "ReportAMessageWithoutLosingEvidence")
    ];
}
