// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;

namespace CommunityStarter.Domain.GeneratedFeatures;

public sealed record DeliverPrivacySafeInsightsRequest(
    Guid SubjectId,
    string Action,
    long ExpectedVersion,
    Guid? CommunityId,
    IReadOnlyDictionary<string, string> Values)
{
    public FeatureInput ToInput() => new(SubjectId, Action, ExpectedVersion, CommunityId, Values);
}

public sealed record DeliverPrivacySafeInsightsRecord(
    Guid Id,
    Guid? CommunityId,
    string State,
    long Version,
    bool IsAuthorized,
    bool IsAvailable)
{
    public FeatureState ToState() => new(Id, CommunityId, State, Version, IsAuthorized, IsAvailable);
}

public sealed record DeliverPrivacySafeInsightsDecision(
    string RequirementId,
    FeatureDecisionKind Kind,
    string Code,
    string ResultingState,
    long ResultingVersion)
{
    public bool IsAccepted => Kind == FeatureDecisionKind.Accepted;

    public static DeliverPrivacySafeInsightsDecision From(FeatureDecision decision) =>
        new(decision.RequirementId, decision.Kind, decision.Code, decision.ResultingState, decision.ResultingVersion);
}

public sealed class DeliverPrivacySafeInsightsPolicy
{
    public DeliverPrivacySafeInsightsDecision PublishGovernedMetricDefinitions(
        DeliverPrivacySafeInsightsRecord record,
        DeliverPrivacySafeInsightsRequest request) =>
        DeliverPrivacySafeInsightsDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-ADMN-010", record.ToState(), request.ToInput()));

    public DeliverPrivacySafeInsightsDecision EnforceInsightScopeAndPrivacy(
        DeliverPrivacySafeInsightsRecord record,
        DeliverPrivacySafeInsightsRequest request) =>
        DeliverPrivacySafeInsightsDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-ADMN-011", record.ToState(), request.ToInput()));
}

public static class DeliverPrivacySafeInsightsDescriptor
{
    public const string Subsystem = "administration-insights";
    public const string Slug = "deliver-privacy-safe-insights";
    public const string Title = "Privacy-safe actionable insights";

    public static IReadOnlyList<FeatureOperationDescriptor> Operations { get; } =
    [
        new("L2-ADMN-010", "PublishGovernedMetricDefinitions"),
        new("L2-ADMN-011", "EnforceInsightScopeAndPrivacy")
    ];
}
