// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;

namespace CommunityStarter.Domain.GeneratedFeatures;

public sealed record DeliverPrivateNotificationsRequest(
    Guid SubjectId,
    string Action,
    long ExpectedVersion,
    Guid? CommunityId,
    IReadOnlyDictionary<string, string> Values)
{
    public FeatureInput ToInput() => new(SubjectId, Action, ExpectedVersion, CommunityId, Values);
}

public sealed record DeliverPrivateNotificationsRecord(
    Guid Id,
    Guid? CommunityId,
    string State,
    long Version,
    bool IsAuthorized,
    bool IsAvailable)
{
    public FeatureState ToState() => new(Id, CommunityId, State, Version, IsAuthorized, IsAvailable);
}

public sealed record DeliverPrivateNotificationsDecision(
    string RequirementId,
    FeatureDecisionKind Kind,
    string Code,
    string ResultingState,
    long ResultingVersion)
{
    public bool IsAccepted => Kind == FeatureDecisionKind.Accepted;

    public static DeliverPrivateNotificationsDecision From(FeatureDecision decision) =>
        new(decision.RequirementId, decision.Kind, decision.Code, decision.ResultingState, decision.ResultingVersion);
}

public sealed class DeliverPrivateNotificationsPolicy
{
    public DeliverPrivateNotificationsDecision CreateNotificationsAfterCommit(
        DeliverPrivateNotificationsRecord record,
        DeliverPrivateNotificationsRequest request) =>
        DeliverPrivateNotificationsDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-NOTF-001", record.ToState(), request.ToInput()));

    public DeliverPrivateNotificationsDecision RecheckRecipientEligibility(
        DeliverPrivateNotificationsRecord record,
        DeliverPrivateNotificationsRequest request) =>
        DeliverPrivateNotificationsDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-NOTF-002", record.ToState(), request.ToInput()));

    public DeliverPrivateNotificationsDecision MaintainAUsableNotificationInbox(
        DeliverPrivateNotificationsRecord record,
        DeliverPrivateNotificationsRequest request) =>
        DeliverPrivateNotificationsDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-NOTF-003", record.ToState(), request.ToInput()));
}

public static class DeliverPrivateNotificationsDescriptor
{
    public const string Subsystem = "notifications-delivery";
    public const string Slug = "deliver-private-notifications";
    public const string Title = "Relevant and private Notifications";

    public static IReadOnlyList<FeatureOperationDescriptor> Operations { get; } =
    [
        new("L2-NOTF-001", "CreateNotificationsAfterCommit"),
        new("L2-NOTF-002", "RecheckRecipientEligibility"),
        new("L2-NOTF-003", "MaintainAUsableNotificationInbox")
    ];
}
