// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;

namespace CommunityStarter.Domain.GeneratedFeatures;

public sealed record EnforceServerAuthorizationRequest(
    Guid SubjectId,
    string Action,
    long ExpectedVersion,
    Guid? CommunityId,
    IReadOnlyDictionary<string, string> Values)
{
    public FeatureInput ToInput() => new(SubjectId, Action, ExpectedVersion, CommunityId, Values);
}

public sealed record EnforceServerAuthorizationRecord(
    Guid Id,
    Guid? CommunityId,
    string State,
    long Version,
    bool IsAuthorized,
    bool IsAvailable)
{
    public FeatureState ToState() => new(Id, CommunityId, State, Version, IsAuthorized, IsAvailable);
}

public sealed record EnforceServerAuthorizationDecision(
    string RequirementId,
    FeatureDecisionKind Kind,
    string Code,
    string ResultingState,
    long ResultingVersion)
{
    public bool IsAccepted => Kind == FeatureDecisionKind.Accepted;

    public static EnforceServerAuthorizationDecision From(FeatureDecision decision) =>
        new(decision.RequirementId, decision.Kind, decision.Code, decision.ResultingState, decision.ResultingVersion);
}

public sealed class EnforceServerAuthorizationPolicy
{
    public EnforceServerAuthorizationDecision EvaluateCurrentPermissions(
        EnforceServerAuthorizationRecord record,
        EnforceServerAuthorizationRequest request) =>
        EnforceServerAuthorizationDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-AUTH-008", record.ToState(), request.ToInput()));

    public EnforceServerAuthorizationDecision EnforceCommunityBoundaries(
        EnforceServerAuthorizationRecord record,
        EnforceServerAuthorizationRequest request) =>
        EnforceServerAuthorizationDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-AUTH-009", record.ToState(), request.ToInput()));

    public EnforceServerAuthorizationDecision ExposeAllowedActionsSafely(
        EnforceServerAuthorizationRecord record,
        EnforceServerAuthorizationRequest request) =>
        EnforceServerAuthorizationDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-AUTH-010", record.ToState(), request.ToInput()));
}

public static class EnforceServerAuthorizationDescriptor
{
    public const string Subsystem = "identity-access";
    public const string Slug = "enforce-server-authorization";
    public const string Title = "Server-owned authorization";

    public static IReadOnlyList<FeatureOperationDescriptor> Operations { get; } =
    [
        new("L2-AUTH-008", "EvaluateCurrentPermissions"),
        new("L2-AUTH-009", "EnforceCommunityBoundaries"),
        new("L2-AUTH-010", "ExposeAllowedActionsSafely")
    ];
}
