// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;

namespace CommunityStarter.Domain.GeneratedFeatures;

public sealed record EnforceEventAccessRequest(
    Guid SubjectId,
    string Action,
    long ExpectedVersion,
    Guid? CommunityId,
    IReadOnlyDictionary<string, string> Values)
{
    public FeatureInput ToInput() => new(SubjectId, Action, ExpectedVersion, CommunityId, Values);
}

public sealed record EnforceEventAccessRecord(
    Guid Id,
    Guid? CommunityId,
    string State,
    long Version,
    bool IsAuthorized,
    bool IsAvailable)
{
    public FeatureState ToState() => new(Id, CommunityId, State, Version, IsAuthorized, IsAvailable);
}

public sealed record EnforceEventAccessDecision(
    string RequirementId,
    FeatureDecisionKind Kind,
    string Code,
    string ResultingState,
    long ResultingVersion)
{
    public bool IsAccepted => Kind == FeatureDecisionKind.Accepted;

    public static EnforceEventAccessDecision From(FeatureDecision decision) =>
        new(decision.RequirementId, decision.Kind, decision.Code, decision.ResultingState, decision.ResultingVersion);
}

public sealed class EnforceEventAccessPolicy
{
    public EnforceEventAccessDecision AuthorizeEventOrganizers(
        EnforceEventAccessRecord record,
        EnforceEventAccessRequest request) =>
        EnforceEventAccessDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-EVNT-004", record.ToState(), request.ToInput()));

    public EnforceEventAccessDecision EnforceEventAudienceAndDiscovery(
        EnforceEventAccessRecord record,
        EnforceEventAccessRequest request) =>
        EnforceEventAccessDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-EVNT-005", record.ToState(), request.ToInput()));

    public EnforceEventAccessDecision ProtectAttendeeAndLocationPrivacy(
        EnforceEventAccessRecord record,
        EnforceEventAccessRequest request) =>
        EnforceEventAccessDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-EVNT-006", record.ToState(), request.ToInput()));
}

public static class EnforceEventAccessDescriptor
{
    public const string Subsystem = "community-events";
    public const string Slug = "enforce-event-access";
    public const string Title = "Scoped Event access";

    public static IReadOnlyList<FeatureOperationDescriptor> Operations { get; } =
    [
        new("L2-EVNT-004", "AuthorizeEventOrganizers"),
        new("L2-EVNT-005", "EnforceEventAudienceAndDiscovery"),
        new("L2-EVNT-006", "ProtectAttendeeAndLocationPrivacy")
    ];
}
