// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;

namespace CommunityStarter.Domain.GeneratedFeatures;

public sealed record EnforceSecureArtifactPromotionRequest(
    Guid SubjectId,
    string Action,
    long ExpectedVersion,
    Guid? CommunityId,
    IReadOnlyDictionary<string, string> Values)
{
    public FeatureInput ToInput() => new(SubjectId, Action, ExpectedVersion, CommunityId, Values);
}

public sealed record EnforceSecureArtifactPromotionRecord(
    Guid Id,
    Guid? CommunityId,
    string State,
    long Version,
    bool IsAuthorized,
    bool IsAvailable)
{
    public FeatureState ToState() => new(Id, CommunityId, State, Version, IsAuthorized, IsAvailable);
}

public sealed record EnforceSecureArtifactPromotionDecision(
    string RequirementId,
    FeatureDecisionKind Kind,
    string Code,
    string ResultingState,
    long ResultingVersion)
{
    public bool IsAccepted => Kind == FeatureDecisionKind.Accepted;

    public static EnforceSecureArtifactPromotionDecision From(FeatureDecision decision) =>
        new(decision.RequirementId, decision.Kind, decision.Code, decision.ResultingState, decision.ResultingVersion);
}

public sealed class EnforceSecureArtifactPromotionPolicy
{
    public EnforceSecureArtifactPromotionDecision CIRestoresFormatsAnalyzesAndBuildsEveryStack(
        EnforceSecureArtifactPromotionRecord record,
        EnforceSecureArtifactPromotionRequest request) =>
        EnforceSecureArtifactPromotionDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-QUAL-012", record.ToState(), request.ToInput()));

    public EnforceSecureArtifactPromotionDecision CIRunsLayeredTestsAndValidatesSourceArtifacts(
        EnforceSecureArtifactPromotionRecord record,
        EnforceSecureArtifactPromotionRequest request) =>
        EnforceSecureArtifactPromotionDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-QUAL-013", record.ToState(), request.ToInput()));

    public EnforceSecureArtifactPromotionDecision OneVerifiedArtifactIsPromotedWithProtectedCredentials(
        EnforceSecureArtifactPromotionRecord record,
        EnforceSecureArtifactPromotionRequest request) =>
        EnforceSecureArtifactPromotionDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-QUAL-014", record.ToState(), request.ToInput()));

    public EnforceSecureArtifactPromotionDecision DeploymentSmokeChecksReleaseCriticalBehavior(
        EnforceSecureArtifactPromotionRecord record,
        EnforceSecureArtifactPromotionRequest request) =>
        EnforceSecureArtifactPromotionDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-QUAL-015", record.ToState(), request.ToInput()));

    public EnforceSecureArtifactPromotionDecision ProvisionEnvironmentsThroughReviewedInfrastructureCode(
        EnforceSecureArtifactPromotionRecord record,
        EnforceSecureArtifactPromotionRequest request) =>
        EnforceSecureArtifactPromotionDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-QUAL-021", record.ToState(), request.ToInput()));

    public EnforceSecureArtifactPromotionDecision IsolatePreviewAndNonProductionEnvironments(
        EnforceSecureArtifactPromotionRecord record,
        EnforceSecureArtifactPromotionRequest request) =>
        EnforceSecureArtifactPromotionDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-QUAL-023", record.ToState(), request.ToInput()));
}

public static class EnforceSecureArtifactPromotionDescriptor
{
    public const string Subsystem = "delivery-quality";
    public const string Slug = "enforce-secure-artifact-promotion";
    public const string Title = "Enforce one secure build-and-promotion pipeline";

    public static IReadOnlyList<FeatureOperationDescriptor> Operations { get; } =
    [
        new("L2-QUAL-012", "CIRestoresFormatsAnalyzesAndBuildsEveryStack"),
        new("L2-QUAL-013", "CIRunsLayeredTestsAndValidatesSourceArtifacts"),
        new("L2-QUAL-014", "OneVerifiedArtifactIsPromotedWithProtectedCredentials"),
        new("L2-QUAL-015", "DeploymentSmokeChecksReleaseCriticalBehavior"),
        new("L2-QUAL-021", "ProvisionEnvironmentsThroughReviewedInfrastructureCode"),
        new("L2-QUAL-023", "IsolatePreviewAndNonProductionEnvironments")
    ];
}
