// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;

namespace CommunityStarter.Domain.GeneratedFeatures;

public sealed record EnforceProportionateActionsRequest(
    Guid SubjectId,
    string Action,
    long ExpectedVersion,
    Guid? CommunityId,
    IReadOnlyDictionary<string, string> Values)
{
    public FeatureInput ToInput() => new(SubjectId, Action, ExpectedVersion, CommunityId, Values);
}

public sealed record EnforceProportionateActionsRecord(
    Guid Id,
    Guid? CommunityId,
    string State,
    long Version,
    bool IsAuthorized,
    bool IsAvailable)
{
    public FeatureState ToState() => new(Id, CommunityId, State, Version, IsAuthorized, IsAvailable);
}

public sealed record EnforceProportionateActionsDecision(
    string RequirementId,
    FeatureDecisionKind Kind,
    string Code,
    string ResultingState,
    long ResultingVersion)
{
    public bool IsAccepted => Kind == FeatureDecisionKind.Accepted;

    public static EnforceProportionateActionsDecision From(FeatureDecision decision) =>
        new(decision.RequirementId, decision.Kind, decision.Code, decision.ResultingState, decision.ResultingVersion);
}

public sealed class EnforceProportionateActionsPolicy
{
    public EnforceProportionateActionsDecision BoundModeratorAuthorityAndConflicts(
        EnforceProportionateActionsRecord record,
        EnforceProportionateActionsRequest request) =>
        EnforceProportionateActionsDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-SAFE-007", record.ToState(), request.ToInput()));

    public EnforceProportionateActionsDecision ApplyOneAuditableModerationAction(
        EnforceProportionateActionsRecord record,
        EnforceProportionateActionsRequest request) =>
        EnforceProportionateActionsDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-SAFE-008", record.ToState(), request.ToInput()));

    public EnforceProportionateActionsDecision NotifyExpireAndReverseActionsSafely(
        EnforceProportionateActionsRecord record,
        EnforceProportionateActionsRequest request) =>
        EnforceProportionateActionsDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-SAFE-009", record.ToState(), request.ToInput()));

    public EnforceProportionateActionsDecision EnforceTheModerationActionEffectMatrix(
        EnforceProportionateActionsRecord record,
        EnforceProportionateActionsRequest request) =>
        EnforceProportionateActionsDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-SAFE-013", record.ToState(), request.ToInput()));

    public EnforceProportionateActionsDecision RoutePunitiveChangesThroughModerationActions(
        EnforceProportionateActionsRecord record,
        EnforceProportionateActionsRequest request) =>
        EnforceProportionateActionsDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-SAFE-014", record.ToState(), request.ToInput()));

    public EnforceProportionateActionsDecision ResolveEnforcementAndOwnershipContinuityAtomically(
        EnforceProportionateActionsRecord record,
        EnforceProportionateActionsRequest request) =>
        EnforceProportionateActionsDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-SAFE-015", record.ToState(), request.ToInput()));
}

public static class EnforceProportionateActionsDescriptor
{
    public const string Subsystem = "moderation-trust-safety";
    public const string Slug = "enforce-proportionate-actions";
    public const string Title = "Proportionate server-owned enforcement";

    public static IReadOnlyList<FeatureOperationDescriptor> Operations { get; } =
    [
        new("L2-SAFE-007", "BoundModeratorAuthorityAndConflicts"),
        new("L2-SAFE-008", "ApplyOneAuditableModerationAction"),
        new("L2-SAFE-009", "NotifyExpireAndReverseActionsSafely"),
        new("L2-SAFE-013", "EnforceTheModerationActionEffectMatrix"),
        new("L2-SAFE-014", "RoutePunitiveChangesThroughModerationActions"),
        new("L2-SAFE-015", "ResolveEnforcementAndOwnershipContinuityAtomically")
    ];
}
