// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;

namespace CommunityStarter.Domain.GeneratedFeatures;

public sealed record EnforceProviderPrivacyRequest(
    Guid SubjectId,
    string Action,
    long ExpectedVersion,
    Guid? CommunityId,
    IReadOnlyDictionary<string, string> Values)
{
    public FeatureInput ToInput() => new(SubjectId, Action, ExpectedVersion, CommunityId, Values);
}

public sealed record EnforceProviderPrivacyRecord(
    Guid Id,
    Guid? CommunityId,
    string State,
    long Version,
    bool IsAuthorized,
    bool IsAvailable)
{
    public FeatureState ToState() => new(Id, CommunityId, State, Version, IsAuthorized, IsAvailable);
}

public sealed record EnforceProviderPrivacyDecision(
    string RequirementId,
    FeatureDecisionKind Kind,
    string Code,
    string ResultingState,
    long ResultingVersion)
{
    public bool IsAccepted => Kind == FeatureDecisionKind.Accepted;

    public static EnforceProviderPrivacyDecision From(FeatureDecision decision) =>
        new(decision.RequirementId, decision.Kind, decision.Code, decision.ResultingState, decision.ResultingVersion);
}

public sealed class EnforceProviderPrivacyPolicy
{
    public EnforceProviderPrivacyDecision KeepTelemetryFreeOfSensitiveContent(
        EnforceProviderPrivacyRecord record,
        EnforceProviderPrivacyRequest request) =>
        EnforceProviderPrivacyDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-PRIV-013", record.ToState(), request.ToInput()));

    public EnforceProviderPrivacyDecision GovernProductAnalyticsAndConsent(
        EnforceProviderPrivacyRecord record,
        EnforceProviderPrivacyRequest request) =>
        EnforceProviderPrivacyDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-PRIV-014", record.ToState(), request.ToInput()));

    public EnforceProviderPrivacyDecision ControlProcessorAndRegionalDataBoundaries(
        EnforceProviderPrivacyRecord record,
        EnforceProviderPrivacyRequest request) =>
        EnforceProviderPrivacyDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-PRIV-015", record.ToState(), request.ToInput()));
}

public static class EnforceProviderPrivacyDescriptor
{
    public const string Subsystem = "privacy-data-lifecycle";
    public const string Slug = "enforce-provider-privacy";
    public const string Title = "Telemetry and providers respect privacy boundaries";

    public static IReadOnlyList<FeatureOperationDescriptor> Operations { get; } =
    [
        new("L2-PRIV-013", "KeepTelemetryFreeOfSensitiveContent"),
        new("L2-PRIV-014", "GovernProductAnalyticsAndConsent"),
        new("L2-PRIV-015", "ControlProcessorAndRegionalDataBoundaries")
    ];
}
