// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;

namespace CommunityStarter.Domain.GeneratedFeatures;

public sealed record EnforceImplementationDisciplineRequest(
    Guid SubjectId,
    string Action,
    long ExpectedVersion,
    Guid? CommunityId,
    IReadOnlyDictionary<string, string> Values)
{
    public FeatureInput ToInput() => new(SubjectId, Action, ExpectedVersion, CommunityId, Values);
}

public sealed record EnforceImplementationDisciplineRecord(
    Guid Id,
    Guid? CommunityId,
    string State,
    long Version,
    bool IsAuthorized,
    bool IsAvailable)
{
    public FeatureState ToState() => new(Id, CommunityId, State, Version, IsAuthorized, IsAvailable);
}

public sealed record EnforceImplementationDisciplineDecision(
    string RequirementId,
    FeatureDecisionKind Kind,
    string Code,
    string ResultingState,
    long ResultingVersion)
{
    public bool IsAccepted => Kind == FeatureDecisionKind.Accepted;

    public static EnforceImplementationDisciplineDecision From(FeatureDecision decision) =>
        new(decision.RequirementId, decision.Kind, decision.Code, decision.ResultingState, decision.ResultingVersion);
}

public sealed class EnforceImplementationDisciplinePolicy
{
    public EnforceImplementationDisciplineDecision CSharpCodeIsNullableSafeAsynchronousAndConventionEnforced(
        EnforceImplementationDisciplineRecord record,
        EnforceImplementationDisciplineRequest request) =>
        EnforceImplementationDisciplineDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-ARCH-010", record.ToState(), request.ToInput()));

    public EnforceImplementationDisciplineDecision ConfigurationCompositionHealthAndDependenciesAreGoverned(
        EnforceImplementationDisciplineRecord record,
        EnforceImplementationDisciplineRequest request) =>
        EnforceImplementationDisciplineDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-ARCH-011", record.ToState(), request.ToInput()));

    public EnforceImplementationDisciplineDecision UntrustedAndExternalWorkIsBoundedBehindUsefulSeams(
        EnforceImplementationDisciplineRecord record,
        EnforceImplementationDisciplineRequest request) =>
        EnforceImplementationDisciplineDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-ARCH-012", record.ToState(), request.ToInput()));
}

public static class EnforceImplementationDisciplineDescriptor
{
    public const string Subsystem = "platform-architecture";
    public const string Slug = "enforce-implementation-discipline";
    public const string Title = "Enforce production-grade implementation discipline";

    public static IReadOnlyList<FeatureOperationDescriptor> Operations { get; } =
    [
        new("L2-ARCH-010", "CSharpCodeIsNullableSafeAsynchronousAndConventionEnforced"),
        new("L2-ARCH-011", "ConfigurationCompositionHealthAndDependenciesAreGoverned"),
        new("L2-ARCH-012", "UntrustedAndExternalWorkIsBoundedBehindUsefulSeams")
    ];
}
