// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;

namespace CommunityStarter.Domain.GeneratedFeatures;

public sealed record EstablishVisualLanguageRequest(
    Guid SubjectId,
    string Action,
    long ExpectedVersion,
    Guid? CommunityId,
    IReadOnlyDictionary<string, string> Values)
{
    public FeatureInput ToInput() => new(SubjectId, Action, ExpectedVersion, CommunityId, Values);
}

public sealed record EstablishVisualLanguageRecord(
    Guid Id,
    Guid? CommunityId,
    string State,
    long Version,
    bool IsAuthorized,
    bool IsAvailable)
{
    public FeatureState ToState() => new(Id, CommunityId, State, Version, IsAuthorized, IsAvailable);
}

public sealed record EstablishVisualLanguageDecision(
    string RequirementId,
    FeatureDecisionKind Kind,
    string Code,
    string ResultingState,
    long ResultingVersion)
{
    public bool IsAccepted => Kind == FeatureDecisionKind.Accepted;

    public static EstablishVisualLanguageDecision From(FeatureDecision decision) =>
        new(decision.RequirementId, decision.Kind, decision.Code, decision.ResultingState, decision.ResultingVersion);
}

public sealed class EstablishVisualLanguagePolicy
{
    public EstablishVisualLanguageDecision CanonicalFoundationsAndAssetsHaveOneSource(
        EstablishVisualLanguageRecord record,
        EstablishVisualLanguageRequest request) =>
        EstablishVisualLanguageDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-UXDS-001", record.ToState(), request.ToInput()));

    public EstablishVisualLanguageDecision SemanticTokensCoverAllProductRolesAndStates(
        EstablishVisualLanguageRecord record,
        EstablishVisualLanguageRequest request) =>
        EstablishVisualLanguageDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-UXDS-002", record.ToState(), request.ToInput()));

    public EstablishVisualLanguageDecision ComponentsProgressFromFoundationsToProductSignatures(
        EstablishVisualLanguageRecord record,
        EstablishVisualLanguageRequest request) =>
        EstablishVisualLanguageDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-UXDS-003", record.ToState(), request.ToInput()));
}

public static class EstablishVisualLanguageDescriptor
{
    public const string Subsystem = "experience-design-system";
    public const string Slug = "establish-visual-language";
    public const string Title = "Establish one canonical cross-surface visual language";

    public static IReadOnlyList<FeatureOperationDescriptor> Operations { get; } =
    [
        new("L2-UXDS-001", "CanonicalFoundationsAndAssetsHaveOneSource"),
        new("L2-UXDS-002", "SemanticTokensCoverAllProductRolesAndStates"),
        new("L2-UXDS-003", "ComponentsProgressFromFoundationsToProductSignatures")
    ];
}
