// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;

namespace CommunityStarter.Domain.GeneratedFeatures;

public sealed record EvolveRuntimeTopologyRequest(
    Guid SubjectId,
    string Action,
    long ExpectedVersion,
    Guid? CommunityId,
    IReadOnlyDictionary<string, string> Values)
{
    public FeatureInput ToInput() => new(SubjectId, Action, ExpectedVersion, CommunityId, Values);
}

public sealed record EvolveRuntimeTopologyRecord(
    Guid Id,
    Guid? CommunityId,
    string State,
    long Version,
    bool IsAuthorized,
    bool IsAvailable)
{
    public FeatureState ToState() => new(Id, CommunityId, State, Version, IsAuthorized, IsAvailable);
}

public sealed record EvolveRuntimeTopologyDecision(
    string RequirementId,
    FeatureDecisionKind Kind,
    string Code,
    string ResultingState,
    long ResultingVersion)
{
    public bool IsAccepted => Kind == FeatureDecisionKind.Accepted;

    public static EvolveRuntimeTopologyDecision From(FeatureDecision decision) =>
        new(decision.RequirementId, decision.Kind, decision.Code, decision.ResultingState, decision.ResultingVersion);
}

public sealed class EvolveRuntimeTopologyPolicy
{
    public EvolveRuntimeTopologyDecision RealtimeDeliveryFollowsCommittedStateAndReconciles(
        EvolveRuntimeTopologyRecord record,
        EvolveRuntimeTopologyRequest request) =>
        EvolveRuntimeTopologyDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-ARCH-013", record.ToState(), request.ToInput()));

    public EvolveRuntimeTopologyDecision InitialDeploymentIsCohesiveWhileSourceBoundariesRemainSeparable(
        EvolveRuntimeTopologyRecord record,
        EvolveRuntimeTopologyRequest request) =>
        EvolveRuntimeTopologyDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-ARCH-014", record.ToState(), request.ToInput()));
}

public static class EvolveRuntimeTopologyDescriptor
{
    public const string Subsystem = "platform-architecture";
    public const string Slug = "evolve-runtime-topology";
    public const string Title = "Evolve runtime topology without weakening correctness";

    public static IReadOnlyList<FeatureOperationDescriptor> Operations { get; } =
    [
        new("L2-ARCH-013", "RealtimeDeliveryFollowsCommittedStateAndReconciles"),
        new("L2-ARCH-014", "InitialDeploymentIsCohesiveWhileSourceBoundariesRemainSeparable")
    ];
}
