// <auto-generated />
#nullable enable
namespace CommunityStarter.Domain.GeneratedFeatures;

public sealed record FeatureOperationDescriptor(string RequirementId, string Method);

public sealed record FeatureDescriptor(
    string Subsystem,
    string Slug,
    string Title,
    IReadOnlyList<FeatureOperationDescriptor> Operations);

public static class GeneratedFeatureCatalog
{
    public static IReadOnlyList<FeatureDescriptor> Features { get; } =
    [
        new(
            "administration-insights",
            "administer-community-settings",
            "Bounded Community administration",
            AdministerCommunitySettingsDescriptor.Operations),
        new(
            "administration-insights",
            "control-platform-configuration",
            "Controlled platform configuration",
            ControlPlatformConfigurationDescriptor.Operations),
        new(
            "administration-insights",
            "control-platform-support-access",
            "Least-privilege platform and support access",
            ControlPlatformSupportAccessDescriptor.Operations),
        new(
            "administration-insights",
            "deliver-privacy-safe-insights",
            "Privacy-safe actionable insights",
            DeliverPrivacySafeInsightsDescriptor.Operations),
        new(
            "communities-membership",
            "control-membership-lifecycle",
            "Control Membership lifecycle",
            ControlMembershipLifecycleDescriptor.Operations),
        new(
            "communities-membership",
            "delegate-community-authority",
            "Delegate Community authority",
            DelegateCommunityAuthorityDescriptor.Operations),
        new(
            "communities-membership",
            "govern-community-identity",
            "Govern Community identity",
            GovernCommunityIdentityDescriptor.Operations),
        new(
            "communities-membership",
            "govern-space-participation",
            "Govern Spaces and participation rules",
            GovernSpaceParticipationDescriptor.Operations),
        new(
            "communities-membership",
            "preserve-community-integrity",
            "Preserve Community integrity",
            PreserveCommunityIntegrityDescriptor.Operations),
        new(
            "community-events",
            "coordinate-safe-participation",
            "Coordinated and safe participation",
            CoordinateSafeParticipationDescriptor.Operations),
        new(
            "community-events",
            "enforce-event-access",
            "Scoped Event access",
            EnforceEventAccessDescriptor.Operations),
        new(
            "community-events",
            "manage-attendance",
            "Consistent attendance management",
            ManageAttendanceDescriptor.Operations),
        new(
            "community-events",
            "manage-event-lifecycle",
            "Trustworthy Event lifecycle",
            ManageEventLifecycleDescriptor.Operations),
        new(
            "content-media",
            "govern-post-lifecycle",
            "Govern Post lifecycle",
            GovernPostLifecycleDescriptor.Operations),
        new(
            "content-media",
            "handle-attachments-safely",
            "Handle Attachments safely",
            HandleAttachmentsSafelyDescriptor.Operations),
        new(
            "content-media",
            "preserve-content-integrity",
            "Preserve content integrity",
            PreserveContentIntegrityDescriptor.Operations),
        new(
            "content-media",
            "support-comment-conversations",
            "Support Comment conversations",
            SupportCommentConversationsDescriptor.Operations),
        new(
            "delivery-quality",
            "build-layered-risk-evidence",
            "Build layered evidence around product risk",
            BuildLayeredRiskEvidenceDescriptor.Operations),
        new(
            "delivery-quality",
            "enforce-secure-artifact-promotion",
            "Enforce one secure build-and-promotion pipeline",
            EnforceSecureArtifactPromotionDescriptor.Operations),
        new(
            "delivery-quality",
            "keep-delivery-claims-honest",
            "Keep delivery claims and documentation honest",
            KeepDeliveryClaimsHonestDescriptor.Operations),
        new(
            "delivery-quality",
            "keep-tests-deterministic",
            "Keep tests deterministic, readable, and traceable",
            KeepTestsDeterministicDescriptor.Operations),
        new(
            "delivery-quality",
            "operate-telemetry-and-recovery",
            "Operate the starter with actionable telemetry and recovery",
            OperateTelemetryAndRecoveryDescriptor.Operations),
        new(
            "delivery-quality",
            "reproduce-local-change-hygiene",
            "Make local development and change hygiene reproducible",
            ReproduceLocalChangeHygieneDescriptor.Operations),
        new(
            "experience-design-system",
            "establish-visual-language",
            "Establish one canonical cross-surface visual language",
            EstablishVisualLanguageDescriptor.Operations),
        new(
            "experience-design-system",
            "make-interaction-states-resilient",
            "Make every material interaction state resilient",
            MakeInteractionStatesResilientDescriptor.Operations),
        new(
            "experience-design-system",
            "make-language-and-media-inclusive",
            "Make language, locale, and media inclusive",
            MakeLanguageAndMediaInclusiveDescriptor.Operations),
        new(
            "experience-design-system",
            "meet-accessibility-baseline",
            "Meet an inclusive accessibility baseline",
            MeetAccessibilityBaselineDescriptor.Operations),
        new(
            "experience-design-system",
            "provide-angular-component-contracts",
            "Provide disciplined Angular component contracts",
            ProvideAngularComponentContractsDescriptor.Operations),
        new(
            "feeds-search-engagement",
            "deliver-useful-feeds",
            "Deliver useful Feeds",
            DeliverUsefulFeedsDescriptor.Operations),
        new(
            "feeds-search-engagement",
            "keep-discovery-trustworthy",
            "Keep discovery trustworthy",
            KeepDiscoveryTrustworthyDescriptor.Operations),
        new(
            "feeds-search-engagement",
            "record-engagement",
            "Record private and public engagement",
            RecordEngagementDescriptor.Operations),
        new(
            "feeds-search-engagement",
            "search-authorized-content",
            "Search authorized content",
            SearchAuthorizedContentDescriptor.Operations),
        new(
            "identity-access",
            "enforce-server-authorization",
            "Server-owned authorization",
            EnforceServerAuthorizationDescriptor.Operations),
        new(
            "identity-access",
            "manage-safe-account-lifecycle",
            "Safe Account lifecycle",
            ManageSafeAccountLifecycleDescriptor.Operations),
        new(
            "identity-access",
            "observe-access-protection",
            "Observable access protection",
            ObserveAccessProtectionDescriptor.Operations),
        new(
            "identity-access",
            "protect-authenticated-sessions",
            "Defensible authenticated sessions",
            ProtectAuthenticatedSessionsDescriptor.Operations),
        new(
            "marketing-public-web",
            "deliver-truthful-public-surface",
            "Deliver an independent and truthful public surface",
            DeliverTruthfulPublicSurfaceDescriptor.Operations),
        new(
            "marketing-public-web",
            "make-public-discovery-cache-safe",
            "Make public discovery fast, private, and cache-safe",
            MakePublicDiscoveryCacheSafeDescriptor.Operations),
        new(
            "marketing-public-web",
            "publish-unambiguous-routes",
            "Publish marketing and application routes without ambiguity",
            PublishUnambiguousRoutesDescriptor.Operations),
        new(
            "marketing-public-web",
            "verify-public-deployment",
            "Evolve and verify public deployment safely",
            VerifyPublicDeploymentDescriptor.Operations),
        new(
            "messaging-realtime",
            "authorize-conversation-access",
            "Consent-based Conversation access",
            AuthorizeConversationAccessDescriptor.Operations),
        new(
            "messaging-realtime",
            "deliver-durable-messages",
            "Durable and safe Messages",
            DeliverDurableMessagesDescriptor.Operations),
        new(
            "messaging-realtime",
            "reconcile-realtime-experience",
            "Reconciled realtime experience",
            ReconcileRealtimeExperienceDescriptor.Operations),
        new(
            "moderation-trust-safety",
            "enforce-proportionate-actions",
            "Proportionate server-owned enforcement",
            EnforceProportionateActionsDescriptor.Operations),
        new(
            "moderation-trust-safety",
            "manage-moderation-cases",
            "Durable Moderation Cases",
            ManageModerationCasesDescriptor.Operations),
        new(
            "moderation-trust-safety",
            "report-policy-harm",
            "Safe policy reporting",
            ReportPolicyHarmDescriptor.Operations),
        new(
            "moderation-trust-safety",
            "review-safety-decisions",
            "Reviewable and operable safety decisions",
            ReviewSafetyDecisionsDescriptor.Operations),
        new(
            "notifications-delivery",
            "control-recipient-attention",
            "Recipient-controlled attention",
            ControlRecipientAttentionDescriptor.Operations),
        new(
            "notifications-delivery",
            "deliver-external-notifications",
            "Durable external Delivery",
            DeliverExternalNotificationsDescriptor.Operations),
        new(
            "notifications-delivery",
            "deliver-private-notifications",
            "Relevant and private Notifications",
            DeliverPrivateNotificationsDescriptor.Operations),
        new(
            "notifications-delivery",
            "operate-notification-channels",
            "Safe templates and operable channels",
            OperateNotificationChannelsDescriptor.Operations),
        new(
            "onboarding-discovery",
            "complete-resumable-onboarding",
            "Complete resumable onboarding",
            CompleteResumableOnboardingDescriptor.Operations),
        new(
            "onboarding-discovery",
            "keep-onboarding-safe",
            "Keep onboarding safe and inclusive",
            KeepOnboardingSafeDescriptor.Operations),
        new(
            "onboarding-discovery",
            "offer-relevant-discovery",
            "Offer relevant discovery",
            OfferRelevantDiscoveryDescriptor.Operations),
        new(
            "onboarding-discovery",
            "reach-first-community-value",
            "Reach first Community value",
            ReachFirstCommunityValueDescriptor.Operations),
        new(
            "operations-reliability",
            "control-production-change",
            "Production change remains controlled and supportable",
            ControlProductionChangeDescriptor.Operations),
        new(
            "operations-reliability",
            "measure-reliability-capacity",
            "Reliability and capacity are measurable",
            MeasureReliabilityCapacityDescriptor.Operations),
        new(
            "operations-reliability",
            "observe-system-product-health",
            "Operators can understand system and product health",
            ObserveSystemProductHealthDescriptor.Operations),
        new(
            "operations-reliability",
            "recover-data-services",
            "Data and service can be recovered",
            RecoverDataServicesDescriptor.Operations),
        new(
            "operations-reliability",
            "respond-to-incidents",
            "Incidents have owned detection and response",
            RespondToIncidentsDescriptor.Operations),
        new(
            "platform-architecture",
            "enforce-implementation-discipline",
            "Enforce production-grade implementation discipline",
            EnforceImplementationDisciplineDescriptor.Operations),
        new(
            "platform-architecture",
            "evolve-runtime-topology",
            "Evolve runtime topology without weakening correctness",
            EvolveRuntimeTopologyDescriptor.Operations),
        new(
            "platform-architecture",
            "keep-behavior-server-authoritative",
            "Keep community behavior server-authoritative",
            KeepBehaviorServerAuthoritativeDescriptor.Operations),
        new(
            "platform-architecture",
            "preserve-full-stack-boundaries",
            "Preserve explicit full-stack boundaries",
            PreserveFullStackBoundariesDescriptor.Operations),
        new(
            "platform-architecture",
            "protect-data-persistence-integrity",
            "Protect Community data and persistence integrity",
            ProtectDataPersistenceIntegrityDescriptor.Operations),
        new(
            "platform-architecture",
            "trace-architecture-to-product-truth",
            "Make architecture traceable to product truth",
            TraceArchitectureToProductTruthDescriptor.Operations),
        new(
            "privacy-data-lifecycle",
            "control-personal-data",
            "People can access and control their data",
            ControlPersonalDataDescriptor.Operations),
        new(
            "privacy-data-lifecycle",
            "enforce-provider-privacy",
            "Telemetry and providers respect privacy boundaries",
            EnforceProviderPrivacyDescriptor.Operations),
        new(
            "privacy-data-lifecycle",
            "govern-every-data-copy",
            "Lifecycle rules cover every data copy",
            GovernEveryDataCopyDescriptor.Operations),
        new(
            "privacy-data-lifecycle",
            "minimize-personal-data-use",
            "Personal data use is explicit and minimized",
            MinimizePersonalDataUseDescriptor.Operations),
        new(
            "profiles-relationships",
            "enforce-relationship-safety",
            "Enforce relationship safety",
            EnforceRelationshipSafetyDescriptor.Operations),
        new(
            "profiles-relationships",
            "present-trustworthy-profile",
            "Present a trustworthy Profile",
            PresentTrustworthyProfileDescriptor.Operations),
        new(
            "profiles-relationships",
            "respect-community-context",
            "Respect Community context",
            RespectCommunityContextDescriptor.Operations),
        new(
            "security",
            "constrain-untrusted-boundaries",
            "Constrain every untrusted boundary",
            ConstrainUntrustedBoundariesDescriptor.Operations),
        new(
            "security",
            "harden-runtime-supply-chain",
            "Harden browsers, dependencies, and deployment credentials",
            HardenRuntimeSupplyChainDescriptor.Operations),
        new(
            "security",
            "model-threats-and-identity",
            "Model threats and enforce identity in Community context",
            ModelThreatsAndIdentityDescriptor.Operations),
        new(
            "security",
            "operate-security-readiness",
            "Operate with explicit privacy and security readiness",
            OperateSecurityReadinessDescriptor.Operations),
        new(
            "security",
            "protect-secrets-diagnostics-data",
            "Keep secrets, diagnostics, and personal data out of unsafe channels",
            ProtectSecretsDiagnosticsDataDescriptor.Operations),
        new(
            "starter-experience",
            "isolate-development-data",
            "Development data is useful and cannot leak into production",
            IsolateDevelopmentDataDescriptor.Operations),
        new(
            "starter-experience",
            "maintain-repository-knowledge",
            "Repository knowledge stays current and actionable",
            MaintainRepositoryKnowledgeDescriptor.Operations),
        new(
            "starter-experience",
            "reproduce-clean-checkout",
            "A clean checkout is reproducible",
            ReproduceCleanCheckoutDescriptor.Operations),
        new(
            "starter-experience",
            "specialize-starter-safely",
            "Teams can specialize the starter safely",
            SpecializeStarterSafelyDescriptor.Operations)
    ];
}
