// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;

namespace CommunityStarter.Domain.GeneratedFeatures;

public sealed record GovernPostLifecycleRequest(
    Guid SubjectId,
    string Action,
    long ExpectedVersion,
    Guid? CommunityId,
    IReadOnlyDictionary<string, string> Values)
{
    public FeatureInput ToInput() => new(SubjectId, Action, ExpectedVersion, CommunityId, Values);
}

public sealed record GovernPostLifecycleRecord(
    Guid Id,
    Guid? CommunityId,
    string State,
    long Version,
    bool IsAuthorized,
    bool IsAvailable)
{
    public FeatureState ToState() => new(Id, CommunityId, State, Version, IsAuthorized, IsAvailable);
}

public sealed record GovernPostLifecycleDecision(
    string RequirementId,
    FeatureDecisionKind Kind,
    string Code,
    string ResultingState,
    long ResultingVersion)
{
    public bool IsAccepted => Kind == FeatureDecisionKind.Accepted;

    public static GovernPostLifecycleDecision From(FeatureDecision decision) =>
        new(decision.RequirementId, decision.Kind, decision.Code, decision.ResultingState, decision.ResultingVersion);
}

public sealed class GovernPostLifecyclePolicy
{
    public GovernPostLifecycleDecision DraftAndPublishAPost(
        GovernPostLifecycleRecord record,
        GovernPostLifecycleRequest request) =>
        GovernPostLifecycleDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-CONT-001", record.ToState(), request.ToInput()));

    public GovernPostLifecycleDecision EditAPostSafely(
        GovernPostLifecycleRecord record,
        GovernPostLifecycleRequest request) =>
        GovernPostLifecycleDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-CONT-002", record.ToState(), request.ToInput()));

    public GovernPostLifecycleDecision EnforcePostVisibility(
        GovernPostLifecycleRecord record,
        GovernPostLifecycleRequest request) =>
        GovernPostLifecycleDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-CONT-003", record.ToState(), request.ToInput()));

    public GovernPostLifecycleDecision RemoveAndRestoreAPost(
        GovernPostLifecycleRecord record,
        GovernPostLifecycleRequest request) =>
        GovernPostLifecycleDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-CONT-004", record.ToState(), request.ToInput()));
}

public static class GovernPostLifecycleDescriptor
{
    public const string Subsystem = "content-media";
    public const string Slug = "govern-post-lifecycle";
    public const string Title = "Govern Post lifecycle";

    public static IReadOnlyList<FeatureOperationDescriptor> Operations { get; } =
    [
        new("L2-CONT-001", "DraftAndPublishAPost"),
        new("L2-CONT-002", "EditAPostSafely"),
        new("L2-CONT-003", "EnforcePostVisibility"),
        new("L2-CONT-004", "RemoveAndRestoreAPost")
    ];
}
