// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;

namespace CommunityStarter.Domain.GeneratedFeatures;

public sealed record GovernEveryDataCopyRequest(
    Guid SubjectId,
    string Action,
    long ExpectedVersion,
    Guid? CommunityId,
    IReadOnlyDictionary<string, string> Values)
{
    public FeatureInput ToInput() => new(SubjectId, Action, ExpectedVersion, CommunityId, Values);
}

public sealed record GovernEveryDataCopyRecord(
    Guid Id,
    Guid? CommunityId,
    string State,
    long Version,
    bool IsAuthorized,
    bool IsAvailable)
{
    public FeatureState ToState() => new(Id, CommunityId, State, Version, IsAuthorized, IsAvailable);
}

public sealed record GovernEveryDataCopyDecision(
    string RequirementId,
    FeatureDecisionKind Kind,
    string Code,
    string ResultingState,
    long ResultingVersion)
{
    public bool IsAccepted => Kind == FeatureDecisionKind.Accepted;

    public static GovernEveryDataCopyDecision From(FeatureDecision decision) =>
        new(decision.RequirementId, decision.Kind, decision.Code, decision.ResultingState, decision.ResultingVersion);
}

public sealed class GovernEveryDataCopyPolicy
{
    public GovernEveryDataCopyDecision EnforceRetentionSchedules(
        GovernEveryDataCopyRecord record,
        GovernEveryDataCopyRequest request) =>
        GovernEveryDataCopyDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-PRIV-009", record.ToState(), request.ToInput()));

    public GovernEveryDataCopyDecision PropagateDeletionToDerivedSystems(
        GovernEveryDataCopyRecord record,
        GovernEveryDataCopyRequest request) =>
        GovernEveryDataCopyDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-PRIV-010", record.ToState(), request.ToInput()));

    public GovernEveryDataCopyDecision PreserveSharedContentIntegrityWithoutRetainingIdentityUnnecessarily(
        GovernEveryDataCopyRecord record,
        GovernEveryDataCopyRequest request) =>
        GovernEveryDataCopyDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-PRIV-011", record.ToState(), request.ToInput()));

    public GovernEveryDataCopyDecision RestrictLegalHoldsAndSafetyEvidence(
        GovernEveryDataCopyRecord record,
        GovernEveryDataCopyRequest request) =>
        GovernEveryDataCopyDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-PRIV-012", record.ToState(), request.ToInput()));
}

public static class GovernEveryDataCopyDescriptor
{
    public const string Subsystem = "privacy-data-lifecycle";
    public const string Slug = "govern-every-data-copy";
    public const string Title = "Lifecycle rules cover every data copy";

    public static IReadOnlyList<FeatureOperationDescriptor> Operations { get; } =
    [
        new("L2-PRIV-009", "EnforceRetentionSchedules"),
        new("L2-PRIV-010", "PropagateDeletionToDerivedSystems"),
        new("L2-PRIV-011", "PreserveSharedContentIntegrityWithoutRetainingIdentityUnnecessarily"),
        new("L2-PRIV-012", "RestrictLegalHoldsAndSafetyEvidence")
    ];
}
