// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;

namespace CommunityStarter.Domain.GeneratedFeatures;

public sealed record GovernCommunityIdentityRequest(
    Guid SubjectId,
    string Action,
    long ExpectedVersion,
    Guid? CommunityId,
    IReadOnlyDictionary<string, string> Values)
{
    public FeatureInput ToInput() => new(SubjectId, Action, ExpectedVersion, CommunityId, Values);
}

public sealed record GovernCommunityIdentityRecord(
    Guid Id,
    Guid? CommunityId,
    string State,
    long Version,
    bool IsAuthorized,
    bool IsAvailable)
{
    public FeatureState ToState() => new(Id, CommunityId, State, Version, IsAuthorized, IsAvailable);
}

public sealed record GovernCommunityIdentityDecision(
    string RequirementId,
    FeatureDecisionKind Kind,
    string Code,
    string ResultingState,
    long ResultingVersion)
{
    public bool IsAccepted => Kind == FeatureDecisionKind.Accepted;

    public static GovernCommunityIdentityDecision From(FeatureDecision decision) =>
        new(decision.RequirementId, decision.Kind, decision.Code, decision.ResultingState, decision.ResultingVersion);
}

public sealed class GovernCommunityIdentityPolicy
{
    public GovernCommunityIdentityDecision CreateACommunity(
        GovernCommunityIdentityRecord record,
        GovernCommunityIdentityRequest request) =>
        GovernCommunityIdentityDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-COMM-001", record.ToState(), request.ToInput()));

    public GovernCommunityIdentityDecision ConfigureCommunityIdentity(
        GovernCommunityIdentityRecord record,
        GovernCommunityIdentityRequest request) =>
        GovernCommunityIdentityDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-COMM-002", record.ToState(), request.ToInput()));
}

public static class GovernCommunityIdentityDescriptor
{
    public const string Subsystem = "communities-membership";
    public const string Slug = "govern-community-identity";
    public const string Title = "Govern Community identity";

    public static IReadOnlyList<FeatureOperationDescriptor> Operations { get; } =
    [
        new("L2-COMM-001", "CreateACommunity"),
        new("L2-COMM-002", "ConfigureCommunityIdentity")
    ];
}
