// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;

namespace CommunityStarter.Domain.GeneratedFeatures;

public sealed record GovernSpaceParticipationRequest(
    Guid SubjectId,
    string Action,
    long ExpectedVersion,
    Guid? CommunityId,
    IReadOnlyDictionary<string, string> Values)
{
    public FeatureInput ToInput() => new(SubjectId, Action, ExpectedVersion, CommunityId, Values);
}

public sealed record GovernSpaceParticipationRecord(
    Guid Id,
    Guid? CommunityId,
    string State,
    long Version,
    bool IsAuthorized,
    bool IsAvailable)
{
    public FeatureState ToState() => new(Id, CommunityId, State, Version, IsAuthorized, IsAvailable);
}

public sealed record GovernSpaceParticipationDecision(
    string RequirementId,
    FeatureDecisionKind Kind,
    string Code,
    string ResultingState,
    long ResultingVersion)
{
    public bool IsAccepted => Kind == FeatureDecisionKind.Accepted;

    public static GovernSpaceParticipationDecision From(FeatureDecision decision) =>
        new(decision.RequirementId, decision.Kind, decision.Code, decision.ResultingState, decision.ResultingVersion);
}

public sealed class GovernSpaceParticipationPolicy
{
    public GovernSpaceParticipationDecision GovernSpaceLifecycle(
        GovernSpaceParticipationRecord record,
        GovernSpaceParticipationRequest request) =>
        GovernSpaceParticipationDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-COMM-013", record.ToState(), request.ToInput()));

    public GovernSpaceParticipationDecision EnforceSpaceAccess(
        GovernSpaceParticipationRecord record,
        GovernSpaceParticipationRequest request) =>
        GovernSpaceParticipationDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-COMM-014", record.ToState(), request.ToInput()));

    public GovernSpaceParticipationDecision DelegateSpaceAuthority(
        GovernSpaceParticipationRecord record,
        GovernSpaceParticipationRequest request) =>
        GovernSpaceParticipationDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-COMM-015", record.ToState(), request.ToInput()));

    public GovernSpaceParticipationDecision AcceptVersionedRules(
        GovernSpaceParticipationRecord record,
        GovernSpaceParticipationRequest request) =>
        GovernSpaceParticipationDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-COMM-016", record.ToState(), request.ToInput()));
}

public static class GovernSpaceParticipationDescriptor
{
    public const string Subsystem = "communities-membership";
    public const string Slug = "govern-space-participation";
    public const string Title = "Govern Spaces and participation rules";

    public static IReadOnlyList<FeatureOperationDescriptor> Operations { get; } =
    [
        new("L2-COMM-013", "GovernSpaceLifecycle"),
        new("L2-COMM-014", "EnforceSpaceAccess"),
        new("L2-COMM-015", "DelegateSpaceAuthority"),
        new("L2-COMM-016", "AcceptVersionedRules")
    ];
}
