// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;

namespace CommunityStarter.Domain.GeneratedFeatures;

public sealed record HandleAttachmentsSafelyRequest(
    Guid SubjectId,
    string Action,
    long ExpectedVersion,
    Guid? CommunityId,
    IReadOnlyDictionary<string, string> Values)
{
    public FeatureInput ToInput() => new(SubjectId, Action, ExpectedVersion, CommunityId, Values);
}

public sealed record HandleAttachmentsSafelyRecord(
    Guid Id,
    Guid? CommunityId,
    string State,
    long Version,
    bool IsAuthorized,
    bool IsAvailable)
{
    public FeatureState ToState() => new(Id, CommunityId, State, Version, IsAuthorized, IsAvailable);
}

public sealed record HandleAttachmentsSafelyDecision(
    string RequirementId,
    FeatureDecisionKind Kind,
    string Code,
    string ResultingState,
    long ResultingVersion)
{
    public bool IsAccepted => Kind == FeatureDecisionKind.Accepted;

    public static HandleAttachmentsSafelyDecision From(FeatureDecision decision) =>
        new(decision.RequirementId, decision.Kind, decision.Code, decision.ResultingState, decision.ResultingVersion);
}

public sealed class HandleAttachmentsSafelyPolicy
{
    public HandleAttachmentsSafelyDecision StageAnAttachment(
        HandleAttachmentsSafelyRecord record,
        HandleAttachmentsSafelyRequest request) =>
        HandleAttachmentsSafelyDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-CONT-005", record.ToState(), request.ToInput()));

    public HandleAttachmentsSafelyDecision ProcessAnAttachment(
        HandleAttachmentsSafelyRecord record,
        HandleAttachmentsSafelyRequest request) =>
        HandleAttachmentsSafelyDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-CONT-006", record.ToState(), request.ToInput()));

    public HandleAttachmentsSafelyDecision ProtectAttachmentAccess(
        HandleAttachmentsSafelyRecord record,
        HandleAttachmentsSafelyRequest request) =>
        HandleAttachmentsSafelyDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-CONT-007", record.ToState(), request.ToInput()));
}

public static class HandleAttachmentsSafelyDescriptor
{
    public const string Subsystem = "content-media";
    public const string Slug = "handle-attachments-safely";
    public const string Title = "Handle Attachments safely";

    public static IReadOnlyList<FeatureOperationDescriptor> Operations { get; } =
    [
        new("L2-CONT-005", "StageAnAttachment"),
        new("L2-CONT-006", "ProcessAnAttachment"),
        new("L2-CONT-007", "ProtectAttachmentAccess")
    ];
}
