// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;

namespace CommunityStarter.Domain.GeneratedFeatures;

public sealed record HardenRuntimeSupplyChainRequest(
    Guid SubjectId,
    string Action,
    long ExpectedVersion,
    Guid? CommunityId,
    IReadOnlyDictionary<string, string> Values)
{
    public FeatureInput ToInput() => new(SubjectId, Action, ExpectedVersion, CommunityId, Values);
}

public sealed record HardenRuntimeSupplyChainRecord(
    Guid Id,
    Guid? CommunityId,
    string State,
    long Version,
    bool IsAuthorized,
    bool IsAvailable)
{
    public FeatureState ToState() => new(Id, CommunityId, State, Version, IsAuthorized, IsAvailable);
}

public sealed record HardenRuntimeSupplyChainDecision(
    string RequirementId,
    FeatureDecisionKind Kind,
    string Code,
    string ResultingState,
    long ResultingVersion)
{
    public bool IsAccepted => Kind == FeatureDecisionKind.Accepted;

    public static HardenRuntimeSupplyChainDecision From(FeatureDecision decision) =>
        new(decision.RequirementId, decision.Kind, decision.Code, decision.ResultingState, decision.ResultingVersion);
}

public sealed class HardenRuntimeSupplyChainPolicy
{
    public HardenRuntimeSupplyChainDecision BrowserAndTransportHeadersMatchTheDeploymentThreatModel(
        HardenRuntimeSupplyChainRecord record,
        HardenRuntimeSupplyChainRequest request) =>
        HardenRuntimeSupplyChainDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-SECU-010", record.ToState(), request.ToInput()));

    public HardenRuntimeSupplyChainDecision DeploymentUsesProtectedEnvironmentsAndShortLivedCredentials(
        HardenRuntimeSupplyChainRecord record,
        HardenRuntimeSupplyChainRequest request) =>
        HardenRuntimeSupplyChainDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-SECU-011", record.ToState(), request.ToInput()));

    public HardenRuntimeSupplyChainDecision SupplyChainChangesAreReviewedAndContinuouslyScanned(
        HardenRuntimeSupplyChainRecord record,
        HardenRuntimeSupplyChainRequest request) =>
        HardenRuntimeSupplyChainDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-SECU-012", record.ToState(), request.ToInput()));
}

public static class HardenRuntimeSupplyChainDescriptor
{
    public const string Subsystem = "security";
    public const string Slug = "harden-runtime-supply-chain";
    public const string Title = "Harden browsers, dependencies, and deployment credentials";

    public static IReadOnlyList<FeatureOperationDescriptor> Operations { get; } =
    [
        new("L2-SECU-010", "BrowserAndTransportHeadersMatchTheDeploymentThreatModel"),
        new("L2-SECU-011", "DeploymentUsesProtectedEnvironmentsAndShortLivedCredentials"),
        new("L2-SECU-012", "SupplyChainChangesAreReviewedAndContinuouslyScanned")
    ];
}
