// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;

namespace CommunityStarter.Domain.GeneratedFeatures;

public sealed record IsolateDevelopmentDataRequest(
    Guid SubjectId,
    string Action,
    long ExpectedVersion,
    Guid? CommunityId,
    IReadOnlyDictionary<string, string> Values)
{
    public FeatureInput ToInput() => new(SubjectId, Action, ExpectedVersion, CommunityId, Values);
}

public sealed record IsolateDevelopmentDataRecord(
    Guid Id,
    Guid? CommunityId,
    string State,
    long Version,
    bool IsAuthorized,
    bool IsAvailable)
{
    public FeatureState ToState() => new(Id, CommunityId, State, Version, IsAuthorized, IsAvailable);
}

public sealed record IsolateDevelopmentDataDecision(
    string RequirementId,
    FeatureDecisionKind Kind,
    string Code,
    string ResultingState,
    long ResultingVersion)
{
    public bool IsAccepted => Kind == FeatureDecisionKind.Accepted;

    public static IsolateDevelopmentDataDecision From(FeatureDecision decision) =>
        new(decision.RequirementId, decision.Kind, decision.Code, decision.ResultingState, decision.ResultingVersion);
}

public sealed class IsolateDevelopmentDataPolicy
{
    public IsolateDevelopmentDataDecision SeedDeterministicFictionalScenarios(
        IsolateDevelopmentDataRecord record,
        IsolateDevelopmentDataRequest request) =>
        IsolateDevelopmentDataDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-STRT-005", record.ToState(), request.ToInput()));

    public IsolateDevelopmentDataDecision IsolateDevelopmentOnlyIdentityAndProviders(
        IsolateDevelopmentDataRecord record,
        IsolateDevelopmentDataRequest request) =>
        IsolateDevelopmentDataDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-STRT-006", record.ToState(), request.ToInput()));
}

public static class IsolateDevelopmentDataDescriptor
{
    public const string Subsystem = "starter-experience";
    public const string Slug = "isolate-development-data";
    public const string Title = "Development data is useful and cannot leak into production";

    public static IReadOnlyList<FeatureOperationDescriptor> Operations { get; } =
    [
        new("L2-STRT-005", "SeedDeterministicFictionalScenarios"),
        new("L2-STRT-006", "IsolateDevelopmentOnlyIdentityAndProviders")
    ];
}
