// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;

namespace CommunityStarter.Domain.GeneratedFeatures;

public sealed record KeepDeliveryClaimsHonestRequest(
    Guid SubjectId,
    string Action,
    long ExpectedVersion,
    Guid? CommunityId,
    IReadOnlyDictionary<string, string> Values)
{
    public FeatureInput ToInput() => new(SubjectId, Action, ExpectedVersion, CommunityId, Values);
}

public sealed record KeepDeliveryClaimsHonestRecord(
    Guid Id,
    Guid? CommunityId,
    string State,
    long Version,
    bool IsAuthorized,
    bool IsAvailable)
{
    public FeatureState ToState() => new(Id, CommunityId, State, Version, IsAuthorized, IsAvailable);
}

public sealed record KeepDeliveryClaimsHonestDecision(
    string RequirementId,
    FeatureDecisionKind Kind,
    string Code,
    string ResultingState,
    long ResultingVersion)
{
    public bool IsAccepted => Kind == FeatureDecisionKind.Accepted;

    public static KeepDeliveryClaimsHonestDecision From(FeatureDecision decision) =>
        new(decision.RequirementId, decision.Kind, decision.Code, decision.ResultingState, decision.ResultingVersion);
}

public sealed class KeepDeliveryClaimsHonestPolicy
{
    public KeepDeliveryClaimsHonestDecision PullRequestsAndHandoffsExposeImpactAndVerification(
        KeepDeliveryClaimsHonestRecord record,
        KeepDeliveryClaimsHonestRequest request) =>
        KeepDeliveryClaimsHonestDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-QUAL-018", record.ToState(), request.ToInput()));

    public KeepDeliveryClaimsHonestDecision DocumentationAndDecisionEvidenceStayCurrentWithBehavior(
        KeepDeliveryClaimsHonestRecord record,
        KeepDeliveryClaimsHonestRequest request) =>
        KeepDeliveryClaimsHonestDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-QUAL-019", record.ToState(), request.ToInput()));

    public KeepDeliveryClaimsHonestDecision DefinitionOfDoneAndProductionReadinessClaimsMatchEvidence(
        KeepDeliveryClaimsHonestRecord record,
        KeepDeliveryClaimsHonestRequest request) =>
        KeepDeliveryClaimsHonestDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-QUAL-020", record.ToState(), request.ToInput()));
}

public static class KeepDeliveryClaimsHonestDescriptor
{
    public const string Subsystem = "delivery-quality";
    public const string Slug = "keep-delivery-claims-honest";
    public const string Title = "Keep delivery claims and documentation honest";

    public static IReadOnlyList<FeatureOperationDescriptor> Operations { get; } =
    [
        new("L2-QUAL-018", "PullRequestsAndHandoffsExposeImpactAndVerification"),
        new("L2-QUAL-019", "DocumentationAndDecisionEvidenceStayCurrentWithBehavior"),
        new("L2-QUAL-020", "DefinitionOfDoneAndProductionReadinessClaimsMatchEvidence")
    ];
}
