// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;

namespace CommunityStarter.Domain.GeneratedFeatures;

public sealed record KeepTestsDeterministicRequest(
    Guid SubjectId,
    string Action,
    long ExpectedVersion,
    Guid? CommunityId,
    IReadOnlyDictionary<string, string> Values)
{
    public FeatureInput ToInput() => new(SubjectId, Action, ExpectedVersion, CommunityId, Values);
}

public sealed record KeepTestsDeterministicRecord(
    Guid Id,
    Guid? CommunityId,
    string State,
    long Version,
    bool IsAuthorized,
    bool IsAvailable)
{
    public FeatureState ToState() => new(Id, CommunityId, State, Version, IsAuthorized, IsAvailable);
}

public sealed record KeepTestsDeterministicDecision(
    string RequirementId,
    FeatureDecisionKind Kind,
    string Code,
    string ResultingState,
    long ResultingVersion)
{
    public bool IsAccepted => Kind == FeatureDecisionKind.Accepted;

    public static KeepTestsDeterministicDecision From(FeatureDecision decision) =>
        new(decision.RequirementId, decision.Kind, decision.Code, decision.ResultingState, decision.ResultingVersion);
}

public sealed class KeepTestsDeterministicPolicy
{
    public KeepTestsDeterministicDecision TestsAreBehavioralIsolatedAndDeterministic(
        KeepTestsDeterministicRecord record,
        KeepTestsDeterministicRequest request) =>
        KeepTestsDeterministicDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-QUAL-005", record.ToState(), request.ToInput()));

    public KeepTestsDeterministicDecision BrowserJourneysUseStablePageObjectsAndFaithfulDependencies(
        KeepTestsDeterministicRecord record,
        KeepTestsDeterministicRequest request) =>
        KeepTestsDeterministicDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-QUAL-006", record.ToState(), request.ToInput()));

    public KeepTestsDeterministicDecision RequirementStatusIsBackedByAppropriatelyScopedEvidence(
        KeepTestsDeterministicRecord record,
        KeepTestsDeterministicRequest request) =>
        KeepTestsDeterministicDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-QUAL-007", record.ToState(), request.ToInput()));
}

public static class KeepTestsDeterministicDescriptor
{
    public const string Subsystem = "delivery-quality";
    public const string Slug = "keep-tests-deterministic";
    public const string Title = "Keep tests deterministic, readable, and traceable";

    public static IReadOnlyList<FeatureOperationDescriptor> Operations { get; } =
    [
        new("L2-QUAL-005", "TestsAreBehavioralIsolatedAndDeterministic"),
        new("L2-QUAL-006", "BrowserJourneysUseStablePageObjectsAndFaithfulDependencies"),
        new("L2-QUAL-007", "RequirementStatusIsBackedByAppropriatelyScopedEvidence")
    ];
}
