// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;

namespace CommunityStarter.Domain.GeneratedFeatures;

public sealed record KeepDiscoveryTrustworthyRequest(
    Guid SubjectId,
    string Action,
    long ExpectedVersion,
    Guid? CommunityId,
    IReadOnlyDictionary<string, string> Values)
{
    public FeatureInput ToInput() => new(SubjectId, Action, ExpectedVersion, CommunityId, Values);
}

public sealed record KeepDiscoveryTrustworthyRecord(
    Guid Id,
    Guid? CommunityId,
    string State,
    long Version,
    bool IsAuthorized,
    bool IsAvailable)
{
    public FeatureState ToState() => new(Id, CommunityId, State, Version, IsAuthorized, IsAvailable);
}

public sealed record KeepDiscoveryTrustworthyDecision(
    string RequirementId,
    FeatureDecisionKind Kind,
    string Code,
    string ResultingState,
    long ResultingVersion)
{
    public bool IsAccepted => Kind == FeatureDecisionKind.Accepted;

    public static KeepDiscoveryTrustworthyDecision From(FeatureDecision decision) =>
        new(decision.RequirementId, decision.Kind, decision.Code, decision.ResultingState, decision.ResultingVersion);
}

public sealed class KeepDiscoveryTrustworthyPolicy
{
    public KeepDiscoveryTrustworthyDecision ReconcileCommittedChanges(
        KeepDiscoveryTrustworthyRecord record,
        KeepDiscoveryTrustworthyRequest request) =>
        KeepDiscoveryTrustworthyDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-DISC-011", record.ToState(), request.ToInput()));

    public KeepDiscoveryTrustworthyDecision BoundAbuseAndDegradation(
        KeepDiscoveryTrustworthyRecord record,
        KeepDiscoveryTrustworthyRequest request) =>
        KeepDiscoveryTrustworthyDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-DISC-012", record.ToState(), request.ToInput()));
}

public static class KeepDiscoveryTrustworthyDescriptor
{
    public const string Subsystem = "feeds-search-engagement";
    public const string Slug = "keep-discovery-trustworthy";
    public const string Title = "Keep discovery trustworthy";

    public static IReadOnlyList<FeatureOperationDescriptor> Operations { get; } =
    [
        new("L2-DISC-011", "ReconcileCommittedChanges"),
        new("L2-DISC-012", "BoundAbuseAndDegradation")
    ];
}
