// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;

namespace CommunityStarter.Domain.GeneratedFeatures;

public sealed record KeepBehaviorServerAuthoritativeRequest(
    Guid SubjectId,
    string Action,
    long ExpectedVersion,
    Guid? CommunityId,
    IReadOnlyDictionary<string, string> Values)
{
    public FeatureInput ToInput() => new(SubjectId, Action, ExpectedVersion, CommunityId, Values);
}

public sealed record KeepBehaviorServerAuthoritativeRecord(
    Guid Id,
    Guid? CommunityId,
    string State,
    long Version,
    bool IsAuthorized,
    bool IsAvailable)
{
    public FeatureState ToState() => new(Id, CommunityId, State, Version, IsAuthorized, IsAvailable);
}

public sealed record KeepBehaviorServerAuthoritativeDecision(
    string RequirementId,
    FeatureDecisionKind Kind,
    string Code,
    string ResultingState,
    long ResultingVersion)
{
    public bool IsAccepted => Kind == FeatureDecisionKind.Accepted;

    public static KeepBehaviorServerAuthoritativeDecision From(FeatureDecision decision) =>
        new(decision.RequirementId, decision.Kind, decision.Code, decision.ResultingState, decision.ResultingVersion);
}

public sealed class KeepBehaviorServerAuthoritativePolicy
{
    public KeepBehaviorServerAuthoritativeDecision ApplicationCodeIsOrganizedByCapabilityAndUseCase(
        KeepBehaviorServerAuthoritativeRecord record,
        KeepBehaviorServerAuthoritativeRequest request) =>
        KeepBehaviorServerAuthoritativeDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-ARCH-004", record.ToState(), request.ToInput()));

    public KeepBehaviorServerAuthoritativeDecision StateChangesFollowOneAuthoritativeSequence(
        KeepBehaviorServerAuthoritativeRecord record,
        KeepBehaviorServerAuthoritativeRequest request) =>
        KeepBehaviorServerAuthoritativeDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-ARCH-005", record.ToState(), request.ToInput()));

    public KeepBehaviorServerAuthoritativeDecision HTTPContractsAndFailuresAreStableAndExplicit(
        KeepBehaviorServerAuthoritativeRecord record,
        KeepBehaviorServerAuthoritativeRequest request) =>
        KeepBehaviorServerAuthoritativeDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-ARCH-006", record.ToState(), request.ToInput()));
}

public static class KeepBehaviorServerAuthoritativeDescriptor
{
    public const string Subsystem = "platform-architecture";
    public const string Slug = "keep-behavior-server-authoritative";
    public const string Title = "Keep community behavior server-authoritative";

    public static IReadOnlyList<FeatureOperationDescriptor> Operations { get; } =
    [
        new("L2-ARCH-004", "ApplicationCodeIsOrganizedByCapabilityAndUseCase"),
        new("L2-ARCH-005", "StateChangesFollowOneAuthoritativeSequence"),
        new("L2-ARCH-006", "HTTPContractsAndFailuresAreStableAndExplicit")
    ];
}
