// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;

namespace CommunityStarter.Domain.GeneratedFeatures;

public sealed record MaintainRepositoryKnowledgeRequest(
    Guid SubjectId,
    string Action,
    long ExpectedVersion,
    Guid? CommunityId,
    IReadOnlyDictionary<string, string> Values)
{
    public FeatureInput ToInput() => new(SubjectId, Action, ExpectedVersion, CommunityId, Values);
}

public sealed record MaintainRepositoryKnowledgeRecord(
    Guid Id,
    Guid? CommunityId,
    string State,
    long Version,
    bool IsAuthorized,
    bool IsAvailable)
{
    public FeatureState ToState() => new(Id, CommunityId, State, Version, IsAuthorized, IsAvailable);
}

public sealed record MaintainRepositoryKnowledgeDecision(
    string RequirementId,
    FeatureDecisionKind Kind,
    string Code,
    string ResultingState,
    long ResultingVersion)
{
    public bool IsAccepted => Kind == FeatureDecisionKind.Accepted;

    public static MaintainRepositoryKnowledgeDecision From(FeatureDecision decision) =>
        new(decision.RequirementId, decision.Kind, decision.Code, decision.ResultingState, decision.ResultingVersion);
}

public sealed class MaintainRepositoryKnowledgePolicy
{
    public MaintainRepositoryKnowledgeDecision MaintainAnOutcomeOrientedDocumentationMap(
        MaintainRepositoryKnowledgeRecord record,
        MaintainRepositoryKnowledgeRequest request) =>
        MaintainRepositoryKnowledgeDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-STRT-012", record.ToState(), request.ToInput()));

    public MaintainRepositoryKnowledgeDecision DocumentContributionOwnershipSupportAndDisclosure(
        MaintainRepositoryKnowledgeRecord record,
        MaintainRepositoryKnowledgeRequest request) =>
        MaintainRepositoryKnowledgeDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-STRT-014", record.ToState(), request.ToInput()));

    public MaintainRepositoryKnowledgeDecision TrackDependencyAndAssetProvenance(
        MaintainRepositoryKnowledgeRecord record,
        MaintainRepositoryKnowledgeRequest request) =>
        MaintainRepositoryKnowledgeDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-STRT-015", record.ToState(), request.ToInput()));
}

public static class MaintainRepositoryKnowledgeDescriptor
{
    public const string Subsystem = "starter-experience";
    public const string Slug = "maintain-repository-knowledge";
    public const string Title = "Repository knowledge stays current and actionable";

    public static IReadOnlyList<FeatureOperationDescriptor> Operations { get; } =
    [
        new("L2-STRT-012", "MaintainAnOutcomeOrientedDocumentationMap"),
        new("L2-STRT-014", "DocumentContributionOwnershipSupportAndDisclosure"),
        new("L2-STRT-015", "TrackDependencyAndAssetProvenance")
    ];
}
