// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;

namespace CommunityStarter.Domain.GeneratedFeatures;

public sealed record MakePublicDiscoveryCacheSafeRequest(
    Guid SubjectId,
    string Action,
    long ExpectedVersion,
    Guid? CommunityId,
    IReadOnlyDictionary<string, string> Values)
{
    public FeatureInput ToInput() => new(SubjectId, Action, ExpectedVersion, CommunityId, Values);
}

public sealed record MakePublicDiscoveryCacheSafeRecord(
    Guid Id,
    Guid? CommunityId,
    string State,
    long Version,
    bool IsAuthorized,
    bool IsAvailable)
{
    public FeatureState ToState() => new(Id, CommunityId, State, Version, IsAuthorized, IsAvailable);
}

public sealed record MakePublicDiscoveryCacheSafeDecision(
    string RequirementId,
    FeatureDecisionKind Kind,
    string Code,
    string ResultingState,
    long ResultingVersion)
{
    public bool IsAccepted => Kind == FeatureDecisionKind.Accepted;

    public static MakePublicDiscoveryCacheSafeDecision From(FeatureDecision decision) =>
        new(decision.RequirementId, decision.Kind, decision.Code, decision.ResultingState, decision.ResultingVersion);
}

public sealed class MakePublicDiscoveryCacheSafePolicy
{
    public MakePublicDiscoveryCacheSafeDecision PublicMetadataAndIndexingAreDeliberate(
        MakePublicDiscoveryCacheSafeRecord record,
        MakePublicDiscoveryCacheSafeRequest request) =>
        MakePublicDiscoveryCacheSafeDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-MKTG-007", record.ToState(), request.ToInput()));

    public MakePublicDiscoveryCacheSafeDecision PublicPerformanceHasAnExplicitBudget(
        MakePublicDiscoveryCacheSafeRecord record,
        MakePublicDiscoveryCacheSafeRequest request) =>
        MakePublicDiscoveryCacheSafeDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-MKTG-008", record.ToState(), request.ToInput()));

    public MakePublicDiscoveryCacheSafeDecision AnalyticsEmbedsAndAuthenticatedDataRemainPrivateByDesign(
        MakePublicDiscoveryCacheSafeRecord record,
        MakePublicDiscoveryCacheSafeRequest request) =>
        MakePublicDiscoveryCacheSafeDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-MKTG-009", record.ToState(), request.ToInput()));

    public MakePublicDiscoveryCacheSafeDecision CachePolicyDistinguishesImmutableAndRevalidatedContent(
        MakePublicDiscoveryCacheSafeRecord record,
        MakePublicDiscoveryCacheSafeRequest request) =>
        MakePublicDiscoveryCacheSafeDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-MKTG-010", record.ToState(), request.ToInput()));

    public MakePublicDiscoveryCacheSafeDecision PublishIndexableCommunitiesSafely(
        MakePublicDiscoveryCacheSafeRecord record,
        MakePublicDiscoveryCacheSafeRequest request) =>
        MakePublicDiscoveryCacheSafeDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-MKTG-013", record.ToState(), request.ToInput()));
}

public static class MakePublicDiscoveryCacheSafeDescriptor
{
    public const string Subsystem = "marketing-public-web";
    public const string Slug = "make-public-discovery-cache-safe";
    public const string Title = "Make public discovery fast, private, and cache-safe";

    public static IReadOnlyList<FeatureOperationDescriptor> Operations { get; } =
    [
        new("L2-MKTG-007", "PublicMetadataAndIndexingAreDeliberate"),
        new("L2-MKTG-008", "PublicPerformanceHasAnExplicitBudget"),
        new("L2-MKTG-009", "AnalyticsEmbedsAndAuthenticatedDataRemainPrivateByDesign"),
        new("L2-MKTG-010", "CachePolicyDistinguishesImmutableAndRevalidatedContent"),
        new("L2-MKTG-013", "PublishIndexableCommunitiesSafely")
    ];
}
