// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;

namespace CommunityStarter.Domain.GeneratedFeatures;

public sealed record MakeInteractionStatesResilientRequest(
    Guid SubjectId,
    string Action,
    long ExpectedVersion,
    Guid? CommunityId,
    IReadOnlyDictionary<string, string> Values)
{
    public FeatureInput ToInput() => new(SubjectId, Action, ExpectedVersion, CommunityId, Values);
}

public sealed record MakeInteractionStatesResilientRecord(
    Guid Id,
    Guid? CommunityId,
    string State,
    long Version,
    bool IsAuthorized,
    bool IsAvailable)
{
    public FeatureState ToState() => new(Id, CommunityId, State, Version, IsAuthorized, IsAvailable);
}

public sealed record MakeInteractionStatesResilientDecision(
    string RequirementId,
    FeatureDecisionKind Kind,
    string Code,
    string ResultingState,
    long ResultingVersion)
{
    public bool IsAccepted => Kind == FeatureDecisionKind.Accepted;

    public static MakeInteractionStatesResilientDecision From(FeatureDecision decision) =>
        new(decision.RequirementId, decision.Kind, decision.Code, decision.ResultingState, decision.ResultingVersion);
}

public sealed class MakeInteractionStatesResilientPolicy
{
    public MakeInteractionStatesResilientDecision TemplatesAndNavigationUseSemanticWebBehavior(
        MakeInteractionStatesResilientRecord record,
        MakeInteractionStatesResilientRequest request) =>
        MakeInteractionStatesResilientDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-UXDS-007", record.ToState(), request.ToInput()));

    public MakeInteractionStatesResilientDecision StylingLayoutMotionIconsAndMediaFollowSystemRules(
        MakeInteractionStatesResilientRecord record,
        MakeInteractionStatesResilientRequest request) =>
        MakeInteractionStatesResilientDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-UXDS-008", record.ToState(), request.ToInput()));

    public MakeInteractionStatesResilientDecision FeatureStatesAreCompleteAndServerTruthIsReconciled(
        MakeInteractionStatesResilientRecord record,
        MakeInteractionStatesResilientRequest request) =>
        MakeInteractionStatesResilientDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-UXDS-009", record.ToState(), request.ToInput()));
}

public static class MakeInteractionStatesResilientDescriptor
{
    public const string Subsystem = "experience-design-system";
    public const string Slug = "make-interaction-states-resilient";
    public const string Title = "Make every material interaction state resilient";

    public static IReadOnlyList<FeatureOperationDescriptor> Operations { get; } =
    [
        new("L2-UXDS-007", "TemplatesAndNavigationUseSemanticWebBehavior"),
        new("L2-UXDS-008", "StylingLayoutMotionIconsAndMediaFollowSystemRules"),
        new("L2-UXDS-009", "FeatureStatesAreCompleteAndServerTruthIsReconciled")
    ];
}
