// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;

namespace CommunityStarter.Domain.GeneratedFeatures;

public sealed record ManageSafeAccountLifecycleRequest(
    Guid SubjectId,
    string Action,
    long ExpectedVersion,
    Guid? CommunityId,
    IReadOnlyDictionary<string, string> Values)
{
    public FeatureInput ToInput() => new(SubjectId, Action, ExpectedVersion, CommunityId, Values);
}

public sealed record ManageSafeAccountLifecycleRecord(
    Guid Id,
    Guid? CommunityId,
    string State,
    long Version,
    bool IsAuthorized,
    bool IsAvailable)
{
    public FeatureState ToState() => new(Id, CommunityId, State, Version, IsAuthorized, IsAvailable);
}

public sealed record ManageSafeAccountLifecycleDecision(
    string RequirementId,
    FeatureDecisionKind Kind,
    string Code,
    string ResultingState,
    long ResultingVersion)
{
    public bool IsAccepted => Kind == FeatureDecisionKind.Accepted;

    public static ManageSafeAccountLifecycleDecision From(FeatureDecision decision) =>
        new(decision.RequirementId, decision.Kind, decision.Code, decision.ResultingState, decision.ResultingVersion);
}

public sealed class ManageSafeAccountLifecyclePolicy
{
    public ManageSafeAccountLifecycleDecision RegisterAnAccountSafely(
        ManageSafeAccountLifecycleRecord record,
        ManageSafeAccountLifecycleRequest request) =>
        ManageSafeAccountLifecycleDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-AUTH-001", record.ToState(), request.ToInput()));

    public ManageSafeAccountLifecycleDecision VerifyAccountOwnership(
        ManageSafeAccountLifecycleRecord record,
        ManageSafeAccountLifecycleRequest request) =>
        ManageSafeAccountLifecycleDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-AUTH-002", record.ToState(), request.ToInput()));

    public ManageSafeAccountLifecycleDecision RecoverAccountAccess(
        ManageSafeAccountLifecycleRecord record,
        ManageSafeAccountLifecycleRequest request) =>
        ManageSafeAccountLifecycleDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-AUTH-003", record.ToState(), request.ToInput()));

    public ManageSafeAccountLifecycleDecision EnterAccountDeactivationSafely(
        ManageSafeAccountLifecycleRecord record,
        ManageSafeAccountLifecycleRequest request) =>
        ManageSafeAccountLifecycleDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-AUTH-004", record.ToState(), request.ToInput()));

    public ManageSafeAccountLifecycleDecision ProtectLocalCredentialsAndActionSecrets(
        ManageSafeAccountLifecycleRecord record,
        ManageSafeAccountLifecycleRequest request) =>
        ManageSafeAccountLifecycleDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-AUTH-014", record.ToState(), request.ToInput()));
}

public static class ManageSafeAccountLifecycleDescriptor
{
    public const string Subsystem = "identity-access";
    public const string Slug = "manage-safe-account-lifecycle";
    public const string Title = "Safe Account lifecycle";

    public static IReadOnlyList<FeatureOperationDescriptor> Operations { get; } =
    [
        new("L2-AUTH-001", "RegisterAnAccountSafely"),
        new("L2-AUTH-002", "VerifyAccountOwnership"),
        new("L2-AUTH-003", "RecoverAccountAccess"),
        new("L2-AUTH-004", "EnterAccountDeactivationSafely"),
        new("L2-AUTH-014", "ProtectLocalCredentialsAndActionSecrets")
    ];
}
