// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;

namespace CommunityStarter.Domain.GeneratedFeatures;

public sealed record ManageAttendanceRequest(
    Guid SubjectId,
    string Action,
    long ExpectedVersion,
    Guid? CommunityId,
    IReadOnlyDictionary<string, string> Values)
{
    public FeatureInput ToInput() => new(SubjectId, Action, ExpectedVersion, CommunityId, Values);
}

public sealed record ManageAttendanceRecord(
    Guid Id,
    Guid? CommunityId,
    string State,
    long Version,
    bool IsAuthorized,
    bool IsAvailable)
{
    public FeatureState ToState() => new(Id, CommunityId, State, Version, IsAuthorized, IsAvailable);
}

public sealed record ManageAttendanceDecision(
    string RequirementId,
    FeatureDecisionKind Kind,
    string Code,
    string ResultingState,
    long ResultingVersion)
{
    public bool IsAccepted => Kind == FeatureDecisionKind.Accepted;

    public static ManageAttendanceDecision From(FeatureDecision decision) =>
        new(decision.RequirementId, decision.Kind, decision.Code, decision.ResultingState, decision.ResultingVersion);
}

public sealed class ManageAttendancePolicy
{
    public ManageAttendanceDecision TransitionOneCurrentRSVP(
        ManageAttendanceRecord record,
        ManageAttendanceRequest request) =>
        ManageAttendanceDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-EVNT-007", record.ToState(), request.ToInput()));

    public ManageAttendanceDecision AllocateCapacityAndWaitlistFairly(
        ManageAttendanceRecord record,
        ManageAttendanceRequest request) =>
        ManageAttendanceDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-EVNT-008", record.ToState(), request.ToInput()));

    public ManageAttendanceDecision ReconcileAttendanceAfterAccessLoss(
        ManageAttendanceRecord record,
        ManageAttendanceRequest request) =>
        ManageAttendanceDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-EVNT-013", record.ToState(), request.ToInput()));
}

public static class ManageAttendanceDescriptor
{
    public const string Subsystem = "community-events";
    public const string Slug = "manage-attendance";
    public const string Title = "Consistent attendance management";

    public static IReadOnlyList<FeatureOperationDescriptor> Operations { get; } =
    [
        new("L2-EVNT-007", "TransitionOneCurrentRSVP"),
        new("L2-EVNT-008", "AllocateCapacityAndWaitlistFairly"),
        new("L2-EVNT-013", "ReconcileAttendanceAfterAccessLoss")
    ];
}
