// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;

namespace CommunityStarter.Domain.GeneratedFeatures;

public sealed record ManageEventLifecycleRequest(
    Guid SubjectId,
    string Action,
    long ExpectedVersion,
    Guid? CommunityId,
    IReadOnlyDictionary<string, string> Values)
{
    public FeatureInput ToInput() => new(SubjectId, Action, ExpectedVersion, CommunityId, Values);
}

public sealed record ManageEventLifecycleRecord(
    Guid Id,
    Guid? CommunityId,
    string State,
    long Version,
    bool IsAuthorized,
    bool IsAvailable)
{
    public FeatureState ToState() => new(Id, CommunityId, State, Version, IsAuthorized, IsAvailable);
}

public sealed record ManageEventLifecycleDecision(
    string RequirementId,
    FeatureDecisionKind Kind,
    string Code,
    string ResultingState,
    long ResultingVersion)
{
    public bool IsAccepted => Kind == FeatureDecisionKind.Accepted;

    public static ManageEventLifecycleDecision From(FeatureDecision decision) =>
        new(decision.RequirementId, decision.Kind, decision.Code, decision.ResultingState, decision.ResultingVersion);
}

public sealed class ManageEventLifecyclePolicy
{
    public ManageEventLifecycleDecision CreateAValidEvent(
        ManageEventLifecycleRecord record,
        ManageEventLifecycleRequest request) =>
        ManageEventLifecycleDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-EVNT-001", record.ToState(), request.ToInput()));

    public ManageEventLifecycleDecision PublishReviseAndCancelAtomically(
        ManageEventLifecycleRecord record,
        ManageEventLifecycleRequest request) =>
        ManageEventLifecycleDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-EVNT-003", record.ToState(), request.ToInput()));
}

public static class ManageEventLifecycleDescriptor
{
    public const string Subsystem = "community-events";
    public const string Slug = "manage-event-lifecycle";
    public const string Title = "Trustworthy Event lifecycle";

    public static IReadOnlyList<FeatureOperationDescriptor> Operations { get; } =
    [
        new("L2-EVNT-001", "CreateAValidEvent"),
        new("L2-EVNT-003", "PublishReviseAndCancelAtomically")
    ];
}
