// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;

namespace CommunityStarter.Domain.GeneratedFeatures;

public sealed record ManageModerationCasesRequest(
    Guid SubjectId,
    string Action,
    long ExpectedVersion,
    Guid? CommunityId,
    IReadOnlyDictionary<string, string> Values)
{
    public FeatureInput ToInput() => new(SubjectId, Action, ExpectedVersion, CommunityId, Values);
}

public sealed record ManageModerationCasesRecord(
    Guid Id,
    Guid? CommunityId,
    string State,
    long Version,
    bool IsAuthorized,
    bool IsAvailable)
{
    public FeatureState ToState() => new(Id, CommunityId, State, Version, IsAuthorized, IsAvailable);
}

public sealed record ManageModerationCasesDecision(
    string RequirementId,
    FeatureDecisionKind Kind,
    string Code,
    string ResultingState,
    long ResultingVersion)
{
    public bool IsAccepted => Kind == FeatureDecisionKind.Accepted;

    public static ManageModerationCasesDecision From(FeatureDecision decision) =>
        new(decision.RequirementId, decision.Kind, decision.Code, decision.ResultingState, decision.ResultingVersion);
}

public sealed class ManageModerationCasesPolicy
{
    public ManageModerationCasesDecision CreateACaseWithDurableEvidence(
        ManageModerationCasesRecord record,
        ManageModerationCasesRequest request) =>
        ManageModerationCasesDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-SAFE-004", record.ToState(), request.ToInput()));

    public ManageModerationCasesDecision TriageAssignAndEscalateCases(
        ManageModerationCasesRecord record,
        ManageModerationCasesRequest request) =>
        ManageModerationCasesDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-SAFE-005", record.ToState(), request.ToInput()));

    public ManageModerationCasesDecision RestrictAndRetainSensitiveEvidence(
        ManageModerationCasesRecord record,
        ManageModerationCasesRequest request) =>
        ManageModerationCasesDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-SAFE-006", record.ToState(), request.ToInput()));
}

public static class ManageModerationCasesDescriptor
{
    public const string Subsystem = "moderation-trust-safety";
    public const string Slug = "manage-moderation-cases";
    public const string Title = "Durable Moderation Cases";

    public static IReadOnlyList<FeatureOperationDescriptor> Operations { get; } =
    [
        new("L2-SAFE-004", "CreateACaseWithDurableEvidence"),
        new("L2-SAFE-005", "TriageAssignAndEscalateCases"),
        new("L2-SAFE-006", "RestrictAndRetainSensitiveEvidence")
    ];
}
