// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;

namespace CommunityStarter.Domain.GeneratedFeatures;

public sealed record MeasureReliabilityCapacityRequest(
    Guid SubjectId,
    string Action,
    long ExpectedVersion,
    Guid? CommunityId,
    IReadOnlyDictionary<string, string> Values)
{
    public FeatureInput ToInput() => new(SubjectId, Action, ExpectedVersion, CommunityId, Values);
}

public sealed record MeasureReliabilityCapacityRecord(
    Guid Id,
    Guid? CommunityId,
    string State,
    long Version,
    bool IsAuthorized,
    bool IsAvailable)
{
    public FeatureState ToState() => new(Id, CommunityId, State, Version, IsAuthorized, IsAvailable);
}

public sealed record MeasureReliabilityCapacityDecision(
    string RequirementId,
    FeatureDecisionKind Kind,
    string Code,
    string ResultingState,
    long ResultingVersion)
{
    public bool IsAccepted => Kind == FeatureDecisionKind.Accepted;

    public static MeasureReliabilityCapacityDecision From(FeatureDecision decision) =>
        new(decision.RequirementId, decision.Kind, decision.Code, decision.ResultingState, decision.ResultingVersion);
}

public sealed class MeasureReliabilityCapacityPolicy
{
    public MeasureReliabilityCapacityDecision DefineAndReportServiceObjectives(
        MeasureReliabilityCapacityRecord record,
        MeasureReliabilityCapacityRequest request) =>
        MeasureReliabilityCapacityDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-OPER-005", record.ToState(), request.ToInput()));

    public MeasureReliabilityCapacityDecision EnforcePerformanceAndResourceBudgets(
        MeasureReliabilityCapacityRecord record,
        MeasureReliabilityCapacityRequest request) =>
        MeasureReliabilityCapacityDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-OPER-006", record.ToState(), request.ToInput()));

    public MeasureReliabilityCapacityDecision DegradeSafelyDuringDependencyFailure(
        MeasureReliabilityCapacityRecord record,
        MeasureReliabilityCapacityRequest request) =>
        MeasureReliabilityCapacityDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-OPER-008", record.ToState(), request.ToInput()));
}

public static class MeasureReliabilityCapacityDescriptor
{
    public const string Subsystem = "operations-reliability";
    public const string Slug = "measure-reliability-capacity";
    public const string Title = "Reliability and capacity are measurable";

    public static IReadOnlyList<FeatureOperationDescriptor> Operations { get; } =
    [
        new("L2-OPER-005", "DefineAndReportServiceObjectives"),
        new("L2-OPER-006", "EnforcePerformanceAndResourceBudgets"),
        new("L2-OPER-008", "DegradeSafelyDuringDependencyFailure")
    ];
}
