// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;

namespace CommunityStarter.Domain.GeneratedFeatures;

public sealed record MeetAccessibilityBaselineRequest(
    Guid SubjectId,
    string Action,
    long ExpectedVersion,
    Guid? CommunityId,
    IReadOnlyDictionary<string, string> Values)
{
    public FeatureInput ToInput() => new(SubjectId, Action, ExpectedVersion, CommunityId, Values);
}

public sealed record MeetAccessibilityBaselineRecord(
    Guid Id,
    Guid? CommunityId,
    string State,
    long Version,
    bool IsAuthorized,
    bool IsAvailable)
{
    public FeatureState ToState() => new(Id, CommunityId, State, Version, IsAuthorized, IsAvailable);
}

public sealed record MeetAccessibilityBaselineDecision(
    string RequirementId,
    FeatureDecisionKind Kind,
    string Code,
    string ResultingState,
    long ResultingVersion)
{
    public bool IsAccepted => Kind == FeatureDecisionKind.Accepted;

    public static MeetAccessibilityBaselineDecision From(FeatureDecision decision) =>
        new(decision.RequirementId, decision.Kind, decision.Code, decision.ResultingState, decision.ResultingVersion);
}

public sealed class MeetAccessibilityBaselinePolicy
{
    public MeetAccessibilityBaselineDecision SharedPrimitivesAreSemanticAndOperable(
        MeetAccessibilityBaselineRecord record,
        MeetAccessibilityBaselineRequest request) =>
        MeetAccessibilityBaselineDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-UXDS-010", record.ToState(), request.ToInput()));

    public MeetAccessibilityBaselineDecision DynamicStatusAndResponsiveCompositionRemainAccessible(
        MeetAccessibilityBaselineRecord record,
        MeetAccessibilityBaselineRequest request) =>
        MeetAccessibilityBaselineDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-UXDS-011", record.ToState(), request.ToInput()));
}

public static class MeetAccessibilityBaselineDescriptor
{
    public const string Subsystem = "experience-design-system";
    public const string Slug = "meet-accessibility-baseline";
    public const string Title = "Meet an inclusive accessibility baseline";

    public static IReadOnlyList<FeatureOperationDescriptor> Operations { get; } =
    [
        new("L2-UXDS-010", "SharedPrimitivesAreSemanticAndOperable"),
        new("L2-UXDS-011", "DynamicStatusAndResponsiveCompositionRemainAccessible")
    ];
}
