// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;

namespace CommunityStarter.Domain.GeneratedFeatures;

public sealed record MinimizePersonalDataUseRequest(
    Guid SubjectId,
    string Action,
    long ExpectedVersion,
    Guid? CommunityId,
    IReadOnlyDictionary<string, string> Values)
{
    public FeatureInput ToInput() => new(SubjectId, Action, ExpectedVersion, CommunityId, Values);
}

public sealed record MinimizePersonalDataUseRecord(
    Guid Id,
    Guid? CommunityId,
    string State,
    long Version,
    bool IsAuthorized,
    bool IsAvailable)
{
    public FeatureState ToState() => new(Id, CommunityId, State, Version, IsAuthorized, IsAvailable);
}

public sealed record MinimizePersonalDataUseDecision(
    string RequirementId,
    FeatureDecisionKind Kind,
    string Code,
    string ResultingState,
    long ResultingVersion)
{
    public bool IsAccepted => Kind == FeatureDecisionKind.Accepted;

    public static MinimizePersonalDataUseDecision From(FeatureDecision decision) =>
        new(decision.RequirementId, decision.Kind, decision.Code, decision.ResultingState, decision.ResultingVersion);
}

public sealed class MinimizePersonalDataUsePolicy
{
    public MinimizePersonalDataUseDecision MaintainAPersonalDataInventory(
        MinimizePersonalDataUseRecord record,
        MinimizePersonalDataUseRequest request) =>
        MinimizePersonalDataUseDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-PRIV-001", record.ToState(), request.ToInput()));

    public MinimizePersonalDataUseDecision ObtainAndHonorOptionalProcessingChoices(
        MinimizePersonalDataUseRecord record,
        MinimizePersonalDataUseRequest request) =>
        MinimizePersonalDataUseDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-PRIV-002", record.ToState(), request.ToInput()));

    public MinimizePersonalDataUseDecision ApplyPrivacyPreservingDefaults(
        MinimizePersonalDataUseRecord record,
        MinimizePersonalDataUseRequest request) =>
        MinimizePersonalDataUseDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-PRIV-003", record.ToState(), request.ToInput()));
}

public static class MinimizePersonalDataUseDescriptor
{
    public const string Subsystem = "privacy-data-lifecycle";
    public const string Slug = "minimize-personal-data-use";
    public const string Title = "Personal data use is explicit and minimized";

    public static IReadOnlyList<FeatureOperationDescriptor> Operations { get; } =
    [
        new("L2-PRIV-001", "MaintainAPersonalDataInventory"),
        new("L2-PRIV-002", "ObtainAndHonorOptionalProcessingChoices"),
        new("L2-PRIV-003", "ApplyPrivacyPreservingDefaults")
    ];
}
