// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;

namespace CommunityStarter.Domain.GeneratedFeatures;

public sealed record ModelThreatsAndIdentityRequest(
    Guid SubjectId,
    string Action,
    long ExpectedVersion,
    Guid? CommunityId,
    IReadOnlyDictionary<string, string> Values)
{
    public FeatureInput ToInput() => new(SubjectId, Action, ExpectedVersion, CommunityId, Values);
}

public sealed record ModelThreatsAndIdentityRecord(
    Guid Id,
    Guid? CommunityId,
    string State,
    long Version,
    bool IsAuthorized,
    bool IsAvailable)
{
    public FeatureState ToState() => new(Id, CommunityId, State, Version, IsAuthorized, IsAvailable);
}

public sealed record ModelThreatsAndIdentityDecision(
    string RequirementId,
    FeatureDecisionKind Kind,
    string Code,
    string ResultingState,
    long ResultingVersion)
{
    public bool IsAccepted => Kind == FeatureDecisionKind.Accepted;

    public static ModelThreatsAndIdentityDecision From(FeatureDecision decision) =>
        new(decision.RequirementId, decision.Kind, decision.Code, decision.ResultingState, decision.ResultingVersion);
}

public sealed class ModelThreatsAndIdentityPolicy
{
    public ModelThreatsAndIdentityDecision HighRiskCommunityFlowsHaveMaintainedThreatModels(
        ModelThreatsAndIdentityRecord record,
        ModelThreatsAndIdentityRequest request) =>
        ModelThreatsAndIdentityDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-SECU-001", record.ToState(), request.ToInput()));

    public ModelThreatsAndIdentityDecision ProductionIdentityAndSessionBehaviorCannotInheritDevelopmentShortcuts(
        ModelThreatsAndIdentityRecord record,
        ModelThreatsAndIdentityRequest request) =>
        ModelThreatsAndIdentityDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-SECU-002", record.ToState(), request.ToInput()));

    public ModelThreatsAndIdentityDecision EveryProtectedResourceIsAuthorizedInCommunityContext(
        ModelThreatsAndIdentityRecord record,
        ModelThreatsAndIdentityRequest request) =>
        ModelThreatsAndIdentityDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-SECU-003", record.ToState(), request.ToInput()));
}

public static class ModelThreatsAndIdentityDescriptor
{
    public const string Subsystem = "security";
    public const string Slug = "model-threats-and-identity";
    public const string Title = "Model threats and enforce identity in Community context";

    public static IReadOnlyList<FeatureOperationDescriptor> Operations { get; } =
    [
        new("L2-SECU-001", "HighRiskCommunityFlowsHaveMaintainedThreatModels"),
        new("L2-SECU-002", "ProductionIdentityAndSessionBehaviorCannotInheritDevelopmentShortcuts"),
        new("L2-SECU-003", "EveryProtectedResourceIsAuthorizedInCommunityContext")
    ];
}
