// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;

namespace CommunityStarter.Domain.GeneratedFeatures;

public sealed record ObserveAccessProtectionRequest(
    Guid SubjectId,
    string Action,
    long ExpectedVersion,
    Guid? CommunityId,
    IReadOnlyDictionary<string, string> Values)
{
    public FeatureInput ToInput() => new(SubjectId, Action, ExpectedVersion, CommunityId, Values);
}

public sealed record ObserveAccessProtectionRecord(
    Guid Id,
    Guid? CommunityId,
    string State,
    long Version,
    bool IsAuthorized,
    bool IsAvailable)
{
    public FeatureState ToState() => new(Id, CommunityId, State, Version, IsAuthorized, IsAvailable);
}

public sealed record ObserveAccessProtectionDecision(
    string RequirementId,
    FeatureDecisionKind Kind,
    string Code,
    string ResultingState,
    long ResultingVersion)
{
    public bool IsAccepted => Kind == FeatureDecisionKind.Accepted;

    public static ObserveAccessProtectionDecision From(FeatureDecision decision) =>
        new(decision.RequirementId, decision.Kind, decision.Code, decision.ResultingState, decision.ResultingVersion);
}

public sealed class ObserveAccessProtectionPolicy
{
    public ObserveAccessProtectionDecision LimitSensitiveAttempts(
        ObserveAccessProtectionRecord record,
        ObserveAccessProtectionRequest request) =>
        ObserveAccessProtectionDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-AUTH-011", record.ToState(), request.ToInput()));

    public ObserveAccessProtectionDecision RecordSecurityEvents(
        ObserveAccessProtectionRecord record,
        ObserveAccessProtectionRequest request) =>
        ObserveAccessProtectionDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-AUTH-012", record.ToState(), request.ToInput()));
}

public static class ObserveAccessProtectionDescriptor
{
    public const string Subsystem = "identity-access";
    public const string Slug = "observe-access-protection";
    public const string Title = "Observable access protection";

    public static IReadOnlyList<FeatureOperationDescriptor> Operations { get; } =
    [
        new("L2-AUTH-011", "LimitSensitiveAttempts"),
        new("L2-AUTH-012", "RecordSecurityEvents")
    ];
}
