// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;

namespace CommunityStarter.Domain.GeneratedFeatures;

public sealed record ObserveSystemProductHealthRequest(
    Guid SubjectId,
    string Action,
    long ExpectedVersion,
    Guid? CommunityId,
    IReadOnlyDictionary<string, string> Values)
{
    public FeatureInput ToInput() => new(SubjectId, Action, ExpectedVersion, CommunityId, Values);
}

public sealed record ObserveSystemProductHealthRecord(
    Guid Id,
    Guid? CommunityId,
    string State,
    long Version,
    bool IsAuthorized,
    bool IsAvailable)
{
    public FeatureState ToState() => new(Id, CommunityId, State, Version, IsAuthorized, IsAvailable);
}

public sealed record ObserveSystemProductHealthDecision(
    string RequirementId,
    FeatureDecisionKind Kind,
    string Code,
    string ResultingState,
    long ResultingVersion)
{
    public bool IsAccepted => Kind == FeatureDecisionKind.Accepted;

    public static ObserveSystemProductHealthDecision From(FeatureDecision decision) =>
        new(decision.RequirementId, decision.Kind, decision.Code, decision.ResultingState, decision.ResultingVersion);
}

public sealed class ObserveSystemProductHealthPolicy
{
    public ObserveSystemProductHealthDecision CorrelateStructuredOperationalTelemetry(
        ObserveSystemProductHealthRecord record,
        ObserveSystemProductHealthRequest request) =>
        ObserveSystemProductHealthDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-OPER-001", record.ToState(), request.ToInput()));

    public ObserveSystemProductHealthDecision MeasureTechnicalAndProductHealth(
        ObserveSystemProductHealthRecord record,
        ObserveSystemProductHealthRequest request) =>
        ObserveSystemProductHealthDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-OPER-002", record.ToState(), request.ToInput()));

    public ObserveSystemProductHealthDecision DistinguishLivenessReadinessAndDependencyHealth(
        ObserveSystemProductHealthRecord record,
        ObserveSystemProductHealthRequest request) =>
        ObserveSystemProductHealthDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-OPER-003", record.ToState(), request.ToInput()));

    public ObserveSystemProductHealthDecision ProvideOwnedOperationalDashboards(
        ObserveSystemProductHealthRecord record,
        ObserveSystemProductHealthRequest request) =>
        ObserveSystemProductHealthDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-OPER-004", record.ToState(), request.ToInput()));
}

public static class ObserveSystemProductHealthDescriptor
{
    public const string Subsystem = "operations-reliability";
    public const string Slug = "observe-system-product-health";
    public const string Title = "Operators can understand system and product health";

    public static IReadOnlyList<FeatureOperationDescriptor> Operations { get; } =
    [
        new("L2-OPER-001", "CorrelateStructuredOperationalTelemetry"),
        new("L2-OPER-002", "MeasureTechnicalAndProductHealth"),
        new("L2-OPER-003", "DistinguishLivenessReadinessAndDependencyHealth"),
        new("L2-OPER-004", "ProvideOwnedOperationalDashboards")
    ];
}
