// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;

namespace CommunityStarter.Domain.GeneratedFeatures;

public sealed record OfferRelevantDiscoveryRequest(
    Guid SubjectId,
    string Action,
    long ExpectedVersion,
    Guid? CommunityId,
    IReadOnlyDictionary<string, string> Values)
{
    public FeatureInput ToInput() => new(SubjectId, Action, ExpectedVersion, CommunityId, Values);
}

public sealed record OfferRelevantDiscoveryRecord(
    Guid Id,
    Guid? CommunityId,
    string State,
    long Version,
    bool IsAuthorized,
    bool IsAvailable)
{
    public FeatureState ToState() => new(Id, CommunityId, State, Version, IsAuthorized, IsAvailable);
}

public sealed record OfferRelevantDiscoveryDecision(
    string RequirementId,
    FeatureDecisionKind Kind,
    string Code,
    string ResultingState,
    long ResultingVersion)
{
    public bool IsAccepted => Kind == FeatureDecisionKind.Accepted;

    public static OfferRelevantDiscoveryDecision From(FeatureDecision decision) =>
        new(decision.RequirementId, decision.Kind, decision.Code, decision.ResultingState, decision.ResultingVersion);
}

public sealed class OfferRelevantDiscoveryPolicy
{
    public OfferRelevantDiscoveryDecision DiscoverEligibleCommunities(
        OfferRelevantDiscoveryRecord record,
        OfferRelevantDiscoveryRequest request) =>
        OfferRelevantDiscoveryDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-ONBD-004", record.ToState(), request.ToInput()));
}

public static class OfferRelevantDiscoveryDescriptor
{
    public const string Subsystem = "onboarding-discovery";
    public const string Slug = "offer-relevant-discovery";
    public const string Title = "Offer relevant discovery";

    public static IReadOnlyList<FeatureOperationDescriptor> Operations { get; } =
    [
        new("L2-ONBD-004", "DiscoverEligibleCommunities")
    ];
}
