// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;

namespace CommunityStarter.Domain.GeneratedFeatures;

public sealed record OperateNotificationChannelsRequest(
    Guid SubjectId,
    string Action,
    long ExpectedVersion,
    Guid? CommunityId,
    IReadOnlyDictionary<string, string> Values)
{
    public FeatureInput ToInput() => new(SubjectId, Action, ExpectedVersion, CommunityId, Values);
}

public sealed record OperateNotificationChannelsRecord(
    Guid Id,
    Guid? CommunityId,
    string State,
    long Version,
    bool IsAuthorized,
    bool IsAvailable)
{
    public FeatureState ToState() => new(Id, CommunityId, State, Version, IsAuthorized, IsAvailable);
}

public sealed record OperateNotificationChannelsDecision(
    string RequirementId,
    FeatureDecisionKind Kind,
    string Code,
    string ResultingState,
    long ResultingVersion)
{
    public bool IsAccepted => Kind == FeatureDecisionKind.Accepted;

    public static OperateNotificationChannelsDecision From(FeatureDecision decision) =>
        new(decision.RequirementId, decision.Kind, decision.Code, decision.ResultingState, decision.ResultingVersion);
}

public sealed class OperateNotificationChannelsPolicy
{
    public OperateNotificationChannelsDecision RenderSafeTemplatesAndActionLinks(
        OperateNotificationChannelsRecord record,
        OperateNotificationChannelsRequest request) =>
        OperateNotificationChannelsDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-NOTF-010", record.ToState(), request.ToInput()));

    public OperateNotificationChannelsDecision ObserveAndRepairDeliveryHealth(
        OperateNotificationChannelsRecord record,
        OperateNotificationChannelsRequest request) =>
        OperateNotificationChannelsDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-NOTF-011", record.ToState(), request.ToInput()));

    public OperateNotificationChannelsDecision DisableUnconfiguredChannelsCleanly(
        OperateNotificationChannelsRecord record,
        OperateNotificationChannelsRequest request) =>
        OperateNotificationChannelsDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-NOTF-012", record.ToState(), request.ToInput()));
}

public static class OperateNotificationChannelsDescriptor
{
    public const string Subsystem = "notifications-delivery";
    public const string Slug = "operate-notification-channels";
    public const string Title = "Safe templates and operable channels";

    public static IReadOnlyList<FeatureOperationDescriptor> Operations { get; } =
    [
        new("L2-NOTF-010", "RenderSafeTemplatesAndActionLinks"),
        new("L2-NOTF-011", "ObserveAndRepairDeliveryHealth"),
        new("L2-NOTF-012", "DisableUnconfiguredChannelsCleanly")
    ];
}
