// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;

namespace CommunityStarter.Domain.GeneratedFeatures;

public sealed record OperateTelemetryAndRecoveryRequest(
    Guid SubjectId,
    string Action,
    long ExpectedVersion,
    Guid? CommunityId,
    IReadOnlyDictionary<string, string> Values)
{
    public FeatureInput ToInput() => new(SubjectId, Action, ExpectedVersion, CommunityId, Values);
}

public sealed record OperateTelemetryAndRecoveryRecord(
    Guid Id,
    Guid? CommunityId,
    string State,
    long Version,
    bool IsAuthorized,
    bool IsAvailable)
{
    public FeatureState ToState() => new(Id, CommunityId, State, Version, IsAuthorized, IsAvailable);
}

public sealed record OperateTelemetryAndRecoveryDecision(
    string RequirementId,
    FeatureDecisionKind Kind,
    string Code,
    string ResultingState,
    long ResultingVersion)
{
    public bool IsAccepted => Kind == FeatureDecisionKind.Accepted;

    public static OperateTelemetryAndRecoveryDecision From(FeatureDecision decision) =>
        new(decision.RequirementId, decision.Kind, decision.Code, decision.ResultingState, decision.ResultingVersion);
}

public sealed class OperateTelemetryAndRecoveryPolicy
{
    public OperateTelemetryAndRecoveryDecision LogsMetricsTracesAndHealthExposeActionableSignals(
        OperateTelemetryAndRecoveryRecord record,
        OperateTelemetryAndRecoveryRequest request) =>
        OperateTelemetryAndRecoveryDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-QUAL-016", record.ToState(), request.ToInput()));

    public OperateTelemetryAndRecoveryDecision AlertsRecoveryMigrationRetentionAndIncidentsHaveOwnersAndRehearsal(
        OperateTelemetryAndRecoveryRecord record,
        OperateTelemetryAndRecoveryRequest request) =>
        OperateTelemetryAndRecoveryDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-QUAL-017", record.ToState(), request.ToInput()));
}

public static class OperateTelemetryAndRecoveryDescriptor
{
    public const string Subsystem = "delivery-quality";
    public const string Slug = "operate-telemetry-and-recovery";
    public const string Title = "Operate the starter with actionable telemetry and recovery";

    public static IReadOnlyList<FeatureOperationDescriptor> Operations { get; } =
    [
        new("L2-QUAL-016", "LogsMetricsTracesAndHealthExposeActionableSignals"),
        new("L2-QUAL-017", "AlertsRecoveryMigrationRetentionAndIncidentsHaveOwnersAndRehearsal")
    ];
}
