// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;

namespace CommunityStarter.Domain.GeneratedFeatures;

public sealed record OperateSecurityReadinessRequest(
    Guid SubjectId,
    string Action,
    long ExpectedVersion,
    Guid? CommunityId,
    IReadOnlyDictionary<string, string> Values)
{
    public FeatureInput ToInput() => new(SubjectId, Action, ExpectedVersion, CommunityId, Values);
}

public sealed record OperateSecurityReadinessRecord(
    Guid Id,
    Guid? CommunityId,
    string State,
    long Version,
    bool IsAuthorized,
    bool IsAvailable)
{
    public FeatureState ToState() => new(Id, CommunityId, State, Version, IsAuthorized, IsAvailable);
}

public sealed record OperateSecurityReadinessDecision(
    string RequirementId,
    FeatureDecisionKind Kind,
    string Code,
    string ResultingState,
    long ResultingVersion)
{
    public bool IsAccepted => Kind == FeatureDecisionKind.Accepted;

    public static OperateSecurityReadinessDecision From(FeatureDecision decision) =>
        new(decision.RequirementId, decision.Kind, decision.Code, decision.ResultingState, decision.ResultingVersion);
}

public sealed class OperateSecurityReadinessPolicy
{
    public OperateSecurityReadinessDecision VulnerabilitiesHaveAPrivateReportingAndRemediationPath(
        OperateSecurityReadinessRecord record,
        OperateSecurityReadinessRequest request) =>
        OperateSecurityReadinessDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-SECU-013", record.ToState(), request.ToInput()));

    public OperateSecurityReadinessDecision PrivacyConsentRetentionAndAnalyticsPurposeAreDeclared(
        OperateSecurityReadinessRecord record,
        OperateSecurityReadinessRequest request) =>
        OperateSecurityReadinessDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-SECU-014", record.ToState(), request.ToInput()));

    public OperateSecurityReadinessDecision ProductionSecurityClaimsDistinguishChecksFromIndependentReview(
        OperateSecurityReadinessRecord record,
        OperateSecurityReadinessRequest request) =>
        OperateSecurityReadinessDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-SECU-015", record.ToState(), request.ToInput()));
}

public static class OperateSecurityReadinessDescriptor
{
    public const string Subsystem = "security";
    public const string Slug = "operate-security-readiness";
    public const string Title = "Operate with explicit privacy and security readiness";

    public static IReadOnlyList<FeatureOperationDescriptor> Operations { get; } =
    [
        new("L2-SECU-013", "VulnerabilitiesHaveAPrivateReportingAndRemediationPath"),
        new("L2-SECU-014", "PrivacyConsentRetentionAndAnalyticsPurposeAreDeclared"),
        new("L2-SECU-015", "ProductionSecurityClaimsDistinguishChecksFromIndependentReview")
    ];
}
