// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;

namespace CommunityStarter.Domain.GeneratedFeatures;

public sealed record PreserveCommunityIntegrityRequest(
    Guid SubjectId,
    string Action,
    long ExpectedVersion,
    Guid? CommunityId,
    IReadOnlyDictionary<string, string> Values)
{
    public FeatureInput ToInput() => new(SubjectId, Action, ExpectedVersion, CommunityId, Values);
}

public sealed record PreserveCommunityIntegrityRecord(
    Guid Id,
    Guid? CommunityId,
    string State,
    long Version,
    bool IsAuthorized,
    bool IsAvailable)
{
    public FeatureState ToState() => new(Id, CommunityId, State, Version, IsAuthorized, IsAvailable);
}

public sealed record PreserveCommunityIntegrityDecision(
    string RequirementId,
    FeatureDecisionKind Kind,
    string Code,
    string ResultingState,
    long ResultingVersion)
{
    public bool IsAccepted => Kind == FeatureDecisionKind.Accepted;

    public static PreserveCommunityIntegrityDecision From(FeatureDecision decision) =>
        new(decision.RequirementId, decision.Kind, decision.Code, decision.ResultingState, decision.ResultingVersion);
}

public sealed class PreserveCommunityIntegrityPolicy
{
    public PreserveCommunityIntegrityDecision IsolateCommunityState(
        PreserveCommunityIntegrityRecord record,
        PreserveCommunityIntegrityRequest request) =>
        PreserveCommunityIntegrityDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-COMM-011", record.ToState(), request.ToInput()));

    public PreserveCommunityIntegrityDecision EnforceLimitsAndConcurrency(
        PreserveCommunityIntegrityRecord record,
        PreserveCommunityIntegrityRequest request) =>
        PreserveCommunityIntegrityDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-COMM-012", record.ToState(), request.ToInput()));
}

public static class PreserveCommunityIntegrityDescriptor
{
    public const string Subsystem = "communities-membership";
    public const string Slug = "preserve-community-integrity";
    public const string Title = "Preserve Community integrity";

    public static IReadOnlyList<FeatureOperationDescriptor> Operations { get; } =
    [
        new("L2-COMM-011", "IsolateCommunityState"),
        new("L2-COMM-012", "EnforceLimitsAndConcurrency")
    ];
}
