// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;

namespace CommunityStarter.Domain.GeneratedFeatures;

public sealed record PresentTrustworthyProfileRequest(
    Guid SubjectId,
    string Action,
    long ExpectedVersion,
    Guid? CommunityId,
    IReadOnlyDictionary<string, string> Values)
{
    public FeatureInput ToInput() => new(SubjectId, Action, ExpectedVersion, CommunityId, Values);
}

public sealed record PresentTrustworthyProfileRecord(
    Guid Id,
    Guid? CommunityId,
    string State,
    long Version,
    bool IsAuthorized,
    bool IsAvailable)
{
    public FeatureState ToState() => new(Id, CommunityId, State, Version, IsAuthorized, IsAvailable);
}

public sealed record PresentTrustworthyProfileDecision(
    string RequirementId,
    FeatureDecisionKind Kind,
    string Code,
    string ResultingState,
    long ResultingVersion)
{
    public bool IsAccepted => Kind == FeatureDecisionKind.Accepted;

    public static PresentTrustworthyProfileDecision From(FeatureDecision decision) =>
        new(decision.RequirementId, decision.Kind, decision.Code, decision.ResultingState, decision.ResultingVersion);
}

public sealed class PresentTrustworthyProfilePolicy
{
    public PresentTrustworthyProfileDecision ProvisionOneProfile(
        PresentTrustworthyProfileRecord record,
        PresentTrustworthyProfileRequest request) =>
        PresentTrustworthyProfileDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-PROF-001", record.ToState(), request.ToInput()));

    public PresentTrustworthyProfileDecision UpdateOwnedProfileFields(
        PresentTrustworthyProfileRecord record,
        PresentTrustworthyProfileRequest request) =>
        PresentTrustworthyProfileDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-PROF-002", record.ToState(), request.ToInput()));

    public PresentTrustworthyProfileDecision ControlProfileVisibility(
        PresentTrustworthyProfileRecord record,
        PresentTrustworthyProfileRequest request) =>
        PresentTrustworthyProfileDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-PROF-003", record.ToState(), request.ToInput()));

    public PresentTrustworthyProfileDecision ManageProfileImagery(
        PresentTrustworthyProfileRecord record,
        PresentTrustworthyProfileRequest request) =>
        PresentTrustworthyProfileDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-PROF-004", record.ToState(), request.ToInput()));
}

public static class PresentTrustworthyProfileDescriptor
{
    public const string Subsystem = "profiles-relationships";
    public const string Slug = "present-trustworthy-profile";
    public const string Title = "Present a trustworthy Profile";

    public static IReadOnlyList<FeatureOperationDescriptor> Operations { get; } =
    [
        new("L2-PROF-001", "ProvisionOneProfile"),
        new("L2-PROF-002", "UpdateOwnedProfileFields"),
        new("L2-PROF-003", "ControlProfileVisibility"),
        new("L2-PROF-004", "ManageProfileImagery")
    ];
}
