// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;

namespace CommunityStarter.Domain.GeneratedFeatures;

public sealed record PreserveFullStackBoundariesRequest(
    Guid SubjectId,
    string Action,
    long ExpectedVersion,
    Guid? CommunityId,
    IReadOnlyDictionary<string, string> Values)
{
    public FeatureInput ToInput() => new(SubjectId, Action, ExpectedVersion, CommunityId, Values);
}

public sealed record PreserveFullStackBoundariesRecord(
    Guid Id,
    Guid? CommunityId,
    string State,
    long Version,
    bool IsAuthorized,
    bool IsAvailable)
{
    public FeatureState ToState() => new(Id, CommunityId, State, Version, IsAuthorized, IsAvailable);
}

public sealed record PreserveFullStackBoundariesDecision(
    string RequirementId,
    FeatureDecisionKind Kind,
    string Code,
    string ResultingState,
    long ResultingVersion)
{
    public bool IsAccepted => Kind == FeatureDecisionKind.Accepted;

    public static PreserveFullStackBoundariesDecision From(FeatureDecision decision) =>
        new(decision.RequirementId, decision.Kind, decision.Code, decision.ResultingState, decision.ResultingVersion);
}

public sealed class PreserveFullStackBoundariesPolicy
{
    public PreserveFullStackBoundariesDecision RuntimeAndRepositorySurfacesAreExplicit(
        PreserveFullStackBoundariesRecord record,
        PreserveFullStackBoundariesRequest request) =>
        PreserveFullStackBoundariesDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-ARCH-001", record.ToState(), request.ToInput()));

    public PreserveFullStackBoundariesDecision BackendDependenciesPointInward(
        PreserveFullStackBoundariesRecord record,
        PreserveFullStackBoundariesRequest request) =>
        PreserveFullStackBoundariesDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-ARCH-002", record.ToState(), request.ToInput()));

    public PreserveFullStackBoundariesDecision AngularLibrariesHaveStableOwnership(
        PreserveFullStackBoundariesRecord record,
        PreserveFullStackBoundariesRequest request) =>
        PreserveFullStackBoundariesDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-ARCH-003", record.ToState(), request.ToInput()));
}

public static class PreserveFullStackBoundariesDescriptor
{
    public const string Subsystem = "platform-architecture";
    public const string Slug = "preserve-full-stack-boundaries";
    public const string Title = "Preserve explicit full-stack boundaries";

    public static IReadOnlyList<FeatureOperationDescriptor> Operations { get; } =
    [
        new("L2-ARCH-001", "RuntimeAndRepositorySurfacesAreExplicit"),
        new("L2-ARCH-002", "BackendDependenciesPointInward"),
        new("L2-ARCH-003", "AngularLibrariesHaveStableOwnership")
    ];
}
