// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;

namespace CommunityStarter.Domain.GeneratedFeatures;

public sealed record PreserveContentIntegrityRequest(
    Guid SubjectId,
    string Action,
    long ExpectedVersion,
    Guid? CommunityId,
    IReadOnlyDictionary<string, string> Values)
{
    public FeatureInput ToInput() => new(SubjectId, Action, ExpectedVersion, CommunityId, Values);
}

public sealed record PreserveContentIntegrityRecord(
    Guid Id,
    Guid? CommunityId,
    string State,
    long Version,
    bool IsAuthorized,
    bool IsAvailable)
{
    public FeatureState ToState() => new(Id, CommunityId, State, Version, IsAuthorized, IsAvailable);
}

public sealed record PreserveContentIntegrityDecision(
    string RequirementId,
    FeatureDecisionKind Kind,
    string Code,
    string ResultingState,
    long ResultingVersion)
{
    public bool IsAccepted => Kind == FeatureDecisionKind.Accepted;

    public static PreserveContentIntegrityDecision From(FeatureDecision decision) =>
        new(decision.RequirementId, decision.Kind, decision.Code, decision.ResultingState, decision.ResultingVersion);
}

public sealed class PreserveContentIntegrityPolicy
{
    public PreserveContentIntegrityDecision ApplyTagsConsistently(
        PreserveContentIntegrityRecord record,
        PreserveContentIntegrityRequest request) =>
        PreserveContentIntegrityDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-CONT-011", record.ToState(), request.ToInput()));

    public PreserveContentIntegrityDecision ValidateAndRenderSafely(
        PreserveContentIntegrityRecord record,
        PreserveContentIntegrityRequest request) =>
        PreserveContentIntegrityDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-CONT-012", record.ToState(), request.ToInput()));

    public PreserveContentIntegrityDecision CommitContentAtomically(
        PreserveContentIntegrityRecord record,
        PreserveContentIntegrityRequest request) =>
        PreserveContentIntegrityDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-CONT-013", record.ToState(), request.ToInput()));

    public PreserveContentIntegrityDecision ResolveMentionsAndQuoteReferences(
        PreserveContentIntegrityRecord record,
        PreserveContentIntegrityRequest request) =>
        PreserveContentIntegrityDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-CONT-015", record.ToState(), request.ToInput()));
}

public static class PreserveContentIntegrityDescriptor
{
    public const string Subsystem = "content-media";
    public const string Slug = "preserve-content-integrity";
    public const string Title = "Preserve content integrity";

    public static IReadOnlyList<FeatureOperationDescriptor> Operations { get; } =
    [
        new("L2-CONT-011", "ApplyTagsConsistently"),
        new("L2-CONT-012", "ValidateAndRenderSafely"),
        new("L2-CONT-013", "CommitContentAtomically"),
        new("L2-CONT-015", "ResolveMentionsAndQuoteReferences")
    ];
}
