// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;

namespace CommunityStarter.Domain.GeneratedFeatures;

public sealed record ProtectAuthenticatedSessionsRequest(
    Guid SubjectId,
    string Action,
    long ExpectedVersion,
    Guid? CommunityId,
    IReadOnlyDictionary<string, string> Values)
{
    public FeatureInput ToInput() => new(SubjectId, Action, ExpectedVersion, CommunityId, Values);
}

public sealed record ProtectAuthenticatedSessionsRecord(
    Guid Id,
    Guid? CommunityId,
    string State,
    long Version,
    bool IsAuthorized,
    bool IsAvailable)
{
    public FeatureState ToState() => new(Id, CommunityId, State, Version, IsAuthorized, IsAvailable);
}

public sealed record ProtectAuthenticatedSessionsDecision(
    string RequirementId,
    FeatureDecisionKind Kind,
    string Code,
    string ResultingState,
    long ResultingVersion)
{
    public bool IsAccepted => Kind == FeatureDecisionKind.Accepted;

    public static ProtectAuthenticatedSessionsDecision From(FeatureDecision decision) =>
        new(decision.RequirementId, decision.Kind, decision.Code, decision.ResultingState, decision.ResultingVersion);
}

public sealed class ProtectAuthenticatedSessionsPolicy
{
    public ProtectAuthenticatedSessionsDecision SignInWithoutEnumeration(
        ProtectAuthenticatedSessionsRecord record,
        ProtectAuthenticatedSessionsRequest request) =>
        ProtectAuthenticatedSessionsDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-AUTH-005", record.ToState(), request.ToInput()));

    public ProtectAuthenticatedSessionsDecision RequireStrongerVerification(
        ProtectAuthenticatedSessionsRecord record,
        ProtectAuthenticatedSessionsRequest request) =>
        ProtectAuthenticatedSessionsDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-AUTH-006", record.ToState(), request.ToInput()));

    public ProtectAuthenticatedSessionsDecision RotateAndRevokeSessions(
        ProtectAuthenticatedSessionsRecord record,
        ProtectAuthenticatedSessionsRequest request) =>
        ProtectAuthenticatedSessionsDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-AUTH-007", record.ToState(), request.ToInput()));

    public ProtectAuthenticatedSessionsDecision IssueRestrictedRemediationSessions(
        ProtectAuthenticatedSessionsRecord record,
        ProtectAuthenticatedSessionsRequest request) =>
        ProtectAuthenticatedSessionsDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-AUTH-015", record.ToState(), request.ToInput()));

    public ProtectAuthenticatedSessionsDecision GovernStrongerFactorLifecycle(
        ProtectAuthenticatedSessionsRecord record,
        ProtectAuthenticatedSessionsRequest request) =>
        ProtectAuthenticatedSessionsDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-AUTH-016", record.ToState(), request.ToInput()));
}

public static class ProtectAuthenticatedSessionsDescriptor
{
    public const string Subsystem = "identity-access";
    public const string Slug = "protect-authenticated-sessions";
    public const string Title = "Defensible authenticated sessions";

    public static IReadOnlyList<FeatureOperationDescriptor> Operations { get; } =
    [
        new("L2-AUTH-005", "SignInWithoutEnumeration"),
        new("L2-AUTH-006", "RequireStrongerVerification"),
        new("L2-AUTH-007", "RotateAndRevokeSessions"),
        new("L2-AUTH-015", "IssueRestrictedRemediationSessions"),
        new("L2-AUTH-016", "GovernStrongerFactorLifecycle")
    ];
}
