// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;

namespace CommunityStarter.Domain.GeneratedFeatures;

public sealed record ProtectDataPersistenceIntegrityRequest(
    Guid SubjectId,
    string Action,
    long ExpectedVersion,
    Guid? CommunityId,
    IReadOnlyDictionary<string, string> Values)
{
    public FeatureInput ToInput() => new(SubjectId, Action, ExpectedVersion, CommunityId, Values);
}

public sealed record ProtectDataPersistenceIntegrityRecord(
    Guid Id,
    Guid? CommunityId,
    string State,
    long Version,
    bool IsAuthorized,
    bool IsAvailable)
{
    public FeatureState ToState() => new(Id, CommunityId, State, Version, IsAuthorized, IsAvailable);
}

public sealed record ProtectDataPersistenceIntegrityDecision(
    string RequirementId,
    FeatureDecisionKind Kind,
    string Code,
    string ResultingState,
    long ResultingVersion)
{
    public bool IsAccepted => Kind == FeatureDecisionKind.Accepted;

    public static ProtectDataPersistenceIntegrityDecision From(FeatureDecision decision) =>
        new(decision.RequirementId, decision.Kind, decision.Code, decision.ResultingState, decision.ResultingVersion);
}

public sealed class ProtectDataPersistenceIntegrityPolicy
{
    public ProtectDataPersistenceIntegrityDecision RelationalSchemaEvolutionIsForwardAndRehearsable(
        ProtectDataPersistenceIntegrityRecord record,
        ProtectDataPersistenceIntegrityRequest request) =>
        ProtectDataPersistenceIntegrityDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-ARCH-007", record.ToState(), request.ToInput()));

    public ProtectDataPersistenceIntegrityDecision CommunityScopedReadsAreExplicitAndEfficient(
        ProtectDataPersistenceIntegrityRecord record,
        ProtectDataPersistenceIntegrityRequest request) =>
        ProtectDataPersistenceIntegrityDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-ARCH-008", record.ToState(), request.ToInput()));

    public ProtectDataPersistenceIntegrityDecision TimeDemonstrationDataAndLifecycleStateAreDeliberate(
        ProtectDataPersistenceIntegrityRecord record,
        ProtectDataPersistenceIntegrityRequest request) =>
        ProtectDataPersistenceIntegrityDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-ARCH-009", record.ToState(), request.ToInput()));
}

public static class ProtectDataPersistenceIntegrityDescriptor
{
    public const string Subsystem = "platform-architecture";
    public const string Slug = "protect-data-persistence-integrity";
    public const string Title = "Protect Community data and persistence integrity";

    public static IReadOnlyList<FeatureOperationDescriptor> Operations { get; } =
    [
        new("L2-ARCH-007", "RelationalSchemaEvolutionIsForwardAndRehearsable"),
        new("L2-ARCH-008", "CommunityScopedReadsAreExplicitAndEfficient"),
        new("L2-ARCH-009", "TimeDemonstrationDataAndLifecycleStateAreDeliberate")
    ];
}
