// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;

namespace CommunityStarter.Domain.GeneratedFeatures;

public sealed record ProtectSecretsDiagnosticsDataRequest(
    Guid SubjectId,
    string Action,
    long ExpectedVersion,
    Guid? CommunityId,
    IReadOnlyDictionary<string, string> Values)
{
    public FeatureInput ToInput() => new(SubjectId, Action, ExpectedVersion, CommunityId, Values);
}

public sealed record ProtectSecretsDiagnosticsDataRecord(
    Guid Id,
    Guid? CommunityId,
    string State,
    long Version,
    bool IsAuthorized,
    bool IsAvailable)
{
    public FeatureState ToState() => new(Id, CommunityId, State, Version, IsAuthorized, IsAvailable);
}

public sealed record ProtectSecretsDiagnosticsDataDecision(
    string RequirementId,
    FeatureDecisionKind Kind,
    string Code,
    string ResultingState,
    long ResultingVersion)
{
    public bool IsAccepted => Kind == FeatureDecisionKind.Accepted;

    public static ProtectSecretsDiagnosticsDataDecision From(FeatureDecision decision) =>
        new(decision.RequirementId, decision.Kind, decision.Code, decision.ResultingState, decision.ResultingVersion);
}

public sealed class ProtectSecretsDiagnosticsDataPolicy
{
    public ProtectSecretsDiagnosticsDataDecision SecretsStayOutsideSourceAndPlaceholdersFailSafely(
        ProtectSecretsDiagnosticsDataRecord record,
        ProtectSecretsDiagnosticsDataRequest request) =>
        ProtectSecretsDiagnosticsDataDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-SECU-004", record.ToState(), request.ToInput()));

    public ProtectSecretsDiagnosticsDataDecision PublicFailuresAreSanitizedAndPrivateDiagnosticsAreRedacted(
        ProtectSecretsDiagnosticsDataRecord record,
        ProtectSecretsDiagnosticsDataRequest request) =>
        ProtectSecretsDiagnosticsDataDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-SECU-005", record.ToState(), request.ToInput()));

    public ProtectSecretsDiagnosticsDataDecision SourceFixturesAndDemosContainNoRealPersonalData(
        ProtectSecretsDiagnosticsDataRecord record,
        ProtectSecretsDiagnosticsDataRequest request) =>
        ProtectSecretsDiagnosticsDataDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-SECU-006", record.ToState(), request.ToInput()));

    public ProtectSecretsDiagnosticsDataDecision EncryptProtectedDataAndGovernKeys(
        ProtectSecretsDiagnosticsDataRecord record,
        ProtectSecretsDiagnosticsDataRequest request) =>
        ProtectSecretsDiagnosticsDataDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-SECU-016", record.ToState(), request.ToInput()));
}

public static class ProtectSecretsDiagnosticsDataDescriptor
{
    public const string Subsystem = "security";
    public const string Slug = "protect-secrets-diagnostics-data";
    public const string Title = "Keep secrets, diagnostics, and personal data out of unsafe channels";

    public static IReadOnlyList<FeatureOperationDescriptor> Operations { get; } =
    [
        new("L2-SECU-004", "SecretsStayOutsideSourceAndPlaceholdersFailSafely"),
        new("L2-SECU-005", "PublicFailuresAreSanitizedAndPrivateDiagnosticsAreRedacted"),
        new("L2-SECU-006", "SourceFixturesAndDemosContainNoRealPersonalData"),
        new("L2-SECU-016", "EncryptProtectedDataAndGovernKeys")
    ];
}
