// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;

namespace CommunityStarter.Domain.GeneratedFeatures;

public sealed record ProvideAngularComponentContractsRequest(
    Guid SubjectId,
    string Action,
    long ExpectedVersion,
    Guid? CommunityId,
    IReadOnlyDictionary<string, string> Values)
{
    public FeatureInput ToInput() => new(SubjectId, Action, ExpectedVersion, CommunityId, Values);
}

public sealed record ProvideAngularComponentContractsRecord(
    Guid Id,
    Guid? CommunityId,
    string State,
    long Version,
    bool IsAuthorized,
    bool IsAvailable)
{
    public FeatureState ToState() => new(Id, CommunityId, State, Version, IsAuthorized, IsAvailable);
}

public sealed record ProvideAngularComponentContractsDecision(
    string RequirementId,
    FeatureDecisionKind Kind,
    string Code,
    string ResultingState,
    long ResultingVersion)
{
    public bool IsAccepted => Kind == FeatureDecisionKind.Accepted;

    public static ProvideAngularComponentContractsDecision From(FeatureDecision decision) =>
        new(decision.RequirementId, decision.Kind, decision.Code, decision.ResultingState, decision.ResultingVersion);
}

public sealed class ProvideAngularComponentContractsPolicy
{
    public ProvideAngularComponentContractsDecision AngularSourceIsStrictFocusedAndAdjacent(
        ProvideAngularComponentContractsRecord record,
        ProvideAngularComponentContractsRequest request) =>
        ProvideAngularComponentContractsDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-UXDS-004", record.ToState(), request.ToInput()));

    public ProvideAngularComponentContractsDecision PresentationalComponentsReceiveDataAndEmitIntent(
        ProvideAngularComponentContractsRecord record,
        ProvideAngularComponentContractsRequest request) =>
        ProvideAngularComponentContractsDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-UXDS-005", record.ToState(), request.ToInput()));

    public ProvideAngularComponentContractsDecision RemoteAndDerivedStateRemainExplicit(
        ProvideAngularComponentContractsRecord record,
        ProvideAngularComponentContractsRequest request) =>
        ProvideAngularComponentContractsDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-UXDS-006", record.ToState(), request.ToInput()));
}

public static class ProvideAngularComponentContractsDescriptor
{
    public const string Subsystem = "experience-design-system";
    public const string Slug = "provide-angular-component-contracts";
    public const string Title = "Provide disciplined Angular component contracts";

    public static IReadOnlyList<FeatureOperationDescriptor> Operations { get; } =
    [
        new("L2-UXDS-004", "AngularSourceIsStrictFocusedAndAdjacent"),
        new("L2-UXDS-005", "PresentationalComponentsReceiveDataAndEmitIntent"),
        new("L2-UXDS-006", "RemoteAndDerivedStateRemainExplicit")
    ];
}
