// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;

namespace CommunityStarter.Domain.GeneratedFeatures;

public sealed record PublishUnambiguousRoutesRequest(
    Guid SubjectId,
    string Action,
    long ExpectedVersion,
    Guid? CommunityId,
    IReadOnlyDictionary<string, string> Values)
{
    public FeatureInput ToInput() => new(SubjectId, Action, ExpectedVersion, CommunityId, Values);
}

public sealed record PublishUnambiguousRoutesRecord(
    Guid Id,
    Guid? CommunityId,
    string State,
    long Version,
    bool IsAuthorized,
    bool IsAvailable)
{
    public FeatureState ToState() => new(Id, CommunityId, State, Version, IsAuthorized, IsAvailable);
}

public sealed record PublishUnambiguousRoutesDecision(
    string RequirementId,
    FeatureDecisionKind Kind,
    string Code,
    string ResultingState,
    long ResultingVersion)
{
    public bool IsAccepted => Kind == FeatureDecisionKind.Accepted;

    public static PublishUnambiguousRoutesDecision From(FeatureDecision decision) =>
        new(decision.RequirementId, decision.Kind, decision.Code, decision.ResultingState, decision.ResultingVersion);
}

public sealed class PublishUnambiguousRoutesPolicy
{
    public PublishUnambiguousRoutesDecision OneOriginPublishingAssemblesDeterministicAssets(
        PublishUnambiguousRoutesRecord record,
        PublishUnambiguousRoutesRequest request) =>
        PublishUnambiguousRoutesDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-MKTG-004", record.ToState(), request.ToInput()));

    public PublishUnambiguousRoutesDecision RequestRoutingProtectsEveryRuntimeOwner(
        PublishUnambiguousRoutesRecord record,
        PublishUnambiguousRoutesRequest request) =>
        PublishUnambiguousRoutesDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-MKTG-005", record.ToState(), request.ToInput()));

    public PublishUnambiguousRoutesDecision PublicToApplicationNavigationIsDeploymentConfigurable(
        PublishUnambiguousRoutesRecord record,
        PublishUnambiguousRoutesRequest request) =>
        PublishUnambiguousRoutesDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-MKTG-006", record.ToState(), request.ToInput()));
}

public static class PublishUnambiguousRoutesDescriptor
{
    public const string Subsystem = "marketing-public-web";
    public const string Slug = "publish-unambiguous-routes";
    public const string Title = "Publish marketing and application routes without ambiguity";

    public static IReadOnlyList<FeatureOperationDescriptor> Operations { get; } =
    [
        new("L2-MKTG-004", "OneOriginPublishingAssemblesDeterministicAssets"),
        new("L2-MKTG-005", "RequestRoutingProtectsEveryRuntimeOwner"),
        new("L2-MKTG-006", "PublicToApplicationNavigationIsDeploymentConfigurable")
    ];
}
