// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;

namespace CommunityStarter.Domain.GeneratedFeatures;

public sealed record ReproduceCleanCheckoutRequest(
    Guid SubjectId,
    string Action,
    long ExpectedVersion,
    Guid? CommunityId,
    IReadOnlyDictionary<string, string> Values)
{
    public FeatureInput ToInput() => new(SubjectId, Action, ExpectedVersion, CommunityId, Values);
}

public sealed record ReproduceCleanCheckoutRecord(
    Guid Id,
    Guid? CommunityId,
    string State,
    long Version,
    bool IsAuthorized,
    bool IsAvailable)
{
    public FeatureState ToState() => new(Id, CommunityId, State, Version, IsAuthorized, IsAvailable);
}

public sealed record ReproduceCleanCheckoutDecision(
    string RequirementId,
    FeatureDecisionKind Kind,
    string Code,
    string ResultingState,
    long ResultingVersion)
{
    public bool IsAccepted => Kind == FeatureDecisionKind.Accepted;

    public static ReproduceCleanCheckoutDecision From(FeatureDecision decision) =>
        new(decision.RequirementId, decision.Kind, decision.Code, decision.ResultingState, decision.ResultingVersion);
}

public sealed class ReproduceCleanCheckoutPolicy
{
    public ReproduceCleanCheckoutDecision PinAndValidateDevelopmentToolchains(
        ReproduceCleanCheckoutRecord record,
        ReproduceCleanCheckoutRequest request) =>
        ReproduceCleanCheckoutDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-STRT-001", record.ToState(), request.ToInput()));

    public ReproduceCleanCheckoutDecision ExposeCanonicalRepositoryCommands(
        ReproduceCleanCheckoutRecord record,
        ReproduceCleanCheckoutRequest request) =>
        ReproduceCleanCheckoutDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-STRT-002", record.ToState(), request.ToInput()));

    public ReproduceCleanCheckoutDecision ProvisionRepeatableLocalDependencies(
        ReproduceCleanCheckoutRecord record,
        ReproduceCleanCheckoutRequest request) =>
        ReproduceCleanCheckoutDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-STRT-003", record.ToState(), request.ToInput()));

    public ReproduceCleanCheckoutDecision ValidateEnvironmentConfigurationAndSecrets(
        ReproduceCleanCheckoutRecord record,
        ReproduceCleanCheckoutRequest request) =>
        ReproduceCleanCheckoutDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-STRT-004", record.ToState(), request.ToInput()));
}

public static class ReproduceCleanCheckoutDescriptor
{
    public const string Subsystem = "starter-experience";
    public const string Slug = "reproduce-clean-checkout";
    public const string Title = "A clean checkout is reproducible";

    public static IReadOnlyList<FeatureOperationDescriptor> Operations { get; } =
    [
        new("L2-STRT-001", "PinAndValidateDevelopmentToolchains"),
        new("L2-STRT-002", "ExposeCanonicalRepositoryCommands"),
        new("L2-STRT-003", "ProvisionRepeatableLocalDependencies"),
        new("L2-STRT-004", "ValidateEnvironmentConfigurationAndSecrets")
    ];
}
