// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;

namespace CommunityStarter.Domain.GeneratedFeatures;

public sealed record ReproduceLocalChangeHygieneRequest(
    Guid SubjectId,
    string Action,
    long ExpectedVersion,
    Guid? CommunityId,
    IReadOnlyDictionary<string, string> Values)
{
    public FeatureInput ToInput() => new(SubjectId, Action, ExpectedVersion, CommunityId, Values);
}

public sealed record ReproduceLocalChangeHygieneRecord(
    Guid Id,
    Guid? CommunityId,
    string State,
    long Version,
    bool IsAuthorized,
    bool IsAvailable)
{
    public FeatureState ToState() => new(Id, CommunityId, State, Version, IsAuthorized, IsAvailable);
}

public sealed record ReproduceLocalChangeHygieneDecision(
    string RequirementId,
    FeatureDecisionKind Kind,
    string Code,
    string ResultingState,
    long ResultingVersion)
{
    public bool IsAccepted => Kind == FeatureDecisionKind.Accepted;

    public static ReproduceLocalChangeHygieneDecision From(FeatureDecision decision) =>
        new(decision.RequirementId, decision.Kind, decision.Code, decision.ResultingState, decision.ResultingVersion);
}

public sealed class ReproduceLocalChangeHygienePolicy
{
    public ReproduceLocalChangeHygieneDecision CanonicalRestoreBuildTestAndE2eCommandsWorkCleanly(
        ReproduceLocalChangeHygieneRecord record,
        ReproduceLocalChangeHygieneRequest request) =>
        ReproduceLocalChangeHygieneDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-QUAL-008", record.ToState(), request.ToInput()));

    public ReproduceLocalChangeHygieneDecision RepositoryFormattingAndTrackedArtifactsAreGoverned(
        ReproduceLocalChangeHygieneRecord record,
        ReproduceLocalChangeHygieneRequest request) =>
        ReproduceLocalChangeHygieneDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-QUAL-009", record.ToState(), request.ToInput()));

    public ReproduceLocalChangeHygieneDecision IterationStartsNarrowAndEndsWithEveryRequiredGate(
        ReproduceLocalChangeHygieneRecord record,
        ReproduceLocalChangeHygieneRequest request) =>
        ReproduceLocalChangeHygieneDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-QUAL-010", record.ToState(), request.ToInput()));

    public ReproduceLocalChangeHygieneDecision DatabaseMarketingDeploymentAndDocumentationChangesHaveSpecializedChecks(
        ReproduceLocalChangeHygieneRecord record,
        ReproduceLocalChangeHygieneRequest request) =>
        ReproduceLocalChangeHygieneDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-QUAL-011", record.ToState(), request.ToInput()));
}

public static class ReproduceLocalChangeHygieneDescriptor
{
    public const string Subsystem = "delivery-quality";
    public const string Slug = "reproduce-local-change-hygiene";
    public const string Title = "Make local development and change hygiene reproducible";

    public static IReadOnlyList<FeatureOperationDescriptor> Operations { get; } =
    [
        new("L2-QUAL-008", "CanonicalRestoreBuildTestAndE2eCommandsWorkCleanly"),
        new("L2-QUAL-009", "RepositoryFormattingAndTrackedArtifactsAreGoverned"),
        new("L2-QUAL-010", "IterationStartsNarrowAndEndsWithEveryRequiredGate"),
        new("L2-QUAL-011", "DatabaseMarketingDeploymentAndDocumentationChangesHaveSpecializedChecks")
    ];
}
