// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;

namespace CommunityStarter.Domain.GeneratedFeatures;

public sealed record RespondToIncidentsRequest(
    Guid SubjectId,
    string Action,
    long ExpectedVersion,
    Guid? CommunityId,
    IReadOnlyDictionary<string, string> Values)
{
    public FeatureInput ToInput() => new(SubjectId, Action, ExpectedVersion, CommunityId, Values);
}

public sealed record RespondToIncidentsRecord(
    Guid Id,
    Guid? CommunityId,
    string State,
    long Version,
    bool IsAuthorized,
    bool IsAvailable)
{
    public FeatureState ToState() => new(Id, CommunityId, State, Version, IsAuthorized, IsAvailable);
}

public sealed record RespondToIncidentsDecision(
    string RequirementId,
    FeatureDecisionKind Kind,
    string Code,
    string ResultingState,
    long ResultingVersion)
{
    public bool IsAccepted => Kind == FeatureDecisionKind.Accepted;

    public static RespondToIncidentsDecision From(FeatureDecision decision) =>
        new(decision.RequirementId, decision.Kind, decision.Code, decision.ResultingState, decision.ResultingVersion);
}

public sealed class RespondToIncidentsPolicy
{
    public RespondToIncidentsDecision RouteActionableAlertsToAnOwner(
        RespondToIncidentsRecord record,
        RespondToIncidentsRequest request) =>
        RespondToIncidentsDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-OPER-009", record.ToState(), request.ToInput()));

    public RespondToIncidentsDecision RunAndReviewIncidentsConsistently(
        RespondToIncidentsRecord record,
        RespondToIncidentsRequest request) =>
        RespondToIncidentsDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-OPER-010", record.ToState(), request.ToInput()));

    public RespondToIncidentsDecision MaintainExecutableOperationalRunbooks(
        RespondToIncidentsRecord record,
        RespondToIncidentsRequest request) =>
        RespondToIncidentsDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-OPER-011", record.ToState(), request.ToInput()));
}

public static class RespondToIncidentsDescriptor
{
    public const string Subsystem = "operations-reliability";
    public const string Slug = "respond-to-incidents";
    public const string Title = "Incidents have owned detection and response";

    public static IReadOnlyList<FeatureOperationDescriptor> Operations { get; } =
    [
        new("L2-OPER-009", "RouteActionableAlertsToAnOwner"),
        new("L2-OPER-010", "RunAndReviewIncidentsConsistently"),
        new("L2-OPER-011", "MaintainExecutableOperationalRunbooks")
    ];
}
