// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;

namespace CommunityStarter.Domain.GeneratedFeatures;

public sealed record RespectCommunityContextRequest(
    Guid SubjectId,
    string Action,
    long ExpectedVersion,
    Guid? CommunityId,
    IReadOnlyDictionary<string, string> Values)
{
    public FeatureInput ToInput() => new(SubjectId, Action, ExpectedVersion, CommunityId, Values);
}

public sealed record RespectCommunityContextRecord(
    Guid Id,
    Guid? CommunityId,
    string State,
    long Version,
    bool IsAuthorized,
    bool IsAvailable)
{
    public FeatureState ToState() => new(Id, CommunityId, State, Version, IsAuthorized, IsAvailable);
}

public sealed record RespectCommunityContextDecision(
    string RequirementId,
    FeatureDecisionKind Kind,
    string Code,
    string ResultingState,
    long ResultingVersion)
{
    public bool IsAccepted => Kind == FeatureDecisionKind.Accepted;

    public static RespectCommunityContextDecision From(FeatureDecision decision) =>
        new(decision.RequirementId, decision.Kind, decision.Code, decision.ResultingState, decision.ResultingVersion);
}

public sealed class RespectCommunityContextPolicy
{
    public RespectCommunityContextDecision RenderCommunityContextSafely(
        RespectCommunityContextRecord record,
        RespectCommunityContextRequest request) =>
        RespectCommunityContextDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-PROF-011", record.ToState(), request.ToInput()));

    public RespectCommunityContextDecision RetireProfileDataSafely(
        RespectCommunityContextRecord record,
        RespectCommunityContextRequest request) =>
        RespectCommunityContextDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-PROF-012", record.ToState(), request.ToInput()));

    public RespectCommunityContextDecision ListAPrivacySafeMemberDirectory(
        RespectCommunityContextRecord record,
        RespectCommunityContextRequest request) =>
        RespectCommunityContextDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-PROF-014", record.ToState(), request.ToInput()));
}

public static class RespectCommunityContextDescriptor
{
    public const string Subsystem = "profiles-relationships";
    public const string Slug = "respect-community-context";
    public const string Title = "Respect Community context";

    public static IReadOnlyList<FeatureOperationDescriptor> Operations { get; } =
    [
        new("L2-PROF-011", "RenderCommunityContextSafely"),
        new("L2-PROF-012", "RetireProfileDataSafely"),
        new("L2-PROF-014", "ListAPrivacySafeMemberDirectory")
    ];
}
