// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;

namespace CommunityStarter.Domain.GeneratedFeatures;

public sealed record ReviewSafetyDecisionsRequest(
    Guid SubjectId,
    string Action,
    long ExpectedVersion,
    Guid? CommunityId,
    IReadOnlyDictionary<string, string> Values)
{
    public FeatureInput ToInput() => new(SubjectId, Action, ExpectedVersion, CommunityId, Values);
}

public sealed record ReviewSafetyDecisionsRecord(
    Guid Id,
    Guid? CommunityId,
    string State,
    long Version,
    bool IsAuthorized,
    bool IsAvailable)
{
    public FeatureState ToState() => new(Id, CommunityId, State, Version, IsAuthorized, IsAvailable);
}

public sealed record ReviewSafetyDecisionsDecision(
    string RequirementId,
    FeatureDecisionKind Kind,
    string Code,
    string ResultingState,
    long ResultingVersion)
{
    public bool IsAccepted => Kind == FeatureDecisionKind.Accepted;

    public static ReviewSafetyDecisionsDecision From(FeatureDecision decision) =>
        new(decision.RequirementId, decision.Kind, decision.Code, decision.ResultingState, decision.ResultingVersion);
}

public sealed class ReviewSafetyDecisionsPolicy
{
    public ReviewSafetyDecisionsDecision AdjudicateEligibleAppealsAndRepairState(
        ReviewSafetyDecisionsRecord record,
        ReviewSafetyDecisionsRequest request) =>
        ReviewSafetyDecisionsDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-SAFE-010", record.ToState(), request.ToInput()));

    public ReviewSafetyDecisionsDecision AuditAndMeasureSafetyOutcomes(
        ReviewSafetyDecisionsRecord record,
        ReviewSafetyDecisionsRequest request) =>
        ReviewSafetyDecisionsDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-SAFE-012", record.ToState(), request.ToInput()));
}

public static class ReviewSafetyDecisionsDescriptor
{
    public const string Subsystem = "moderation-trust-safety";
    public const string Slug = "review-safety-decisions";
    public const string Title = "Reviewable and operable safety decisions";

    public static IReadOnlyList<FeatureOperationDescriptor> Operations { get; } =
    [
        new("L2-SAFE-010", "AdjudicateEligibleAppealsAndRepairState"),
        new("L2-SAFE-012", "AuditAndMeasureSafetyOutcomes")
    ];
}
