// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;

namespace CommunityStarter.Domain.GeneratedFeatures;

public sealed record SearchAuthorizedContentRequest(
    Guid SubjectId,
    string Action,
    long ExpectedVersion,
    Guid? CommunityId,
    IReadOnlyDictionary<string, string> Values)
{
    public FeatureInput ToInput() => new(SubjectId, Action, ExpectedVersion, CommunityId, Values);
}

public sealed record SearchAuthorizedContentRecord(
    Guid Id,
    Guid? CommunityId,
    string State,
    long Version,
    bool IsAuthorized,
    bool IsAvailable)
{
    public FeatureState ToState() => new(Id, CommunityId, State, Version, IsAuthorized, IsAvailable);
}

public sealed record SearchAuthorizedContentDecision(
    string RequirementId,
    FeatureDecisionKind Kind,
    string Code,
    string ResultingState,
    long ResultingVersion)
{
    public bool IsAccepted => Kind == FeatureDecisionKind.Accepted;

    public static SearchAuthorizedContentDecision From(FeatureDecision decision) =>
        new(decision.RequirementId, decision.Kind, decision.Code, decision.ResultingState, decision.ResultingVersion);
}

public sealed class SearchAuthorizedContentPolicy
{
    public SearchAuthorizedContentDecision SearchEligibleRecords(
        SearchAuthorizedContentRecord record,
        SearchAuthorizedContentRequest request) =>
        SearchAuthorizedContentDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-DISC-005", record.ToState(), request.ToInput()));

    public SearchAuthorizedContentDecision FilterAndPageSearchResults(
        SearchAuthorizedContentRecord record,
        SearchAuthorizedContentRequest request) =>
        SearchAuthorizedContentDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-DISC-006", record.ToState(), request.ToInput()));

    public SearchAuthorizedContentDecision RemoveStaleSearchResults(
        SearchAuthorizedContentRecord record,
        SearchAuthorizedContentRequest request) =>
        SearchAuthorizedContentDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-DISC-007", record.ToState(), request.ToInput()));
}

public static class SearchAuthorizedContentDescriptor
{
    public const string Subsystem = "feeds-search-engagement";
    public const string Slug = "search-authorized-content";
    public const string Title = "Search authorized content";

    public static IReadOnlyList<FeatureOperationDescriptor> Operations { get; } =
    [
        new("L2-DISC-005", "SearchEligibleRecords"),
        new("L2-DISC-006", "FilterAndPageSearchResults"),
        new("L2-DISC-007", "RemoveStaleSearchResults")
    ];
}
