// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;

namespace CommunityStarter.Domain.GeneratedFeatures;

public sealed record TraceArchitectureToProductTruthRequest(
    Guid SubjectId,
    string Action,
    long ExpectedVersion,
    Guid? CommunityId,
    IReadOnlyDictionary<string, string> Values)
{
    public FeatureInput ToInput() => new(SubjectId, Action, ExpectedVersion, CommunityId, Values);
}

public sealed record TraceArchitectureToProductTruthRecord(
    Guid Id,
    Guid? CommunityId,
    string State,
    long Version,
    bool IsAuthorized,
    bool IsAvailable)
{
    public FeatureState ToState() => new(Id, CommunityId, State, Version, IsAuthorized, IsAvailable);
}

public sealed record TraceArchitectureToProductTruthDecision(
    string RequirementId,
    FeatureDecisionKind Kind,
    string Code,
    string ResultingState,
    long ResultingVersion)
{
    public bool IsAccepted => Kind == FeatureDecisionKind.Accepted;

    public static TraceArchitectureToProductTruthDecision From(FeatureDecision decision) =>
        new(decision.RequirementId, decision.Kind, decision.Code, decision.ResultingState, decision.ResultingVersion);
}

public sealed class TraceArchitectureToProductTruthPolicy
{
    public TraceArchitectureToProductTruthDecision VocabularyInvariantsAndVerticalSlicesDriveImplementation(
        TraceArchitectureToProductTruthRecord record,
        TraceArchitectureToProductTruthRequest request) =>
        TraceArchitectureToProductTruthDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-ARCH-015", record.ToState(), request.ToInput()));

    public TraceArchitectureToProductTruthDecision ConsequentialDecisionsAndDocumentationRemainTraceable(
        TraceArchitectureToProductTruthRecord record,
        TraceArchitectureToProductTruthRequest request) =>
        TraceArchitectureToProductTruthDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-ARCH-016", record.ToState(), request.ToInput()));
}

public static class TraceArchitectureToProductTruthDescriptor
{
    public const string Subsystem = "platform-architecture";
    public const string Slug = "trace-architecture-to-product-truth";
    public const string Title = "Make architecture traceable to product truth";

    public static IReadOnlyList<FeatureOperationDescriptor> Operations { get; } =
    [
        new("L2-ARCH-015", "VocabularyInvariantsAndVerticalSlicesDriveImplementation"),
        new("L2-ARCH-016", "ConsequentialDecisionsAndDocumentationRemainTraceable")
    ];
}
