// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;

namespace CommunityStarter.Domain.GeneratedFeatures;

public sealed record VerifyPublicDeploymentRequest(
    Guid SubjectId,
    string Action,
    long ExpectedVersion,
    Guid? CommunityId,
    IReadOnlyDictionary<string, string> Values)
{
    public FeatureInput ToInput() => new(SubjectId, Action, ExpectedVersion, CommunityId, Values);
}

public sealed record VerifyPublicDeploymentRecord(
    Guid Id,
    Guid? CommunityId,
    string State,
    long Version,
    bool IsAuthorized,
    bool IsAvailable)
{
    public FeatureState ToState() => new(Id, CommunityId, State, Version, IsAuthorized, IsAvailable);
}

public sealed record VerifyPublicDeploymentDecision(
    string RequirementId,
    FeatureDecisionKind Kind,
    string Code,
    string ResultingState,
    long ResultingVersion)
{
    public bool IsAccepted => Kind == FeatureDecisionKind.Accepted;

    public static VerifyPublicDeploymentDecision From(FeatureDecision decision) =>
        new(decision.RequirementId, decision.Kind, decision.Code, decision.ResultingState, decision.ResultingVersion);
}

public sealed class VerifyPublicDeploymentPolicy
{
    public VerifyPublicDeploymentDecision PublishedPublicBehaviorIsReleaseBlockingEvidence(
        VerifyPublicDeploymentRecord record,
        VerifyPublicDeploymentRequest request) =>
        VerifyPublicDeploymentDecision.From(FeaturePolicyEvaluator.Evaluate(
            "L2-MKTG-012", record.ToState(), request.ToInput()));
}

public static class VerifyPublicDeploymentDescriptor
{
    public const string Subsystem = "marketing-public-web";
    public const string Slug = "verify-public-deployment";
    public const string Title = "Evolve and verify public deployment safely";

    public static IReadOnlyList<FeatureOperationDescriptor> Operations { get; } =
    [
        new("L2-MKTG-012", "PublishedPublicBehaviorIsReleaseBlockingEvidence")
    ];
}
