// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;
using CommunityStarter.Domain.GeneratedFeatures;

namespace CommunityStarter.Application.GeneratedFeatures;

public interface IAdministerCommunitySettingsRepository
{
    ValueTask<AdministerCommunitySettingsRecord?> LoadAsync(
        Guid subjectId,
        Guid? communityId,
        CancellationToken cancellationToken);

    ValueTask CommitAsync(
        AdministerCommunitySettingsRecord current,
        AdministerCommunitySettingsDecision decision,
        CancellationToken cancellationToken);
}

public sealed class AdministerCommunitySettingsProjector(IFeatureProjectionSink sink)
{
    public ValueTask EnqueueAsync(
        AdministerCommunitySettingsRequest request,
        AdministerCommunitySettingsDecision decision,
        CancellationToken cancellationToken) =>
        sink.EnqueueAsync(
            AdministerCommunitySettingsDescriptor.Slug,
            request.SubjectId,
            request.CommunityId,
            decision.RequirementId,
            decision.ResultingVersion,
            cancellationToken);
}

public sealed class AdministerCommunitySettingsHandler(
    IAdministerCommunitySettingsRepository repository,
    AdministerCommunitySettingsProjector projector)
{
    public async ValueTask<AdministerCommunitySettingsDecision> HandleAsync(
        AdministerCommunitySettingsRequest request,
        CancellationToken cancellationToken)
    {
        var record = await repository.LoadAsync(
            request.SubjectId,
            request.CommunityId,
            cancellationToken) ?? new(
                request.SubjectId,
                request.CommunityId,
                "missing",
                request.ExpectedVersion,
                IsAuthorized: false,
                IsAvailable: false);
        var policy = new AdministerCommunitySettingsPolicy();
        var decision = request.Action switch
        {
            "ChangeVersionedCommunitySettings" => policy.ChangeVersionedCommunitySettings(record, request),
            "DelegateRolesWithoutPrivilegeEscalation" => policy.DelegateRolesWithoutPrivilegeEscalation(record, request),
            "PreviewAndExecuteHighImpactOperations" => policy.PreviewAndExecuteHighImpactOperations(record, request),
            _ => new(
                "unknown",
                FeatureDecisionKind.Invalid,
                "unknown_feature_action",
                record.State,
                record.Version)
        };

        if (!decision.IsAccepted)
        {
            return decision;
        }

        await repository.CommitAsync(record, decision, cancellationToken);
        await projector.EnqueueAsync(request, decision, cancellationToken);
        return decision;
    }
}
