// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;
using CommunityStarter.Domain.GeneratedFeatures;

namespace CommunityStarter.Application.GeneratedFeatures;

public interface IAuthorizeConversationAccessRepository
{
    ValueTask<AuthorizeConversationAccessRecord?> LoadAsync(
        Guid subjectId,
        Guid? communityId,
        CancellationToken cancellationToken);

    ValueTask CommitAsync(
        AuthorizeConversationAccessRecord current,
        AuthorizeConversationAccessDecision decision,
        CancellationToken cancellationToken);
}

public sealed class AuthorizeConversationAccessProjector(IFeatureProjectionSink sink)
{
    public ValueTask EnqueueAsync(
        AuthorizeConversationAccessRequest request,
        AuthorizeConversationAccessDecision decision,
        CancellationToken cancellationToken) =>
        sink.EnqueueAsync(
            AuthorizeConversationAccessDescriptor.Slug,
            request.SubjectId,
            request.CommunityId,
            decision.RequirementId,
            decision.ResultingVersion,
            cancellationToken);
}

public sealed class AuthorizeConversationAccessHandler(
    IAuthorizeConversationAccessRepository repository,
    AuthorizeConversationAccessProjector projector)
{
    public async ValueTask<AuthorizeConversationAccessDecision> HandleAsync(
        AuthorizeConversationAccessRequest request,
        CancellationToken cancellationToken)
    {
        var record = await repository.LoadAsync(
            request.SubjectId,
            request.CommunityId,
            cancellationToken) ?? new(
                request.SubjectId,
                request.CommunityId,
                "missing",
                request.ExpectedVersion,
                IsAuthorized: false,
                IsAvailable: false);
        var policy = new AuthorizeConversationAccessPolicy();
        var decision = request.Action switch
        {
            "StartAnAuthorizedConversation" => policy.StartAnAuthorizedConversation(record, request),
            "EnforceMessageRequestAndBlockPolicy" => policy.EnforceMessageRequestAndBlockPolicy(record, request),
            "EndAndReEnterDirectConversationsDeterministically" => policy.EndAndReEnterDirectConversationsDeterministically(record, request),
            _ => new(
                "unknown",
                FeatureDecisionKind.Invalid,
                "unknown_feature_action",
                record.State,
                record.Version)
        };

        if (!decision.IsAccepted)
        {
            return decision;
        }

        await repository.CommitAsync(record, decision, cancellationToken);
        await projector.EnqueueAsync(request, decision, cancellationToken);
        return decision;
    }
}
