// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;
using CommunityStarter.Domain.GeneratedFeatures;

namespace CommunityStarter.Application.GeneratedFeatures;

public interface ICompleteResumableOnboardingRepository
{
    ValueTask<CompleteResumableOnboardingRecord?> LoadAsync(
        Guid subjectId,
        Guid? communityId,
        CancellationToken cancellationToken);

    ValueTask CommitAsync(
        CompleteResumableOnboardingRecord current,
        CompleteResumableOnboardingDecision decision,
        CancellationToken cancellationToken);
}

public sealed class CompleteResumableOnboardingProjector(IFeatureProjectionSink sink)
{
    public ValueTask EnqueueAsync(
        CompleteResumableOnboardingRequest request,
        CompleteResumableOnboardingDecision decision,
        CancellationToken cancellationToken) =>
        sink.EnqueueAsync(
            CompleteResumableOnboardingDescriptor.Slug,
            request.SubjectId,
            request.CommunityId,
            decision.RequirementId,
            decision.ResultingVersion,
            cancellationToken);
}

public sealed class CompleteResumableOnboardingHandler(
    ICompleteResumableOnboardingRepository repository,
    CompleteResumableOnboardingProjector projector)
{
    public async ValueTask<CompleteResumableOnboardingDecision> HandleAsync(
        CompleteResumableOnboardingRequest request,
        CancellationToken cancellationToken)
    {
        var record = await repository.LoadAsync(
            request.SubjectId,
            request.CommunityId,
            cancellationToken) ?? new(
                request.SubjectId,
                request.CommunityId,
                "missing",
                request.ExpectedVersion,
                IsAuthorized: false,
                IsAvailable: false);
        var policy = new CompleteResumableOnboardingPolicy();
        var decision = request.Action switch
        {
            "StartAndResumeOnboarding" => policy.StartAndResumeOnboarding(record, request),
            "CompleteRequiredSteps" => policy.CompleteRequiredSteps(record, request),
            "ContinueFromAnInvitation" => policy.ContinueFromAnInvitation(record, request),
            _ => new(
                "unknown",
                FeatureDecisionKind.Invalid,
                "unknown_feature_action",
                record.State,
                record.Version)
        };

        if (!decision.IsAccepted)
        {
            return decision;
        }

        await repository.CommitAsync(record, decision, cancellationToken);
        await projector.EnqueueAsync(request, decision, cancellationToken);
        return decision;
    }
}
