// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;
using CommunityStarter.Domain.GeneratedFeatures;

namespace CommunityStarter.Application.GeneratedFeatures;

public interface IControlProductionChangeRepository
{
    ValueTask<ControlProductionChangeRecord?> LoadAsync(
        Guid subjectId,
        Guid? communityId,
        CancellationToken cancellationToken);

    ValueTask CommitAsync(
        ControlProductionChangeRecord current,
        ControlProductionChangeDecision decision,
        CancellationToken cancellationToken);
}

public sealed class ControlProductionChangeProjector(IFeatureProjectionSink sink)
{
    public ValueTask EnqueueAsync(
        ControlProductionChangeRequest request,
        ControlProductionChangeDecision decision,
        CancellationToken cancellationToken) =>
        sink.EnqueueAsync(
            ControlProductionChangeDescriptor.Slug,
            request.SubjectId,
            request.CommunityId,
            decision.RequirementId,
            decision.ResultingVersion,
            cancellationToken);
}

public sealed class ControlProductionChangeHandler(
    IControlProductionChangeRepository repository,
    ControlProductionChangeProjector projector)
{
    public async ValueTask<ControlProductionChangeDecision> HandleAsync(
        ControlProductionChangeRequest request,
        CancellationToken cancellationToken)
    {
        var record = await repository.LoadAsync(
            request.SubjectId,
            request.CommunityId,
            cancellationToken) ?? new(
                request.SubjectId,
                request.CommunityId,
                "missing",
                request.ExpectedVersion,
                IsAuthorized: false,
                IsAvailable: false);
        var policy = new ControlProductionChangePolicy();
        var decision = request.Action switch
        {
            "OperateMigrationsAndBackfillsSafely" => policy.OperateMigrationsAndBackfillsSafely(record, request),
            "OperateDurableJobQueues" => policy.OperateDurableJobQueues(record, request),
            _ => new(
                "unknown",
                FeatureDecisionKind.Invalid,
                "unknown_feature_action",
                record.State,
                record.Version)
        };

        if (!decision.IsAccepted)
        {
            return decision;
        }

        await repository.CommitAsync(record, decision, cancellationToken);
        await projector.EnqueueAsync(request, decision, cancellationToken);
        return decision;
    }
}
