// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;
using CommunityStarter.Domain.GeneratedFeatures;

namespace CommunityStarter.Application.GeneratedFeatures;

public interface IControlPlatformConfigurationRepository
{
    ValueTask<ControlPlatformConfigurationRecord?> LoadAsync(
        Guid subjectId,
        Guid? communityId,
        CancellationToken cancellationToken);

    ValueTask CommitAsync(
        ControlPlatformConfigurationRecord current,
        ControlPlatformConfigurationDecision decision,
        CancellationToken cancellationToken);
}

public sealed class ControlPlatformConfigurationProjector(IFeatureProjectionSink sink)
{
    public ValueTask EnqueueAsync(
        ControlPlatformConfigurationRequest request,
        ControlPlatformConfigurationDecision decision,
        CancellationToken cancellationToken) =>
        sink.EnqueueAsync(
            ControlPlatformConfigurationDescriptor.Slug,
            request.SubjectId,
            request.CommunityId,
            decision.RequirementId,
            decision.ResultingVersion,
            cancellationToken);
}

public sealed class ControlPlatformConfigurationHandler(
    IControlPlatformConfigurationRepository repository,
    ControlPlatformConfigurationProjector projector)
{
    public async ValueTask<ControlPlatformConfigurationDecision> HandleAsync(
        ControlPlatformConfigurationRequest request,
        CancellationToken cancellationToken)
    {
        var record = await repository.LoadAsync(
            request.SubjectId,
            request.CommunityId,
            cancellationToken) ?? new(
                request.SubjectId,
                request.CommunityId,
                "missing",
                request.ExpectedVersion,
                IsAuthorized: false,
                IsAvailable: false);
        var policy = new ControlPlatformConfigurationPolicy();
        var decision = request.Action switch
        {
            "PreserveConfigurationHistoryAndRollback" => policy.PreserveConfigurationHistoryAndRollback(record, request),
            "GovernFeatureFlagsAndKillSwitches" => policy.GovernFeatureFlagsAndKillSwitches(record, request),
            _ => new(
                "unknown",
                FeatureDecisionKind.Invalid,
                "unknown_feature_action",
                record.State,
                record.Version)
        };

        if (!decision.IsAccepted)
        {
            return decision;
        }

        await repository.CommitAsync(record, decision, cancellationToken);
        await projector.EnqueueAsync(request, decision, cancellationToken);
        return decision;
    }
}
