// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;
using CommunityStarter.Domain.GeneratedFeatures;

namespace CommunityStarter.Application.GeneratedFeatures;

public interface IControlRecipientAttentionRepository
{
    ValueTask<ControlRecipientAttentionRecord?> LoadAsync(
        Guid subjectId,
        Guid? communityId,
        CancellationToken cancellationToken);

    ValueTask CommitAsync(
        ControlRecipientAttentionRecord current,
        ControlRecipientAttentionDecision decision,
        CancellationToken cancellationToken);
}

public sealed class ControlRecipientAttentionProjector(IFeatureProjectionSink sink)
{
    public ValueTask EnqueueAsync(
        ControlRecipientAttentionRequest request,
        ControlRecipientAttentionDecision decision,
        CancellationToken cancellationToken) =>
        sink.EnqueueAsync(
            ControlRecipientAttentionDescriptor.Slug,
            request.SubjectId,
            request.CommunityId,
            decision.RequirementId,
            decision.ResultingVersion,
            cancellationToken);
}

public sealed class ControlRecipientAttentionHandler(
    IControlRecipientAttentionRepository repository,
    ControlRecipientAttentionProjector projector)
{
    public async ValueTask<ControlRecipientAttentionDecision> HandleAsync(
        ControlRecipientAttentionRequest request,
        CancellationToken cancellationToken)
    {
        var record = await repository.LoadAsync(
            request.SubjectId,
            request.CommunityId,
            cancellationToken) ?? new(
                request.SubjectId,
                request.CommunityId,
                "missing",
                request.ExpectedVersion,
                IsAuthorized: false,
                IsAvailable: false);
        var policy = new ControlRecipientAttentionPolicy();
        var decision = request.Action switch
        {
            "ApplyNotificationPreferences" => policy.ApplyNotificationPreferences(record, request),
            "LocalizeAccessiblePrivacySafeContent" => policy.LocalizeAccessiblePrivacySafeContent(record, request),
            _ => new(
                "unknown",
                FeatureDecisionKind.Invalid,
                "unknown_feature_action",
                record.State,
                record.Version)
        };

        if (!decision.IsAccepted)
        {
            return decision;
        }

        await repository.CommitAsync(record, decision, cancellationToken);
        await projector.EnqueueAsync(request, decision, cancellationToken);
        return decision;
    }
}
