// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;
using CommunityStarter.Domain.GeneratedFeatures;

namespace CommunityStarter.Application.GeneratedFeatures;

public interface IControlPlatformSupportAccessRepository
{
    ValueTask<ControlPlatformSupportAccessRecord?> LoadAsync(
        Guid subjectId,
        Guid? communityId,
        CancellationToken cancellationToken);

    ValueTask CommitAsync(
        ControlPlatformSupportAccessRecord current,
        ControlPlatformSupportAccessDecision decision,
        CancellationToken cancellationToken);
}

public sealed class ControlPlatformSupportAccessProjector(IFeatureProjectionSink sink)
{
    public ValueTask EnqueueAsync(
        ControlPlatformSupportAccessRequest request,
        ControlPlatformSupportAccessDecision decision,
        CancellationToken cancellationToken) =>
        sink.EnqueueAsync(
            ControlPlatformSupportAccessDescriptor.Slug,
            request.SubjectId,
            request.CommunityId,
            decision.RequirementId,
            decision.ResultingVersion,
            cancellationToken);
}

public sealed class ControlPlatformSupportAccessHandler(
    IControlPlatformSupportAccessRepository repository,
    ControlPlatformSupportAccessProjector projector)
{
    public async ValueTask<ControlPlatformSupportAccessDecision> HandleAsync(
        ControlPlatformSupportAccessRequest request,
        CancellationToken cancellationToken)
    {
        var record = await repository.LoadAsync(
            request.SubjectId,
            request.CommunityId,
            cancellationToken) ?? new(
                request.SubjectId,
                request.CommunityId,
                "missing",
                request.ExpectedVersion,
                IsAuthorized: false,
                IsAvailable: false);
        var policy = new ControlPlatformSupportAccessPolicy();
        var decision = request.Action switch
        {
            "SeparateOperatorResponsibilities" => policy.SeparateOperatorResponsibilities(record, request),
            "GrantPurposeBoundSupportAccess" => policy.GrantPurposeBoundSupportAccess(record, request),
            "MaintainSupportCaseLifecycle" => policy.MaintainSupportCaseLifecycle(record, request),
            "ProvisionAndPreserveOperatorAuthority" => policy.ProvisionAndPreserveOperatorAuthority(record, request),
            _ => new(
                "unknown",
                FeatureDecisionKind.Invalid,
                "unknown_feature_action",
                record.State,
                record.Version)
        };

        if (!decision.IsAccepted)
        {
            return decision;
        }

        await repository.CommitAsync(record, decision, cancellationToken);
        await projector.EnqueueAsync(request, decision, cancellationToken);
        return decision;
    }
}
