// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;
using CommunityStarter.Domain.GeneratedFeatures;

namespace CommunityStarter.Application.GeneratedFeatures;

public interface IDelegateCommunityAuthorityRepository
{
    ValueTask<DelegateCommunityAuthorityRecord?> LoadAsync(
        Guid subjectId,
        Guid? communityId,
        CancellationToken cancellationToken);

    ValueTask CommitAsync(
        DelegateCommunityAuthorityRecord current,
        DelegateCommunityAuthorityDecision decision,
        CancellationToken cancellationToken);
}

public sealed class DelegateCommunityAuthorityProjector(IFeatureProjectionSink sink)
{
    public ValueTask EnqueueAsync(
        DelegateCommunityAuthorityRequest request,
        DelegateCommunityAuthorityDecision decision,
        CancellationToken cancellationToken) =>
        sink.EnqueueAsync(
            DelegateCommunityAuthorityDescriptor.Slug,
            request.SubjectId,
            request.CommunityId,
            decision.RequirementId,
            decision.ResultingVersion,
            cancellationToken);
}

public sealed class DelegateCommunityAuthorityHandler(
    IDelegateCommunityAuthorityRepository repository,
    DelegateCommunityAuthorityProjector projector)
{
    public async ValueTask<DelegateCommunityAuthorityDecision> HandleAsync(
        DelegateCommunityAuthorityRequest request,
        CancellationToken cancellationToken)
    {
        var record = await repository.LoadAsync(
            request.SubjectId,
            request.CommunityId,
            cancellationToken) ?? new(
                request.SubjectId,
                request.CommunityId,
                "missing",
                request.ExpectedVersion,
                IsAuthorized: false,
                IsAvailable: false);
        var policy = new DelegateCommunityAuthorityPolicy();
        var decision = request.Action switch
        {
            "ManageRolesAndPermissions" => policy.ManageRolesAndPermissions(record, request),
            "AssignARoleSafely" => policy.AssignARoleSafely(record, request),
            "PreserveAdministrativeContinuity" => policy.PreserveAdministrativeContinuity(record, request),
            _ => new(
                "unknown",
                FeatureDecisionKind.Invalid,
                "unknown_feature_action",
                record.State,
                record.Version)
        };

        if (!decision.IsAccepted)
        {
            return decision;
        }

        await repository.CommitAsync(record, decision, cancellationToken);
        await projector.EnqueueAsync(request, decision, cancellationToken);
        return decision;
    }
}
