// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;
using CommunityStarter.Domain.GeneratedFeatures;

namespace CommunityStarter.Application.GeneratedFeatures;

public interface IDeliverDurableMessagesRepository
{
    ValueTask<DeliverDurableMessagesRecord?> LoadAsync(
        Guid subjectId,
        Guid? communityId,
        CancellationToken cancellationToken);

    ValueTask CommitAsync(
        DeliverDurableMessagesRecord current,
        DeliverDurableMessagesDecision decision,
        CancellationToken cancellationToken);
}

public sealed class DeliverDurableMessagesProjector(IFeatureProjectionSink sink)
{
    public ValueTask EnqueueAsync(
        DeliverDurableMessagesRequest request,
        DeliverDurableMessagesDecision decision,
        CancellationToken cancellationToken) =>
        sink.EnqueueAsync(
            DeliverDurableMessagesDescriptor.Slug,
            request.SubjectId,
            request.CommunityId,
            decision.RequirementId,
            decision.ResultingVersion,
            cancellationToken);
}

public sealed class DeliverDurableMessagesHandler(
    IDeliverDurableMessagesRepository repository,
    DeliverDurableMessagesProjector projector)
{
    public async ValueTask<DeliverDurableMessagesDecision> HandleAsync(
        DeliverDurableMessagesRequest request,
        CancellationToken cancellationToken)
    {
        var record = await repository.LoadAsync(
            request.SubjectId,
            request.CommunityId,
            cancellationToken) ?? new(
                request.SubjectId,
                request.CommunityId,
                "missing",
                request.ExpectedVersion,
                IsAuthorized: false,
                IsAvailable: false);
        var policy = new DeliverDurableMessagesPolicy();
        var decision = request.Action switch
        {
            "CommitOneValidatedMessage" => policy.CommitOneValidatedMessage(record, request),
            "PageMessagesAndTrackReadingPrivately" => policy.PageMessagesAndTrackReadingPrivately(record, request),
            "ApplyEditDeletionAndRetentionPolicy" => policy.ApplyEditDeletionAndRetentionPolicy(record, request),
            "ReportAMessageWithoutLosingEvidence" => policy.ReportAMessageWithoutLosingEvidence(record, request),
            _ => new(
                "unknown",
                FeatureDecisionKind.Invalid,
                "unknown_feature_action",
                record.State,
                record.Version)
        };

        if (!decision.IsAccepted)
        {
            return decision;
        }

        await repository.CommitAsync(record, decision, cancellationToken);
        await projector.EnqueueAsync(request, decision, cancellationToken);
        return decision;
    }
}
