// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;
using CommunityStarter.Domain.GeneratedFeatures;

namespace CommunityStarter.Application.GeneratedFeatures;

public interface IDeliverPrivateNotificationsRepository
{
    ValueTask<DeliverPrivateNotificationsRecord?> LoadAsync(
        Guid subjectId,
        Guid? communityId,
        CancellationToken cancellationToken);

    ValueTask CommitAsync(
        DeliverPrivateNotificationsRecord current,
        DeliverPrivateNotificationsDecision decision,
        CancellationToken cancellationToken);
}

public sealed class DeliverPrivateNotificationsProjector(IFeatureProjectionSink sink)
{
    public ValueTask EnqueueAsync(
        DeliverPrivateNotificationsRequest request,
        DeliverPrivateNotificationsDecision decision,
        CancellationToken cancellationToken) =>
        sink.EnqueueAsync(
            DeliverPrivateNotificationsDescriptor.Slug,
            request.SubjectId,
            request.CommunityId,
            decision.RequirementId,
            decision.ResultingVersion,
            cancellationToken);
}

public sealed class DeliverPrivateNotificationsHandler(
    IDeliverPrivateNotificationsRepository repository,
    DeliverPrivateNotificationsProjector projector)
{
    public async ValueTask<DeliverPrivateNotificationsDecision> HandleAsync(
        DeliverPrivateNotificationsRequest request,
        CancellationToken cancellationToken)
    {
        var record = await repository.LoadAsync(
            request.SubjectId,
            request.CommunityId,
            cancellationToken) ?? new(
                request.SubjectId,
                request.CommunityId,
                "missing",
                request.ExpectedVersion,
                IsAuthorized: false,
                IsAvailable: false);
        var policy = new DeliverPrivateNotificationsPolicy();
        var decision = request.Action switch
        {
            "CreateNotificationsAfterCommit" => policy.CreateNotificationsAfterCommit(record, request),
            "RecheckRecipientEligibility" => policy.RecheckRecipientEligibility(record, request),
            "MaintainAUsableNotificationInbox" => policy.MaintainAUsableNotificationInbox(record, request),
            _ => new(
                "unknown",
                FeatureDecisionKind.Invalid,
                "unknown_feature_action",
                record.State,
                record.Version)
        };

        if (!decision.IsAccepted)
        {
            return decision;
        }

        await repository.CommitAsync(record, decision, cancellationToken);
        await projector.EnqueueAsync(request, decision, cancellationToken);
        return decision;
    }
}
