// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;
using CommunityStarter.Domain.GeneratedFeatures;

namespace CommunityStarter.Application.GeneratedFeatures;

public interface IEnforceRelationshipSafetyRepository
{
    ValueTask<EnforceRelationshipSafetyRecord?> LoadAsync(
        Guid subjectId,
        Guid? communityId,
        CancellationToken cancellationToken);

    ValueTask CommitAsync(
        EnforceRelationshipSafetyRecord current,
        EnforceRelationshipSafetyDecision decision,
        CancellationToken cancellationToken);
}

public sealed class EnforceRelationshipSafetyProjector(IFeatureProjectionSink sink)
{
    public ValueTask EnqueueAsync(
        EnforceRelationshipSafetyRequest request,
        EnforceRelationshipSafetyDecision decision,
        CancellationToken cancellationToken) =>
        sink.EnqueueAsync(
            EnforceRelationshipSafetyDescriptor.Slug,
            request.SubjectId,
            request.CommunityId,
            decision.RequirementId,
            decision.ResultingVersion,
            cancellationToken);
}

public sealed class EnforceRelationshipSafetyHandler(
    IEnforceRelationshipSafetyRepository repository,
    EnforceRelationshipSafetyProjector projector)
{
    public async ValueTask<EnforceRelationshipSafetyDecision> HandleAsync(
        EnforceRelationshipSafetyRequest request,
        CancellationToken cancellationToken)
    {
        var record = await repository.LoadAsync(
            request.SubjectId,
            request.CommunityId,
            cancellationToken) ?? new(
                request.SubjectId,
                request.CommunityId,
                "missing",
                request.ExpectedVersion,
                IsAuthorized: false,
                IsAvailable: false);
        var policy = new EnforceRelationshipSafetyPolicy();
        var decision = request.Action switch
        {
            "BlockAnotherAccount" => policy.BlockAnotherAccount(record, request),
            "MuteAnotherAccount" => policy.MuteAnotherAccount(record, request),
            "ResolveBlockAndMutePrecedence" => policy.ResolveBlockAndMutePrecedence(record, request),
            "EnforceTheSharedCommunityBlockMatrix" => policy.EnforceTheSharedCommunityBlockMatrix(record, request),
            _ => new(
                "unknown",
                FeatureDecisionKind.Invalid,
                "unknown_feature_action",
                record.State,
                record.Version)
        };

        if (!decision.IsAccepted)
        {
            return decision;
        }

        await repository.CommitAsync(record, decision, cancellationToken);
        await projector.EnqueueAsync(request, decision, cancellationToken);
        return decision;
    }
}
