// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;
using CommunityStarter.Domain.GeneratedFeatures;

namespace CommunityStarter.Application.GeneratedFeatures;

public interface IEnforceSecureArtifactPromotionRepository
{
    ValueTask<EnforceSecureArtifactPromotionRecord?> LoadAsync(
        Guid subjectId,
        Guid? communityId,
        CancellationToken cancellationToken);

    ValueTask CommitAsync(
        EnforceSecureArtifactPromotionRecord current,
        EnforceSecureArtifactPromotionDecision decision,
        CancellationToken cancellationToken);
}

public sealed class EnforceSecureArtifactPromotionProjector(IFeatureProjectionSink sink)
{
    public ValueTask EnqueueAsync(
        EnforceSecureArtifactPromotionRequest request,
        EnforceSecureArtifactPromotionDecision decision,
        CancellationToken cancellationToken) =>
        sink.EnqueueAsync(
            EnforceSecureArtifactPromotionDescriptor.Slug,
            request.SubjectId,
            request.CommunityId,
            decision.RequirementId,
            decision.ResultingVersion,
            cancellationToken);
}

public sealed class EnforceSecureArtifactPromotionHandler(
    IEnforceSecureArtifactPromotionRepository repository,
    EnforceSecureArtifactPromotionProjector projector)
{
    public async ValueTask<EnforceSecureArtifactPromotionDecision> HandleAsync(
        EnforceSecureArtifactPromotionRequest request,
        CancellationToken cancellationToken)
    {
        var record = await repository.LoadAsync(
            request.SubjectId,
            request.CommunityId,
            cancellationToken) ?? new(
                request.SubjectId,
                request.CommunityId,
                "missing",
                request.ExpectedVersion,
                IsAuthorized: false,
                IsAvailable: false);
        var policy = new EnforceSecureArtifactPromotionPolicy();
        var decision = request.Action switch
        {
            "CIRestoresFormatsAnalyzesAndBuildsEveryStack" => policy.CIRestoresFormatsAnalyzesAndBuildsEveryStack(record, request),
            "CIRunsLayeredTestsAndValidatesSourceArtifacts" => policy.CIRunsLayeredTestsAndValidatesSourceArtifacts(record, request),
            "OneVerifiedArtifactIsPromotedWithProtectedCredentials" => policy.OneVerifiedArtifactIsPromotedWithProtectedCredentials(record, request),
            "DeploymentSmokeChecksReleaseCriticalBehavior" => policy.DeploymentSmokeChecksReleaseCriticalBehavior(record, request),
            "ProvisionEnvironmentsThroughReviewedInfrastructureCode" => policy.ProvisionEnvironmentsThroughReviewedInfrastructureCode(record, request),
            "IsolatePreviewAndNonProductionEnvironments" => policy.IsolatePreviewAndNonProductionEnvironments(record, request),
            _ => new(
                "unknown",
                FeatureDecisionKind.Invalid,
                "unknown_feature_action",
                record.State,
                record.Version)
        };

        if (!decision.IsAccepted)
        {
            return decision;
        }

        await repository.CommitAsync(record, decision, cancellationToken);
        await projector.EnqueueAsync(request, decision, cancellationToken);
        return decision;
    }
}
