// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;
using CommunityStarter.Domain.GeneratedFeatures;

namespace CommunityStarter.Application.GeneratedFeatures;

public interface IEnforceEventAccessRepository
{
    ValueTask<EnforceEventAccessRecord?> LoadAsync(
        Guid subjectId,
        Guid? communityId,
        CancellationToken cancellationToken);

    ValueTask CommitAsync(
        EnforceEventAccessRecord current,
        EnforceEventAccessDecision decision,
        CancellationToken cancellationToken);
}

public sealed class EnforceEventAccessProjector(IFeatureProjectionSink sink)
{
    public ValueTask EnqueueAsync(
        EnforceEventAccessRequest request,
        EnforceEventAccessDecision decision,
        CancellationToken cancellationToken) =>
        sink.EnqueueAsync(
            EnforceEventAccessDescriptor.Slug,
            request.SubjectId,
            request.CommunityId,
            decision.RequirementId,
            decision.ResultingVersion,
            cancellationToken);
}

public sealed class EnforceEventAccessHandler(
    IEnforceEventAccessRepository repository,
    EnforceEventAccessProjector projector)
{
    public async ValueTask<EnforceEventAccessDecision> HandleAsync(
        EnforceEventAccessRequest request,
        CancellationToken cancellationToken)
    {
        var record = await repository.LoadAsync(
            request.SubjectId,
            request.CommunityId,
            cancellationToken) ?? new(
                request.SubjectId,
                request.CommunityId,
                "missing",
                request.ExpectedVersion,
                IsAuthorized: false,
                IsAvailable: false);
        var policy = new EnforceEventAccessPolicy();
        var decision = request.Action switch
        {
            "AuthorizeEventOrganizers" => policy.AuthorizeEventOrganizers(record, request),
            "EnforceEventAudienceAndDiscovery" => policy.EnforceEventAudienceAndDiscovery(record, request),
            "ProtectAttendeeAndLocationPrivacy" => policy.ProtectAttendeeAndLocationPrivacy(record, request),
            _ => new(
                "unknown",
                FeatureDecisionKind.Invalid,
                "unknown_feature_action",
                record.State,
                record.Version)
        };

        if (!decision.IsAccepted)
        {
            return decision;
        }

        await repository.CommitAsync(record, decision, cancellationToken);
        await projector.EnqueueAsync(request, decision, cancellationToken);
        return decision;
    }
}
