// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;
using CommunityStarter.Domain.GeneratedFeatures;

namespace CommunityStarter.Application.GeneratedFeatures;

public interface IEnforceServerAuthorizationRepository
{
    ValueTask<EnforceServerAuthorizationRecord?> LoadAsync(
        Guid subjectId,
        Guid? communityId,
        CancellationToken cancellationToken);

    ValueTask CommitAsync(
        EnforceServerAuthorizationRecord current,
        EnforceServerAuthorizationDecision decision,
        CancellationToken cancellationToken);
}

public sealed class EnforceServerAuthorizationProjector(IFeatureProjectionSink sink)
{
    public ValueTask EnqueueAsync(
        EnforceServerAuthorizationRequest request,
        EnforceServerAuthorizationDecision decision,
        CancellationToken cancellationToken) =>
        sink.EnqueueAsync(
            EnforceServerAuthorizationDescriptor.Slug,
            request.SubjectId,
            request.CommunityId,
            decision.RequirementId,
            decision.ResultingVersion,
            cancellationToken);
}

public sealed class EnforceServerAuthorizationHandler(
    IEnforceServerAuthorizationRepository repository,
    EnforceServerAuthorizationProjector projector)
{
    public async ValueTask<EnforceServerAuthorizationDecision> HandleAsync(
        EnforceServerAuthorizationRequest request,
        CancellationToken cancellationToken)
    {
        var record = await repository.LoadAsync(
            request.SubjectId,
            request.CommunityId,
            cancellationToken) ?? new(
                request.SubjectId,
                request.CommunityId,
                "missing",
                request.ExpectedVersion,
                IsAuthorized: false,
                IsAvailable: false);
        var policy = new EnforceServerAuthorizationPolicy();
        var decision = request.Action switch
        {
            "EvaluateCurrentPermissions" => policy.EvaluateCurrentPermissions(record, request),
            "EnforceCommunityBoundaries" => policy.EnforceCommunityBoundaries(record, request),
            "ExposeAllowedActionsSafely" => policy.ExposeAllowedActionsSafely(record, request),
            _ => new(
                "unknown",
                FeatureDecisionKind.Invalid,
                "unknown_feature_action",
                record.State,
                record.Version)
        };

        if (!decision.IsAccepted)
        {
            return decision;
        }

        await repository.CommitAsync(record, decision, cancellationToken);
        await projector.EnqueueAsync(request, decision, cancellationToken);
        return decision;
    }
}
