// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;
using CommunityStarter.Domain.GeneratedFeatures;

namespace CommunityStarter.Application.GeneratedFeatures;

public interface IEnforceProportionateActionsRepository
{
    ValueTask<EnforceProportionateActionsRecord?> LoadAsync(
        Guid subjectId,
        Guid? communityId,
        CancellationToken cancellationToken);

    ValueTask CommitAsync(
        EnforceProportionateActionsRecord current,
        EnforceProportionateActionsDecision decision,
        CancellationToken cancellationToken);
}

public sealed class EnforceProportionateActionsProjector(IFeatureProjectionSink sink)
{
    public ValueTask EnqueueAsync(
        EnforceProportionateActionsRequest request,
        EnforceProportionateActionsDecision decision,
        CancellationToken cancellationToken) =>
        sink.EnqueueAsync(
            EnforceProportionateActionsDescriptor.Slug,
            request.SubjectId,
            request.CommunityId,
            decision.RequirementId,
            decision.ResultingVersion,
            cancellationToken);
}

public sealed class EnforceProportionateActionsHandler(
    IEnforceProportionateActionsRepository repository,
    EnforceProportionateActionsProjector projector)
{
    public async ValueTask<EnforceProportionateActionsDecision> HandleAsync(
        EnforceProportionateActionsRequest request,
        CancellationToken cancellationToken)
    {
        var record = await repository.LoadAsync(
            request.SubjectId,
            request.CommunityId,
            cancellationToken) ?? new(
                request.SubjectId,
                request.CommunityId,
                "missing",
                request.ExpectedVersion,
                IsAuthorized: false,
                IsAvailable: false);
        var policy = new EnforceProportionateActionsPolicy();
        var decision = request.Action switch
        {
            "BoundModeratorAuthorityAndConflicts" => policy.BoundModeratorAuthorityAndConflicts(record, request),
            "ApplyOneAuditableModerationAction" => policy.ApplyOneAuditableModerationAction(record, request),
            "NotifyExpireAndReverseActionsSafely" => policy.NotifyExpireAndReverseActionsSafely(record, request),
            "EnforceTheModerationActionEffectMatrix" => policy.EnforceTheModerationActionEffectMatrix(record, request),
            "RoutePunitiveChangesThroughModerationActions" => policy.RoutePunitiveChangesThroughModerationActions(record, request),
            "ResolveEnforcementAndOwnershipContinuityAtomically" => policy.ResolveEnforcementAndOwnershipContinuityAtomically(record, request),
            _ => new(
                "unknown",
                FeatureDecisionKind.Invalid,
                "unknown_feature_action",
                record.State,
                record.Version)
        };

        if (!decision.IsAccepted)
        {
            return decision;
        }

        await repository.CommitAsync(record, decision, cancellationToken);
        await projector.EnqueueAsync(request, decision, cancellationToken);
        return decision;
    }
}
