// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;
using CommunityStarter.Domain.GeneratedFeatures;

namespace CommunityStarter.Application.GeneratedFeatures;

public interface IEstablishVisualLanguageRepository
{
    ValueTask<EstablishVisualLanguageRecord?> LoadAsync(
        Guid subjectId,
        Guid? communityId,
        CancellationToken cancellationToken);

    ValueTask CommitAsync(
        EstablishVisualLanguageRecord current,
        EstablishVisualLanguageDecision decision,
        CancellationToken cancellationToken);
}

public sealed class EstablishVisualLanguageProjector(IFeatureProjectionSink sink)
{
    public ValueTask EnqueueAsync(
        EstablishVisualLanguageRequest request,
        EstablishVisualLanguageDecision decision,
        CancellationToken cancellationToken) =>
        sink.EnqueueAsync(
            EstablishVisualLanguageDescriptor.Slug,
            request.SubjectId,
            request.CommunityId,
            decision.RequirementId,
            decision.ResultingVersion,
            cancellationToken);
}

public sealed class EstablishVisualLanguageHandler(
    IEstablishVisualLanguageRepository repository,
    EstablishVisualLanguageProjector projector)
{
    public async ValueTask<EstablishVisualLanguageDecision> HandleAsync(
        EstablishVisualLanguageRequest request,
        CancellationToken cancellationToken)
    {
        var record = await repository.LoadAsync(
            request.SubjectId,
            request.CommunityId,
            cancellationToken) ?? new(
                request.SubjectId,
                request.CommunityId,
                "missing",
                request.ExpectedVersion,
                IsAuthorized: false,
                IsAvailable: false);
        var policy = new EstablishVisualLanguagePolicy();
        var decision = request.Action switch
        {
            "CanonicalFoundationsAndAssetsHaveOneSource" => policy.CanonicalFoundationsAndAssetsHaveOneSource(record, request),
            "SemanticTokensCoverAllProductRolesAndStates" => policy.SemanticTokensCoverAllProductRolesAndStates(record, request),
            "ComponentsProgressFromFoundationsToProductSignatures" => policy.ComponentsProgressFromFoundationsToProductSignatures(record, request),
            _ => new(
                "unknown",
                FeatureDecisionKind.Invalid,
                "unknown_feature_action",
                record.State,
                record.Version)
        };

        if (!decision.IsAccepted)
        {
            return decision;
        }

        await repository.CommitAsync(record, decision, cancellationToken);
        await projector.EnqueueAsync(request, decision, cancellationToken);
        return decision;
    }
}
