// <auto-generated />
#nullable enable
namespace CommunityStarter.Application.GeneratedFeatures;

public interface IFeatureProjectionSink
{
    ValueTask EnqueueAsync(
        string featureSlug,
        Guid subjectId,
        Guid? communityId,
        string requirementId,
        long committedVersion,
        CancellationToken cancellationToken);
}
