// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;
using CommunityStarter.Domain.GeneratedFeatures;

namespace CommunityStarter.Application.GeneratedFeatures;

public interface IGovernEveryDataCopyRepository
{
    ValueTask<GovernEveryDataCopyRecord?> LoadAsync(
        Guid subjectId,
        Guid? communityId,
        CancellationToken cancellationToken);

    ValueTask CommitAsync(
        GovernEveryDataCopyRecord current,
        GovernEveryDataCopyDecision decision,
        CancellationToken cancellationToken);
}

public sealed class GovernEveryDataCopyProjector(IFeatureProjectionSink sink)
{
    public ValueTask EnqueueAsync(
        GovernEveryDataCopyRequest request,
        GovernEveryDataCopyDecision decision,
        CancellationToken cancellationToken) =>
        sink.EnqueueAsync(
            GovernEveryDataCopyDescriptor.Slug,
            request.SubjectId,
            request.CommunityId,
            decision.RequirementId,
            decision.ResultingVersion,
            cancellationToken);
}

public sealed class GovernEveryDataCopyHandler(
    IGovernEveryDataCopyRepository repository,
    GovernEveryDataCopyProjector projector)
{
    public async ValueTask<GovernEveryDataCopyDecision> HandleAsync(
        GovernEveryDataCopyRequest request,
        CancellationToken cancellationToken)
    {
        var record = await repository.LoadAsync(
            request.SubjectId,
            request.CommunityId,
            cancellationToken) ?? new(
                request.SubjectId,
                request.CommunityId,
                "missing",
                request.ExpectedVersion,
                IsAuthorized: false,
                IsAvailable: false);
        var policy = new GovernEveryDataCopyPolicy();
        var decision = request.Action switch
        {
            "EnforceRetentionSchedules" => policy.EnforceRetentionSchedules(record, request),
            "PropagateDeletionToDerivedSystems" => policy.PropagateDeletionToDerivedSystems(record, request),
            "PreserveSharedContentIntegrityWithoutRetainingIdentityUnnecessarily" => policy.PreserveSharedContentIntegrityWithoutRetainingIdentityUnnecessarily(record, request),
            "RestrictLegalHoldsAndSafetyEvidence" => policy.RestrictLegalHoldsAndSafetyEvidence(record, request),
            _ => new(
                "unknown",
                FeatureDecisionKind.Invalid,
                "unknown_feature_action",
                record.State,
                record.Version)
        };

        if (!decision.IsAccepted)
        {
            return decision;
        }

        await repository.CommitAsync(record, decision, cancellationToken);
        await projector.EnqueueAsync(request, decision, cancellationToken);
        return decision;
    }
}
