// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;
using CommunityStarter.Domain.GeneratedFeatures;

namespace CommunityStarter.Application.GeneratedFeatures;

public interface IGovernSpaceParticipationRepository
{
    ValueTask<GovernSpaceParticipationRecord?> LoadAsync(
        Guid subjectId,
        Guid? communityId,
        CancellationToken cancellationToken);

    ValueTask CommitAsync(
        GovernSpaceParticipationRecord current,
        GovernSpaceParticipationDecision decision,
        CancellationToken cancellationToken);
}

public sealed class GovernSpaceParticipationProjector(IFeatureProjectionSink sink)
{
    public ValueTask EnqueueAsync(
        GovernSpaceParticipationRequest request,
        GovernSpaceParticipationDecision decision,
        CancellationToken cancellationToken) =>
        sink.EnqueueAsync(
            GovernSpaceParticipationDescriptor.Slug,
            request.SubjectId,
            request.CommunityId,
            decision.RequirementId,
            decision.ResultingVersion,
            cancellationToken);
}

public sealed class GovernSpaceParticipationHandler(
    IGovernSpaceParticipationRepository repository,
    GovernSpaceParticipationProjector projector)
{
    public async ValueTask<GovernSpaceParticipationDecision> HandleAsync(
        GovernSpaceParticipationRequest request,
        CancellationToken cancellationToken)
    {
        var record = await repository.LoadAsync(
            request.SubjectId,
            request.CommunityId,
            cancellationToken) ?? new(
                request.SubjectId,
                request.CommunityId,
                "missing",
                request.ExpectedVersion,
                IsAuthorized: false,
                IsAvailable: false);
        var policy = new GovernSpaceParticipationPolicy();
        var decision = request.Action switch
        {
            "GovernSpaceLifecycle" => policy.GovernSpaceLifecycle(record, request),
            "EnforceSpaceAccess" => policy.EnforceSpaceAccess(record, request),
            "DelegateSpaceAuthority" => policy.DelegateSpaceAuthority(record, request),
            "AcceptVersionedRules" => policy.AcceptVersionedRules(record, request),
            _ => new(
                "unknown",
                FeatureDecisionKind.Invalid,
                "unknown_feature_action",
                record.State,
                record.Version)
        };

        if (!decision.IsAccepted)
        {
            return decision;
        }

        await repository.CommitAsync(record, decision, cancellationToken);
        await projector.EnqueueAsync(request, decision, cancellationToken);
        return decision;
    }
}
