// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;
using CommunityStarter.Domain.GeneratedFeatures;

namespace CommunityStarter.Application.GeneratedFeatures;

public interface IHandleAttachmentsSafelyRepository
{
    ValueTask<HandleAttachmentsSafelyRecord?> LoadAsync(
        Guid subjectId,
        Guid? communityId,
        CancellationToken cancellationToken);

    ValueTask CommitAsync(
        HandleAttachmentsSafelyRecord current,
        HandleAttachmentsSafelyDecision decision,
        CancellationToken cancellationToken);
}

public sealed class HandleAttachmentsSafelyProjector(IFeatureProjectionSink sink)
{
    public ValueTask EnqueueAsync(
        HandleAttachmentsSafelyRequest request,
        HandleAttachmentsSafelyDecision decision,
        CancellationToken cancellationToken) =>
        sink.EnqueueAsync(
            HandleAttachmentsSafelyDescriptor.Slug,
            request.SubjectId,
            request.CommunityId,
            decision.RequirementId,
            decision.ResultingVersion,
            cancellationToken);
}

public sealed class HandleAttachmentsSafelyHandler(
    IHandleAttachmentsSafelyRepository repository,
    HandleAttachmentsSafelyProjector projector)
{
    public async ValueTask<HandleAttachmentsSafelyDecision> HandleAsync(
        HandleAttachmentsSafelyRequest request,
        CancellationToken cancellationToken)
    {
        var record = await repository.LoadAsync(
            request.SubjectId,
            request.CommunityId,
            cancellationToken) ?? new(
                request.SubjectId,
                request.CommunityId,
                "missing",
                request.ExpectedVersion,
                IsAuthorized: false,
                IsAvailable: false);
        var policy = new HandleAttachmentsSafelyPolicy();
        var decision = request.Action switch
        {
            "StageAnAttachment" => policy.StageAnAttachment(record, request),
            "ProcessAnAttachment" => policy.ProcessAnAttachment(record, request),
            "ProtectAttachmentAccess" => policy.ProtectAttachmentAccess(record, request),
            _ => new(
                "unknown",
                FeatureDecisionKind.Invalid,
                "unknown_feature_action",
                record.State,
                record.Version)
        };

        if (!decision.IsAccepted)
        {
            return decision;
        }

        await repository.CommitAsync(record, decision, cancellationToken);
        await projector.EnqueueAsync(request, decision, cancellationToken);
        return decision;
    }
}
