// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;
using CommunityStarter.Domain.GeneratedFeatures;

namespace CommunityStarter.Application.GeneratedFeatures;

public interface IHardenRuntimeSupplyChainRepository
{
    ValueTask<HardenRuntimeSupplyChainRecord?> LoadAsync(
        Guid subjectId,
        Guid? communityId,
        CancellationToken cancellationToken);

    ValueTask CommitAsync(
        HardenRuntimeSupplyChainRecord current,
        HardenRuntimeSupplyChainDecision decision,
        CancellationToken cancellationToken);
}

public sealed class HardenRuntimeSupplyChainProjector(IFeatureProjectionSink sink)
{
    public ValueTask EnqueueAsync(
        HardenRuntimeSupplyChainRequest request,
        HardenRuntimeSupplyChainDecision decision,
        CancellationToken cancellationToken) =>
        sink.EnqueueAsync(
            HardenRuntimeSupplyChainDescriptor.Slug,
            request.SubjectId,
            request.CommunityId,
            decision.RequirementId,
            decision.ResultingVersion,
            cancellationToken);
}

public sealed class HardenRuntimeSupplyChainHandler(
    IHardenRuntimeSupplyChainRepository repository,
    HardenRuntimeSupplyChainProjector projector)
{
    public async ValueTask<HardenRuntimeSupplyChainDecision> HandleAsync(
        HardenRuntimeSupplyChainRequest request,
        CancellationToken cancellationToken)
    {
        var record = await repository.LoadAsync(
            request.SubjectId,
            request.CommunityId,
            cancellationToken) ?? new(
                request.SubjectId,
                request.CommunityId,
                "missing",
                request.ExpectedVersion,
                IsAuthorized: false,
                IsAvailable: false);
        var policy = new HardenRuntimeSupplyChainPolicy();
        var decision = request.Action switch
        {
            "BrowserAndTransportHeadersMatchTheDeploymentThreatModel" => policy.BrowserAndTransportHeadersMatchTheDeploymentThreatModel(record, request),
            "DeploymentUsesProtectedEnvironmentsAndShortLivedCredentials" => policy.DeploymentUsesProtectedEnvironmentsAndShortLivedCredentials(record, request),
            "SupplyChainChangesAreReviewedAndContinuouslyScanned" => policy.SupplyChainChangesAreReviewedAndContinuouslyScanned(record, request),
            _ => new(
                "unknown",
                FeatureDecisionKind.Invalid,
                "unknown_feature_action",
                record.State,
                record.Version)
        };

        if (!decision.IsAccepted)
        {
            return decision;
        }

        await repository.CommitAsync(record, decision, cancellationToken);
        await projector.EnqueueAsync(request, decision, cancellationToken);
        return decision;
    }
}
