// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;
using CommunityStarter.Domain.GeneratedFeatures;

namespace CommunityStarter.Application.GeneratedFeatures;

public interface IIsolateDevelopmentDataRepository
{
    ValueTask<IsolateDevelopmentDataRecord?> LoadAsync(
        Guid subjectId,
        Guid? communityId,
        CancellationToken cancellationToken);

    ValueTask CommitAsync(
        IsolateDevelopmentDataRecord current,
        IsolateDevelopmentDataDecision decision,
        CancellationToken cancellationToken);
}

public sealed class IsolateDevelopmentDataProjector(IFeatureProjectionSink sink)
{
    public ValueTask EnqueueAsync(
        IsolateDevelopmentDataRequest request,
        IsolateDevelopmentDataDecision decision,
        CancellationToken cancellationToken) =>
        sink.EnqueueAsync(
            IsolateDevelopmentDataDescriptor.Slug,
            request.SubjectId,
            request.CommunityId,
            decision.RequirementId,
            decision.ResultingVersion,
            cancellationToken);
}

public sealed class IsolateDevelopmentDataHandler(
    IIsolateDevelopmentDataRepository repository,
    IsolateDevelopmentDataProjector projector)
{
    public async ValueTask<IsolateDevelopmentDataDecision> HandleAsync(
        IsolateDevelopmentDataRequest request,
        CancellationToken cancellationToken)
    {
        var record = await repository.LoadAsync(
            request.SubjectId,
            request.CommunityId,
            cancellationToken) ?? new(
                request.SubjectId,
                request.CommunityId,
                "missing",
                request.ExpectedVersion,
                IsAuthorized: false,
                IsAvailable: false);
        var policy = new IsolateDevelopmentDataPolicy();
        var decision = request.Action switch
        {
            "SeedDeterministicFictionalScenarios" => policy.SeedDeterministicFictionalScenarios(record, request),
            "IsolateDevelopmentOnlyIdentityAndProviders" => policy.IsolateDevelopmentOnlyIdentityAndProviders(record, request),
            _ => new(
                "unknown",
                FeatureDecisionKind.Invalid,
                "unknown_feature_action",
                record.State,
                record.Version)
        };

        if (!decision.IsAccepted)
        {
            return decision;
        }

        await repository.CommitAsync(record, decision, cancellationToken);
        await projector.EnqueueAsync(request, decision, cancellationToken);
        return decision;
    }
}
