// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;
using CommunityStarter.Domain.GeneratedFeatures;

namespace CommunityStarter.Application.GeneratedFeatures;

public interface IKeepBehaviorServerAuthoritativeRepository
{
    ValueTask<KeepBehaviorServerAuthoritativeRecord?> LoadAsync(
        Guid subjectId,
        Guid? communityId,
        CancellationToken cancellationToken);

    ValueTask CommitAsync(
        KeepBehaviorServerAuthoritativeRecord current,
        KeepBehaviorServerAuthoritativeDecision decision,
        CancellationToken cancellationToken);
}

public sealed class KeepBehaviorServerAuthoritativeProjector(IFeatureProjectionSink sink)
{
    public ValueTask EnqueueAsync(
        KeepBehaviorServerAuthoritativeRequest request,
        KeepBehaviorServerAuthoritativeDecision decision,
        CancellationToken cancellationToken) =>
        sink.EnqueueAsync(
            KeepBehaviorServerAuthoritativeDescriptor.Slug,
            request.SubjectId,
            request.CommunityId,
            decision.RequirementId,
            decision.ResultingVersion,
            cancellationToken);
}

public sealed class KeepBehaviorServerAuthoritativeHandler(
    IKeepBehaviorServerAuthoritativeRepository repository,
    KeepBehaviorServerAuthoritativeProjector projector)
{
    public async ValueTask<KeepBehaviorServerAuthoritativeDecision> HandleAsync(
        KeepBehaviorServerAuthoritativeRequest request,
        CancellationToken cancellationToken)
    {
        var record = await repository.LoadAsync(
            request.SubjectId,
            request.CommunityId,
            cancellationToken) ?? new(
                request.SubjectId,
                request.CommunityId,
                "missing",
                request.ExpectedVersion,
                IsAuthorized: false,
                IsAvailable: false);
        var policy = new KeepBehaviorServerAuthoritativePolicy();
        var decision = request.Action switch
        {
            "ApplicationCodeIsOrganizedByCapabilityAndUseCase" => policy.ApplicationCodeIsOrganizedByCapabilityAndUseCase(record, request),
            "StateChangesFollowOneAuthoritativeSequence" => policy.StateChangesFollowOneAuthoritativeSequence(record, request),
            "HTTPContractsAndFailuresAreStableAndExplicit" => policy.HTTPContractsAndFailuresAreStableAndExplicit(record, request),
            _ => new(
                "unknown",
                FeatureDecisionKind.Invalid,
                "unknown_feature_action",
                record.State,
                record.Version)
        };

        if (!decision.IsAccepted)
        {
            return decision;
        }

        await repository.CommitAsync(record, decision, cancellationToken);
        await projector.EnqueueAsync(request, decision, cancellationToken);
        return decision;
    }
}
