// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;
using CommunityStarter.Domain.GeneratedFeatures;

namespace CommunityStarter.Application.GeneratedFeatures;

public interface IKeepDeliveryClaimsHonestRepository
{
    ValueTask<KeepDeliveryClaimsHonestRecord?> LoadAsync(
        Guid subjectId,
        Guid? communityId,
        CancellationToken cancellationToken);

    ValueTask CommitAsync(
        KeepDeliveryClaimsHonestRecord current,
        KeepDeliveryClaimsHonestDecision decision,
        CancellationToken cancellationToken);
}

public sealed class KeepDeliveryClaimsHonestProjector(IFeatureProjectionSink sink)
{
    public ValueTask EnqueueAsync(
        KeepDeliveryClaimsHonestRequest request,
        KeepDeliveryClaimsHonestDecision decision,
        CancellationToken cancellationToken) =>
        sink.EnqueueAsync(
            KeepDeliveryClaimsHonestDescriptor.Slug,
            request.SubjectId,
            request.CommunityId,
            decision.RequirementId,
            decision.ResultingVersion,
            cancellationToken);
}

public sealed class KeepDeliveryClaimsHonestHandler(
    IKeepDeliveryClaimsHonestRepository repository,
    KeepDeliveryClaimsHonestProjector projector)
{
    public async ValueTask<KeepDeliveryClaimsHonestDecision> HandleAsync(
        KeepDeliveryClaimsHonestRequest request,
        CancellationToken cancellationToken)
    {
        var record = await repository.LoadAsync(
            request.SubjectId,
            request.CommunityId,
            cancellationToken) ?? new(
                request.SubjectId,
                request.CommunityId,
                "missing",
                request.ExpectedVersion,
                IsAuthorized: false,
                IsAvailable: false);
        var policy = new KeepDeliveryClaimsHonestPolicy();
        var decision = request.Action switch
        {
            "PullRequestsAndHandoffsExposeImpactAndVerification" => policy.PullRequestsAndHandoffsExposeImpactAndVerification(record, request),
            "DocumentationAndDecisionEvidenceStayCurrentWithBehavior" => policy.DocumentationAndDecisionEvidenceStayCurrentWithBehavior(record, request),
            "DefinitionOfDoneAndProductionReadinessClaimsMatchEvidence" => policy.DefinitionOfDoneAndProductionReadinessClaimsMatchEvidence(record, request),
            _ => new(
                "unknown",
                FeatureDecisionKind.Invalid,
                "unknown_feature_action",
                record.State,
                record.Version)
        };

        if (!decision.IsAccepted)
        {
            return decision;
        }

        await repository.CommitAsync(record, decision, cancellationToken);
        await projector.EnqueueAsync(request, decision, cancellationToken);
        return decision;
    }
}
