// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;
using CommunityStarter.Domain.GeneratedFeatures;

namespace CommunityStarter.Application.GeneratedFeatures;

public interface IKeepOnboardingSafeRepository
{
    ValueTask<KeepOnboardingSafeRecord?> LoadAsync(
        Guid subjectId,
        Guid? communityId,
        CancellationToken cancellationToken);

    ValueTask CommitAsync(
        KeepOnboardingSafeRecord current,
        KeepOnboardingSafeDecision decision,
        CancellationToken cancellationToken);
}

public sealed class KeepOnboardingSafeProjector(IFeatureProjectionSink sink)
{
    public ValueTask EnqueueAsync(
        KeepOnboardingSafeRequest request,
        KeepOnboardingSafeDecision decision,
        CancellationToken cancellationToken) =>
        sink.EnqueueAsync(
            KeepOnboardingSafeDescriptor.Slug,
            request.SubjectId,
            request.CommunityId,
            decision.RequirementId,
            decision.ResultingVersion,
            cancellationToken);
}

public sealed class KeepOnboardingSafeHandler(
    IKeepOnboardingSafeRepository repository,
    KeepOnboardingSafeProjector projector)
{
    public async ValueTask<KeepOnboardingSafeDecision> HandleAsync(
        KeepOnboardingSafeRequest request,
        CancellationToken cancellationToken)
    {
        var record = await repository.LoadAsync(
            request.SubjectId,
            request.CommunityId,
            cancellationToken) ?? new(
                request.SubjectId,
                request.CommunityId,
                "missing",
                request.ExpectedVersion,
                IsAuthorized: false,
                IsAvailable: false);
        var policy = new KeepOnboardingSafePolicy();
        var decision = request.Action switch
        {
            "RecordEligibilityAndConsent" => policy.RecordEligibilityAndConsent(record, request),
            "ExcludeUnsafeCommunitySuggestions" => policy.ExcludeUnsafeCommunitySuggestions(record, request),
            "RecoverFromEmptyAndErrorStates" => policy.RecoverFromEmptyAndErrorStates(record, request),
            _ => new(
                "unknown",
                FeatureDecisionKind.Invalid,
                "unknown_feature_action",
                record.State,
                record.Version)
        };

        if (!decision.IsAccepted)
        {
            return decision;
        }

        await repository.CommitAsync(record, decision, cancellationToken);
        await projector.EnqueueAsync(request, decision, cancellationToken);
        return decision;
    }
}
