// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;
using CommunityStarter.Domain.GeneratedFeatures;

namespace CommunityStarter.Application.GeneratedFeatures;

public interface IKeepTestsDeterministicRepository
{
    ValueTask<KeepTestsDeterministicRecord?> LoadAsync(
        Guid subjectId,
        Guid? communityId,
        CancellationToken cancellationToken);

    ValueTask CommitAsync(
        KeepTestsDeterministicRecord current,
        KeepTestsDeterministicDecision decision,
        CancellationToken cancellationToken);
}

public sealed class KeepTestsDeterministicProjector(IFeatureProjectionSink sink)
{
    public ValueTask EnqueueAsync(
        KeepTestsDeterministicRequest request,
        KeepTestsDeterministicDecision decision,
        CancellationToken cancellationToken) =>
        sink.EnqueueAsync(
            KeepTestsDeterministicDescriptor.Slug,
            request.SubjectId,
            request.CommunityId,
            decision.RequirementId,
            decision.ResultingVersion,
            cancellationToken);
}

public sealed class KeepTestsDeterministicHandler(
    IKeepTestsDeterministicRepository repository,
    KeepTestsDeterministicProjector projector)
{
    public async ValueTask<KeepTestsDeterministicDecision> HandleAsync(
        KeepTestsDeterministicRequest request,
        CancellationToken cancellationToken)
    {
        var record = await repository.LoadAsync(
            request.SubjectId,
            request.CommunityId,
            cancellationToken) ?? new(
                request.SubjectId,
                request.CommunityId,
                "missing",
                request.ExpectedVersion,
                IsAuthorized: false,
                IsAvailable: false);
        var policy = new KeepTestsDeterministicPolicy();
        var decision = request.Action switch
        {
            "TestsAreBehavioralIsolatedAndDeterministic" => policy.TestsAreBehavioralIsolatedAndDeterministic(record, request),
            "BrowserJourneysUseStablePageObjectsAndFaithfulDependencies" => policy.BrowserJourneysUseStablePageObjectsAndFaithfulDependencies(record, request),
            "RequirementStatusIsBackedByAppropriatelyScopedEvidence" => policy.RequirementStatusIsBackedByAppropriatelyScopedEvidence(record, request),
            _ => new(
                "unknown",
                FeatureDecisionKind.Invalid,
                "unknown_feature_action",
                record.State,
                record.Version)
        };

        if (!decision.IsAccepted)
        {
            return decision;
        }

        await repository.CommitAsync(record, decision, cancellationToken);
        await projector.EnqueueAsync(request, decision, cancellationToken);
        return decision;
    }
}
