// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;
using CommunityStarter.Domain.GeneratedFeatures;

namespace CommunityStarter.Application.GeneratedFeatures;

public interface IMaintainRepositoryKnowledgeRepository
{
    ValueTask<MaintainRepositoryKnowledgeRecord?> LoadAsync(
        Guid subjectId,
        Guid? communityId,
        CancellationToken cancellationToken);

    ValueTask CommitAsync(
        MaintainRepositoryKnowledgeRecord current,
        MaintainRepositoryKnowledgeDecision decision,
        CancellationToken cancellationToken);
}

public sealed class MaintainRepositoryKnowledgeProjector(IFeatureProjectionSink sink)
{
    public ValueTask EnqueueAsync(
        MaintainRepositoryKnowledgeRequest request,
        MaintainRepositoryKnowledgeDecision decision,
        CancellationToken cancellationToken) =>
        sink.EnqueueAsync(
            MaintainRepositoryKnowledgeDescriptor.Slug,
            request.SubjectId,
            request.CommunityId,
            decision.RequirementId,
            decision.ResultingVersion,
            cancellationToken);
}

public sealed class MaintainRepositoryKnowledgeHandler(
    IMaintainRepositoryKnowledgeRepository repository,
    MaintainRepositoryKnowledgeProjector projector)
{
    public async ValueTask<MaintainRepositoryKnowledgeDecision> HandleAsync(
        MaintainRepositoryKnowledgeRequest request,
        CancellationToken cancellationToken)
    {
        var record = await repository.LoadAsync(
            request.SubjectId,
            request.CommunityId,
            cancellationToken) ?? new(
                request.SubjectId,
                request.CommunityId,
                "missing",
                request.ExpectedVersion,
                IsAuthorized: false,
                IsAvailable: false);
        var policy = new MaintainRepositoryKnowledgePolicy();
        var decision = request.Action switch
        {
            "MaintainAnOutcomeOrientedDocumentationMap" => policy.MaintainAnOutcomeOrientedDocumentationMap(record, request),
            "DocumentContributionOwnershipSupportAndDisclosure" => policy.DocumentContributionOwnershipSupportAndDisclosure(record, request),
            "TrackDependencyAndAssetProvenance" => policy.TrackDependencyAndAssetProvenance(record, request),
            _ => new(
                "unknown",
                FeatureDecisionKind.Invalid,
                "unknown_feature_action",
                record.State,
                record.Version)
        };

        if (!decision.IsAccepted)
        {
            return decision;
        }

        await repository.CommitAsync(record, decision, cancellationToken);
        await projector.EnqueueAsync(request, decision, cancellationToken);
        return decision;
    }
}
