// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;
using CommunityStarter.Domain.GeneratedFeatures;

namespace CommunityStarter.Application.GeneratedFeatures;

public interface IMakePublicDiscoveryCacheSafeRepository
{
    ValueTask<MakePublicDiscoveryCacheSafeRecord?> LoadAsync(
        Guid subjectId,
        Guid? communityId,
        CancellationToken cancellationToken);

    ValueTask CommitAsync(
        MakePublicDiscoveryCacheSafeRecord current,
        MakePublicDiscoveryCacheSafeDecision decision,
        CancellationToken cancellationToken);
}

public sealed class MakePublicDiscoveryCacheSafeProjector(IFeatureProjectionSink sink)
{
    public ValueTask EnqueueAsync(
        MakePublicDiscoveryCacheSafeRequest request,
        MakePublicDiscoveryCacheSafeDecision decision,
        CancellationToken cancellationToken) =>
        sink.EnqueueAsync(
            MakePublicDiscoveryCacheSafeDescriptor.Slug,
            request.SubjectId,
            request.CommunityId,
            decision.RequirementId,
            decision.ResultingVersion,
            cancellationToken);
}

public sealed class MakePublicDiscoveryCacheSafeHandler(
    IMakePublicDiscoveryCacheSafeRepository repository,
    MakePublicDiscoveryCacheSafeProjector projector)
{
    public async ValueTask<MakePublicDiscoveryCacheSafeDecision> HandleAsync(
        MakePublicDiscoveryCacheSafeRequest request,
        CancellationToken cancellationToken)
    {
        var record = await repository.LoadAsync(
            request.SubjectId,
            request.CommunityId,
            cancellationToken) ?? new(
                request.SubjectId,
                request.CommunityId,
                "missing",
                request.ExpectedVersion,
                IsAuthorized: false,
                IsAvailable: false);
        var policy = new MakePublicDiscoveryCacheSafePolicy();
        var decision = request.Action switch
        {
            "PublicMetadataAndIndexingAreDeliberate" => policy.PublicMetadataAndIndexingAreDeliberate(record, request),
            "PublicPerformanceHasAnExplicitBudget" => policy.PublicPerformanceHasAnExplicitBudget(record, request),
            "AnalyticsEmbedsAndAuthenticatedDataRemainPrivateByDesign" => policy.AnalyticsEmbedsAndAuthenticatedDataRemainPrivateByDesign(record, request),
            "CachePolicyDistinguishesImmutableAndRevalidatedContent" => policy.CachePolicyDistinguishesImmutableAndRevalidatedContent(record, request),
            "PublishIndexableCommunitiesSafely" => policy.PublishIndexableCommunitiesSafely(record, request),
            _ => new(
                "unknown",
                FeatureDecisionKind.Invalid,
                "unknown_feature_action",
                record.State,
                record.Version)
        };

        if (!decision.IsAccepted)
        {
            return decision;
        }

        await repository.CommitAsync(record, decision, cancellationToken);
        await projector.EnqueueAsync(request, decision, cancellationToken);
        return decision;
    }
}
