// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;
using CommunityStarter.Domain.GeneratedFeatures;

namespace CommunityStarter.Application.GeneratedFeatures;

public interface IMakeInteractionStatesResilientRepository
{
    ValueTask<MakeInteractionStatesResilientRecord?> LoadAsync(
        Guid subjectId,
        Guid? communityId,
        CancellationToken cancellationToken);

    ValueTask CommitAsync(
        MakeInteractionStatesResilientRecord current,
        MakeInteractionStatesResilientDecision decision,
        CancellationToken cancellationToken);
}

public sealed class MakeInteractionStatesResilientProjector(IFeatureProjectionSink sink)
{
    public ValueTask EnqueueAsync(
        MakeInteractionStatesResilientRequest request,
        MakeInteractionStatesResilientDecision decision,
        CancellationToken cancellationToken) =>
        sink.EnqueueAsync(
            MakeInteractionStatesResilientDescriptor.Slug,
            request.SubjectId,
            request.CommunityId,
            decision.RequirementId,
            decision.ResultingVersion,
            cancellationToken);
}

public sealed class MakeInteractionStatesResilientHandler(
    IMakeInteractionStatesResilientRepository repository,
    MakeInteractionStatesResilientProjector projector)
{
    public async ValueTask<MakeInteractionStatesResilientDecision> HandleAsync(
        MakeInteractionStatesResilientRequest request,
        CancellationToken cancellationToken)
    {
        var record = await repository.LoadAsync(
            request.SubjectId,
            request.CommunityId,
            cancellationToken) ?? new(
                request.SubjectId,
                request.CommunityId,
                "missing",
                request.ExpectedVersion,
                IsAuthorized: false,
                IsAvailable: false);
        var policy = new MakeInteractionStatesResilientPolicy();
        var decision = request.Action switch
        {
            "TemplatesAndNavigationUseSemanticWebBehavior" => policy.TemplatesAndNavigationUseSemanticWebBehavior(record, request),
            "StylingLayoutMotionIconsAndMediaFollowSystemRules" => policy.StylingLayoutMotionIconsAndMediaFollowSystemRules(record, request),
            "FeatureStatesAreCompleteAndServerTruthIsReconciled" => policy.FeatureStatesAreCompleteAndServerTruthIsReconciled(record, request),
            _ => new(
                "unknown",
                FeatureDecisionKind.Invalid,
                "unknown_feature_action",
                record.State,
                record.Version)
        };

        if (!decision.IsAccepted)
        {
            return decision;
        }

        await repository.CommitAsync(record, decision, cancellationToken);
        await projector.EnqueueAsync(request, decision, cancellationToken);
        return decision;
    }
}
