// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;
using CommunityStarter.Domain.GeneratedFeatures;

namespace CommunityStarter.Application.GeneratedFeatures;

public interface IMakeLanguageAndMediaInclusiveRepository
{
    ValueTask<MakeLanguageAndMediaInclusiveRecord?> LoadAsync(
        Guid subjectId,
        Guid? communityId,
        CancellationToken cancellationToken);

    ValueTask CommitAsync(
        MakeLanguageAndMediaInclusiveRecord current,
        MakeLanguageAndMediaInclusiveDecision decision,
        CancellationToken cancellationToken);
}

public sealed class MakeLanguageAndMediaInclusiveProjector(IFeatureProjectionSink sink)
{
    public ValueTask EnqueueAsync(
        MakeLanguageAndMediaInclusiveRequest request,
        MakeLanguageAndMediaInclusiveDecision decision,
        CancellationToken cancellationToken) =>
        sink.EnqueueAsync(
            MakeLanguageAndMediaInclusiveDescriptor.Slug,
            request.SubjectId,
            request.CommunityId,
            decision.RequirementId,
            decision.ResultingVersion,
            cancellationToken);
}

public sealed class MakeLanguageAndMediaInclusiveHandler(
    IMakeLanguageAndMediaInclusiveRepository repository,
    MakeLanguageAndMediaInclusiveProjector projector)
{
    public async ValueTask<MakeLanguageAndMediaInclusiveDecision> HandleAsync(
        MakeLanguageAndMediaInclusiveRequest request,
        CancellationToken cancellationToken)
    {
        var record = await repository.LoadAsync(
            request.SubjectId,
            request.CommunityId,
            cancellationToken) ?? new(
                request.SubjectId,
                request.CommunityId,
                "missing",
                request.ExpectedVersion,
                IsAuthorized: false,
                IsAvailable: false);
        var policy = new MakeLanguageAndMediaInclusivePolicy();
        var decision = request.Action switch
        {
            "LocalizeEveryUserFacingContract" => policy.LocalizeEveryUserFacingContract(record, request),
            "RenderLocaleAndTimeZoneValuesConsistently" => policy.RenderLocaleAndTimeZoneValuesConsistently(record, request),
            "RequireAccessibleMediaAlternatives" => policy.RequireAccessibleMediaAlternatives(record, request),
            _ => new(
                "unknown",
                FeatureDecisionKind.Invalid,
                "unknown_feature_action",
                record.State,
                record.Version)
        };

        if (!decision.IsAccepted)
        {
            return decision;
        }

        await repository.CommitAsync(record, decision, cancellationToken);
        await projector.EnqueueAsync(request, decision, cancellationToken);
        return decision;
    }
}
