// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;
using CommunityStarter.Domain.GeneratedFeatures;

namespace CommunityStarter.Application.GeneratedFeatures;

public interface IManageAttendanceRepository
{
    ValueTask<ManageAttendanceRecord?> LoadAsync(
        Guid subjectId,
        Guid? communityId,
        CancellationToken cancellationToken);

    ValueTask CommitAsync(
        ManageAttendanceRecord current,
        ManageAttendanceDecision decision,
        CancellationToken cancellationToken);
}

public sealed class ManageAttendanceProjector(IFeatureProjectionSink sink)
{
    public ValueTask EnqueueAsync(
        ManageAttendanceRequest request,
        ManageAttendanceDecision decision,
        CancellationToken cancellationToken) =>
        sink.EnqueueAsync(
            ManageAttendanceDescriptor.Slug,
            request.SubjectId,
            request.CommunityId,
            decision.RequirementId,
            decision.ResultingVersion,
            cancellationToken);
}

public sealed class ManageAttendanceHandler(
    IManageAttendanceRepository repository,
    ManageAttendanceProjector projector)
{
    public async ValueTask<ManageAttendanceDecision> HandleAsync(
        ManageAttendanceRequest request,
        CancellationToken cancellationToken)
    {
        var record = await repository.LoadAsync(
            request.SubjectId,
            request.CommunityId,
            cancellationToken) ?? new(
                request.SubjectId,
                request.CommunityId,
                "missing",
                request.ExpectedVersion,
                IsAuthorized: false,
                IsAvailable: false);
        var policy = new ManageAttendancePolicy();
        var decision = request.Action switch
        {
            "TransitionOneCurrentRSVP" => policy.TransitionOneCurrentRSVP(record, request),
            "AllocateCapacityAndWaitlistFairly" => policy.AllocateCapacityAndWaitlistFairly(record, request),
            "ReconcileAttendanceAfterAccessLoss" => policy.ReconcileAttendanceAfterAccessLoss(record, request),
            _ => new(
                "unknown",
                FeatureDecisionKind.Invalid,
                "unknown_feature_action",
                record.State,
                record.Version)
        };

        if (!decision.IsAccepted)
        {
            return decision;
        }

        await repository.CommitAsync(record, decision, cancellationToken);
        await projector.EnqueueAsync(request, decision, cancellationToken);
        return decision;
    }
}
