// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;
using CommunityStarter.Domain.GeneratedFeatures;

namespace CommunityStarter.Application.GeneratedFeatures;

public interface IManageSafeAccountLifecycleRepository
{
    ValueTask<ManageSafeAccountLifecycleRecord?> LoadAsync(
        Guid subjectId,
        Guid? communityId,
        CancellationToken cancellationToken);

    ValueTask CommitAsync(
        ManageSafeAccountLifecycleRecord current,
        ManageSafeAccountLifecycleDecision decision,
        CancellationToken cancellationToken);
}

public sealed class ManageSafeAccountLifecycleProjector(IFeatureProjectionSink sink)
{
    public ValueTask EnqueueAsync(
        ManageSafeAccountLifecycleRequest request,
        ManageSafeAccountLifecycleDecision decision,
        CancellationToken cancellationToken) =>
        sink.EnqueueAsync(
            ManageSafeAccountLifecycleDescriptor.Slug,
            request.SubjectId,
            request.CommunityId,
            decision.RequirementId,
            decision.ResultingVersion,
            cancellationToken);
}

public sealed class ManageSafeAccountLifecycleHandler(
    IManageSafeAccountLifecycleRepository repository,
    ManageSafeAccountLifecycleProjector projector)
{
    public async ValueTask<ManageSafeAccountLifecycleDecision> HandleAsync(
        ManageSafeAccountLifecycleRequest request,
        CancellationToken cancellationToken)
    {
        var record = await repository.LoadAsync(
            request.SubjectId,
            request.CommunityId,
            cancellationToken) ?? new(
                request.SubjectId,
                request.CommunityId,
                "missing",
                request.ExpectedVersion,
                IsAuthorized: false,
                IsAvailable: false);
        var policy = new ManageSafeAccountLifecyclePolicy();
        var decision = request.Action switch
        {
            "RegisterAnAccountSafely" => policy.RegisterAnAccountSafely(record, request),
            "VerifyAccountOwnership" => policy.VerifyAccountOwnership(record, request),
            "RecoverAccountAccess" => policy.RecoverAccountAccess(record, request),
            "EnterAccountDeactivationSafely" => policy.EnterAccountDeactivationSafely(record, request),
            "ProtectLocalCredentialsAndActionSecrets" => policy.ProtectLocalCredentialsAndActionSecrets(record, request),
            _ => new(
                "unknown",
                FeatureDecisionKind.Invalid,
                "unknown_feature_action",
                record.State,
                record.Version)
        };

        if (!decision.IsAccepted)
        {
            return decision;
        }

        await repository.CommitAsync(record, decision, cancellationToken);
        await projector.EnqueueAsync(request, decision, cancellationToken);
        return decision;
    }
}
