// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;
using CommunityStarter.Domain.GeneratedFeatures;

namespace CommunityStarter.Application.GeneratedFeatures;

public interface IManageEventLifecycleRepository
{
    ValueTask<ManageEventLifecycleRecord?> LoadAsync(
        Guid subjectId,
        Guid? communityId,
        CancellationToken cancellationToken);

    ValueTask CommitAsync(
        ManageEventLifecycleRecord current,
        ManageEventLifecycleDecision decision,
        CancellationToken cancellationToken);
}

public sealed class ManageEventLifecycleProjector(IFeatureProjectionSink sink)
{
    public ValueTask EnqueueAsync(
        ManageEventLifecycleRequest request,
        ManageEventLifecycleDecision decision,
        CancellationToken cancellationToken) =>
        sink.EnqueueAsync(
            ManageEventLifecycleDescriptor.Slug,
            request.SubjectId,
            request.CommunityId,
            decision.RequirementId,
            decision.ResultingVersion,
            cancellationToken);
}

public sealed class ManageEventLifecycleHandler(
    IManageEventLifecycleRepository repository,
    ManageEventLifecycleProjector projector)
{
    public async ValueTask<ManageEventLifecycleDecision> HandleAsync(
        ManageEventLifecycleRequest request,
        CancellationToken cancellationToken)
    {
        var record = await repository.LoadAsync(
            request.SubjectId,
            request.CommunityId,
            cancellationToken) ?? new(
                request.SubjectId,
                request.CommunityId,
                "missing",
                request.ExpectedVersion,
                IsAuthorized: false,
                IsAvailable: false);
        var policy = new ManageEventLifecyclePolicy();
        var decision = request.Action switch
        {
            "CreateAValidEvent" => policy.CreateAValidEvent(record, request),
            "PublishReviseAndCancelAtomically" => policy.PublishReviseAndCancelAtomically(record, request),
            _ => new(
                "unknown",
                FeatureDecisionKind.Invalid,
                "unknown_feature_action",
                record.State,
                record.Version)
        };

        if (!decision.IsAccepted)
        {
            return decision;
        }

        await repository.CommitAsync(record, decision, cancellationToken);
        await projector.EnqueueAsync(request, decision, cancellationToken);
        return decision;
    }
}
