// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;
using CommunityStarter.Domain.GeneratedFeatures;

namespace CommunityStarter.Application.GeneratedFeatures;

public interface IManageModerationCasesRepository
{
    ValueTask<ManageModerationCasesRecord?> LoadAsync(
        Guid subjectId,
        Guid? communityId,
        CancellationToken cancellationToken);

    ValueTask CommitAsync(
        ManageModerationCasesRecord current,
        ManageModerationCasesDecision decision,
        CancellationToken cancellationToken);
}

public sealed class ManageModerationCasesProjector(IFeatureProjectionSink sink)
{
    public ValueTask EnqueueAsync(
        ManageModerationCasesRequest request,
        ManageModerationCasesDecision decision,
        CancellationToken cancellationToken) =>
        sink.EnqueueAsync(
            ManageModerationCasesDescriptor.Slug,
            request.SubjectId,
            request.CommunityId,
            decision.RequirementId,
            decision.ResultingVersion,
            cancellationToken);
}

public sealed class ManageModerationCasesHandler(
    IManageModerationCasesRepository repository,
    ManageModerationCasesProjector projector)
{
    public async ValueTask<ManageModerationCasesDecision> HandleAsync(
        ManageModerationCasesRequest request,
        CancellationToken cancellationToken)
    {
        var record = await repository.LoadAsync(
            request.SubjectId,
            request.CommunityId,
            cancellationToken) ?? new(
                request.SubjectId,
                request.CommunityId,
                "missing",
                request.ExpectedVersion,
                IsAuthorized: false,
                IsAvailable: false);
        var policy = new ManageModerationCasesPolicy();
        var decision = request.Action switch
        {
            "CreateACaseWithDurableEvidence" => policy.CreateACaseWithDurableEvidence(record, request),
            "TriageAssignAndEscalateCases" => policy.TriageAssignAndEscalateCases(record, request),
            "RestrictAndRetainSensitiveEvidence" => policy.RestrictAndRetainSensitiveEvidence(record, request),
            _ => new(
                "unknown",
                FeatureDecisionKind.Invalid,
                "unknown_feature_action",
                record.State,
                record.Version)
        };

        if (!decision.IsAccepted)
        {
            return decision;
        }

        await repository.CommitAsync(record, decision, cancellationToken);
        await projector.EnqueueAsync(request, decision, cancellationToken);
        return decision;
    }
}
