// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;
using CommunityStarter.Domain.GeneratedFeatures;

namespace CommunityStarter.Application.GeneratedFeatures;

public interface IMeasureReliabilityCapacityRepository
{
    ValueTask<MeasureReliabilityCapacityRecord?> LoadAsync(
        Guid subjectId,
        Guid? communityId,
        CancellationToken cancellationToken);

    ValueTask CommitAsync(
        MeasureReliabilityCapacityRecord current,
        MeasureReliabilityCapacityDecision decision,
        CancellationToken cancellationToken);
}

public sealed class MeasureReliabilityCapacityProjector(IFeatureProjectionSink sink)
{
    public ValueTask EnqueueAsync(
        MeasureReliabilityCapacityRequest request,
        MeasureReliabilityCapacityDecision decision,
        CancellationToken cancellationToken) =>
        sink.EnqueueAsync(
            MeasureReliabilityCapacityDescriptor.Slug,
            request.SubjectId,
            request.CommunityId,
            decision.RequirementId,
            decision.ResultingVersion,
            cancellationToken);
}

public sealed class MeasureReliabilityCapacityHandler(
    IMeasureReliabilityCapacityRepository repository,
    MeasureReliabilityCapacityProjector projector)
{
    public async ValueTask<MeasureReliabilityCapacityDecision> HandleAsync(
        MeasureReliabilityCapacityRequest request,
        CancellationToken cancellationToken)
    {
        var record = await repository.LoadAsync(
            request.SubjectId,
            request.CommunityId,
            cancellationToken) ?? new(
                request.SubjectId,
                request.CommunityId,
                "missing",
                request.ExpectedVersion,
                IsAuthorized: false,
                IsAvailable: false);
        var policy = new MeasureReliabilityCapacityPolicy();
        var decision = request.Action switch
        {
            "DefineAndReportServiceObjectives" => policy.DefineAndReportServiceObjectives(record, request),
            "EnforcePerformanceAndResourceBudgets" => policy.EnforcePerformanceAndResourceBudgets(record, request),
            "DegradeSafelyDuringDependencyFailure" => policy.DegradeSafelyDuringDependencyFailure(record, request),
            _ => new(
                "unknown",
                FeatureDecisionKind.Invalid,
                "unknown_feature_action",
                record.State,
                record.Version)
        };

        if (!decision.IsAccepted)
        {
            return decision;
        }

        await repository.CommitAsync(record, decision, cancellationToken);
        await projector.EnqueueAsync(request, decision, cancellationToken);
        return decision;
    }
}
