// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;
using CommunityStarter.Domain.GeneratedFeatures;

namespace CommunityStarter.Application.GeneratedFeatures;

public interface IMinimizePersonalDataUseRepository
{
    ValueTask<MinimizePersonalDataUseRecord?> LoadAsync(
        Guid subjectId,
        Guid? communityId,
        CancellationToken cancellationToken);

    ValueTask CommitAsync(
        MinimizePersonalDataUseRecord current,
        MinimizePersonalDataUseDecision decision,
        CancellationToken cancellationToken);
}

public sealed class MinimizePersonalDataUseProjector(IFeatureProjectionSink sink)
{
    public ValueTask EnqueueAsync(
        MinimizePersonalDataUseRequest request,
        MinimizePersonalDataUseDecision decision,
        CancellationToken cancellationToken) =>
        sink.EnqueueAsync(
            MinimizePersonalDataUseDescriptor.Slug,
            request.SubjectId,
            request.CommunityId,
            decision.RequirementId,
            decision.ResultingVersion,
            cancellationToken);
}

public sealed class MinimizePersonalDataUseHandler(
    IMinimizePersonalDataUseRepository repository,
    MinimizePersonalDataUseProjector projector)
{
    public async ValueTask<MinimizePersonalDataUseDecision> HandleAsync(
        MinimizePersonalDataUseRequest request,
        CancellationToken cancellationToken)
    {
        var record = await repository.LoadAsync(
            request.SubjectId,
            request.CommunityId,
            cancellationToken) ?? new(
                request.SubjectId,
                request.CommunityId,
                "missing",
                request.ExpectedVersion,
                IsAuthorized: false,
                IsAvailable: false);
        var policy = new MinimizePersonalDataUsePolicy();
        var decision = request.Action switch
        {
            "MaintainAPersonalDataInventory" => policy.MaintainAPersonalDataInventory(record, request),
            "ObtainAndHonorOptionalProcessingChoices" => policy.ObtainAndHonorOptionalProcessingChoices(record, request),
            "ApplyPrivacyPreservingDefaults" => policy.ApplyPrivacyPreservingDefaults(record, request),
            _ => new(
                "unknown",
                FeatureDecisionKind.Invalid,
                "unknown_feature_action",
                record.State,
                record.Version)
        };

        if (!decision.IsAccepted)
        {
            return decision;
        }

        await repository.CommitAsync(record, decision, cancellationToken);
        await projector.EnqueueAsync(request, decision, cancellationToken);
        return decision;
    }
}
