// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;
using CommunityStarter.Domain.GeneratedFeatures;

namespace CommunityStarter.Application.GeneratedFeatures;

public interface IObserveAccessProtectionRepository
{
    ValueTask<ObserveAccessProtectionRecord?> LoadAsync(
        Guid subjectId,
        Guid? communityId,
        CancellationToken cancellationToken);

    ValueTask CommitAsync(
        ObserveAccessProtectionRecord current,
        ObserveAccessProtectionDecision decision,
        CancellationToken cancellationToken);
}

public sealed class ObserveAccessProtectionProjector(IFeatureProjectionSink sink)
{
    public ValueTask EnqueueAsync(
        ObserveAccessProtectionRequest request,
        ObserveAccessProtectionDecision decision,
        CancellationToken cancellationToken) =>
        sink.EnqueueAsync(
            ObserveAccessProtectionDescriptor.Slug,
            request.SubjectId,
            request.CommunityId,
            decision.RequirementId,
            decision.ResultingVersion,
            cancellationToken);
}

public sealed class ObserveAccessProtectionHandler(
    IObserveAccessProtectionRepository repository,
    ObserveAccessProtectionProjector projector)
{
    public async ValueTask<ObserveAccessProtectionDecision> HandleAsync(
        ObserveAccessProtectionRequest request,
        CancellationToken cancellationToken)
    {
        var record = await repository.LoadAsync(
            request.SubjectId,
            request.CommunityId,
            cancellationToken) ?? new(
                request.SubjectId,
                request.CommunityId,
                "missing",
                request.ExpectedVersion,
                IsAuthorized: false,
                IsAvailable: false);
        var policy = new ObserveAccessProtectionPolicy();
        var decision = request.Action switch
        {
            "LimitSensitiveAttempts" => policy.LimitSensitiveAttempts(record, request),
            "RecordSecurityEvents" => policy.RecordSecurityEvents(record, request),
            _ => new(
                "unknown",
                FeatureDecisionKind.Invalid,
                "unknown_feature_action",
                record.State,
                record.Version)
        };

        if (!decision.IsAccepted)
        {
            return decision;
        }

        await repository.CommitAsync(record, decision, cancellationToken);
        await projector.EnqueueAsync(request, decision, cancellationToken);
        return decision;
    }
}
