// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;
using CommunityStarter.Domain.GeneratedFeatures;

namespace CommunityStarter.Application.GeneratedFeatures;

public interface IObserveSystemProductHealthRepository
{
    ValueTask<ObserveSystemProductHealthRecord?> LoadAsync(
        Guid subjectId,
        Guid? communityId,
        CancellationToken cancellationToken);

    ValueTask CommitAsync(
        ObserveSystemProductHealthRecord current,
        ObserveSystemProductHealthDecision decision,
        CancellationToken cancellationToken);
}

public sealed class ObserveSystemProductHealthProjector(IFeatureProjectionSink sink)
{
    public ValueTask EnqueueAsync(
        ObserveSystemProductHealthRequest request,
        ObserveSystemProductHealthDecision decision,
        CancellationToken cancellationToken) =>
        sink.EnqueueAsync(
            ObserveSystemProductHealthDescriptor.Slug,
            request.SubjectId,
            request.CommunityId,
            decision.RequirementId,
            decision.ResultingVersion,
            cancellationToken);
}

public sealed class ObserveSystemProductHealthHandler(
    IObserveSystemProductHealthRepository repository,
    ObserveSystemProductHealthProjector projector)
{
    public async ValueTask<ObserveSystemProductHealthDecision> HandleAsync(
        ObserveSystemProductHealthRequest request,
        CancellationToken cancellationToken)
    {
        var record = await repository.LoadAsync(
            request.SubjectId,
            request.CommunityId,
            cancellationToken) ?? new(
                request.SubjectId,
                request.CommunityId,
                "missing",
                request.ExpectedVersion,
                IsAuthorized: false,
                IsAvailable: false);
        var policy = new ObserveSystemProductHealthPolicy();
        var decision = request.Action switch
        {
            "CorrelateStructuredOperationalTelemetry" => policy.CorrelateStructuredOperationalTelemetry(record, request),
            "MeasureTechnicalAndProductHealth" => policy.MeasureTechnicalAndProductHealth(record, request),
            "DistinguishLivenessReadinessAndDependencyHealth" => policy.DistinguishLivenessReadinessAndDependencyHealth(record, request),
            "ProvideOwnedOperationalDashboards" => policy.ProvideOwnedOperationalDashboards(record, request),
            _ => new(
                "unknown",
                FeatureDecisionKind.Invalid,
                "unknown_feature_action",
                record.State,
                record.Version)
        };

        if (!decision.IsAccepted)
        {
            return decision;
        }

        await repository.CommitAsync(record, decision, cancellationToken);
        await projector.EnqueueAsync(request, decision, cancellationToken);
        return decision;
    }
}
