// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;
using CommunityStarter.Domain.GeneratedFeatures;

namespace CommunityStarter.Application.GeneratedFeatures;

public interface IOperateSecurityReadinessRepository
{
    ValueTask<OperateSecurityReadinessRecord?> LoadAsync(
        Guid subjectId,
        Guid? communityId,
        CancellationToken cancellationToken);

    ValueTask CommitAsync(
        OperateSecurityReadinessRecord current,
        OperateSecurityReadinessDecision decision,
        CancellationToken cancellationToken);
}

public sealed class OperateSecurityReadinessProjector(IFeatureProjectionSink sink)
{
    public ValueTask EnqueueAsync(
        OperateSecurityReadinessRequest request,
        OperateSecurityReadinessDecision decision,
        CancellationToken cancellationToken) =>
        sink.EnqueueAsync(
            OperateSecurityReadinessDescriptor.Slug,
            request.SubjectId,
            request.CommunityId,
            decision.RequirementId,
            decision.ResultingVersion,
            cancellationToken);
}

public sealed class OperateSecurityReadinessHandler(
    IOperateSecurityReadinessRepository repository,
    OperateSecurityReadinessProjector projector)
{
    public async ValueTask<OperateSecurityReadinessDecision> HandleAsync(
        OperateSecurityReadinessRequest request,
        CancellationToken cancellationToken)
    {
        var record = await repository.LoadAsync(
            request.SubjectId,
            request.CommunityId,
            cancellationToken) ?? new(
                request.SubjectId,
                request.CommunityId,
                "missing",
                request.ExpectedVersion,
                IsAuthorized: false,
                IsAvailable: false);
        var policy = new OperateSecurityReadinessPolicy();
        var decision = request.Action switch
        {
            "VulnerabilitiesHaveAPrivateReportingAndRemediationPath" => policy.VulnerabilitiesHaveAPrivateReportingAndRemediationPath(record, request),
            "PrivacyConsentRetentionAndAnalyticsPurposeAreDeclared" => policy.PrivacyConsentRetentionAndAnalyticsPurposeAreDeclared(record, request),
            "ProductionSecurityClaimsDistinguishChecksFromIndependentReview" => policy.ProductionSecurityClaimsDistinguishChecksFromIndependentReview(record, request),
            _ => new(
                "unknown",
                FeatureDecisionKind.Invalid,
                "unknown_feature_action",
                record.State,
                record.Version)
        };

        if (!decision.IsAccepted)
        {
            return decision;
        }

        await repository.CommitAsync(record, decision, cancellationToken);
        await projector.EnqueueAsync(request, decision, cancellationToken);
        return decision;
    }
}
