// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;
using CommunityStarter.Domain.GeneratedFeatures;

namespace CommunityStarter.Application.GeneratedFeatures;

public interface IPreserveCommunityIntegrityRepository
{
    ValueTask<PreserveCommunityIntegrityRecord?> LoadAsync(
        Guid subjectId,
        Guid? communityId,
        CancellationToken cancellationToken);

    ValueTask CommitAsync(
        PreserveCommunityIntegrityRecord current,
        PreserveCommunityIntegrityDecision decision,
        CancellationToken cancellationToken);
}

public sealed class PreserveCommunityIntegrityProjector(IFeatureProjectionSink sink)
{
    public ValueTask EnqueueAsync(
        PreserveCommunityIntegrityRequest request,
        PreserveCommunityIntegrityDecision decision,
        CancellationToken cancellationToken) =>
        sink.EnqueueAsync(
            PreserveCommunityIntegrityDescriptor.Slug,
            request.SubjectId,
            request.CommunityId,
            decision.RequirementId,
            decision.ResultingVersion,
            cancellationToken);
}

public sealed class PreserveCommunityIntegrityHandler(
    IPreserveCommunityIntegrityRepository repository,
    PreserveCommunityIntegrityProjector projector)
{
    public async ValueTask<PreserveCommunityIntegrityDecision> HandleAsync(
        PreserveCommunityIntegrityRequest request,
        CancellationToken cancellationToken)
    {
        var record = await repository.LoadAsync(
            request.SubjectId,
            request.CommunityId,
            cancellationToken) ?? new(
                request.SubjectId,
                request.CommunityId,
                "missing",
                request.ExpectedVersion,
                IsAuthorized: false,
                IsAvailable: false);
        var policy = new PreserveCommunityIntegrityPolicy();
        var decision = request.Action switch
        {
            "IsolateCommunityState" => policy.IsolateCommunityState(record, request),
            "EnforceLimitsAndConcurrency" => policy.EnforceLimitsAndConcurrency(record, request),
            _ => new(
                "unknown",
                FeatureDecisionKind.Invalid,
                "unknown_feature_action",
                record.State,
                record.Version)
        };

        if (!decision.IsAccepted)
        {
            return decision;
        }

        await repository.CommitAsync(record, decision, cancellationToken);
        await projector.EnqueueAsync(request, decision, cancellationToken);
        return decision;
    }
}
