// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;
using CommunityStarter.Domain.GeneratedFeatures;

namespace CommunityStarter.Application.GeneratedFeatures;

public interface IPreserveFullStackBoundariesRepository
{
    ValueTask<PreserveFullStackBoundariesRecord?> LoadAsync(
        Guid subjectId,
        Guid? communityId,
        CancellationToken cancellationToken);

    ValueTask CommitAsync(
        PreserveFullStackBoundariesRecord current,
        PreserveFullStackBoundariesDecision decision,
        CancellationToken cancellationToken);
}

public sealed class PreserveFullStackBoundariesProjector(IFeatureProjectionSink sink)
{
    public ValueTask EnqueueAsync(
        PreserveFullStackBoundariesRequest request,
        PreserveFullStackBoundariesDecision decision,
        CancellationToken cancellationToken) =>
        sink.EnqueueAsync(
            PreserveFullStackBoundariesDescriptor.Slug,
            request.SubjectId,
            request.CommunityId,
            decision.RequirementId,
            decision.ResultingVersion,
            cancellationToken);
}

public sealed class PreserveFullStackBoundariesHandler(
    IPreserveFullStackBoundariesRepository repository,
    PreserveFullStackBoundariesProjector projector)
{
    public async ValueTask<PreserveFullStackBoundariesDecision> HandleAsync(
        PreserveFullStackBoundariesRequest request,
        CancellationToken cancellationToken)
    {
        var record = await repository.LoadAsync(
            request.SubjectId,
            request.CommunityId,
            cancellationToken) ?? new(
                request.SubjectId,
                request.CommunityId,
                "missing",
                request.ExpectedVersion,
                IsAuthorized: false,
                IsAvailable: false);
        var policy = new PreserveFullStackBoundariesPolicy();
        var decision = request.Action switch
        {
            "RuntimeAndRepositorySurfacesAreExplicit" => policy.RuntimeAndRepositorySurfacesAreExplicit(record, request),
            "BackendDependenciesPointInward" => policy.BackendDependenciesPointInward(record, request),
            "AngularLibrariesHaveStableOwnership" => policy.AngularLibrariesHaveStableOwnership(record, request),
            _ => new(
                "unknown",
                FeatureDecisionKind.Invalid,
                "unknown_feature_action",
                record.State,
                record.Version)
        };

        if (!decision.IsAccepted)
        {
            return decision;
        }

        await repository.CommitAsync(record, decision, cancellationToken);
        await projector.EnqueueAsync(request, decision, cancellationToken);
        return decision;
    }
}
