// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;
using CommunityStarter.Domain.GeneratedFeatures;

namespace CommunityStarter.Application.GeneratedFeatures;

public interface IProtectDataPersistenceIntegrityRepository
{
    ValueTask<ProtectDataPersistenceIntegrityRecord?> LoadAsync(
        Guid subjectId,
        Guid? communityId,
        CancellationToken cancellationToken);

    ValueTask CommitAsync(
        ProtectDataPersistenceIntegrityRecord current,
        ProtectDataPersistenceIntegrityDecision decision,
        CancellationToken cancellationToken);
}

public sealed class ProtectDataPersistenceIntegrityProjector(IFeatureProjectionSink sink)
{
    public ValueTask EnqueueAsync(
        ProtectDataPersistenceIntegrityRequest request,
        ProtectDataPersistenceIntegrityDecision decision,
        CancellationToken cancellationToken) =>
        sink.EnqueueAsync(
            ProtectDataPersistenceIntegrityDescriptor.Slug,
            request.SubjectId,
            request.CommunityId,
            decision.RequirementId,
            decision.ResultingVersion,
            cancellationToken);
}

public sealed class ProtectDataPersistenceIntegrityHandler(
    IProtectDataPersistenceIntegrityRepository repository,
    ProtectDataPersistenceIntegrityProjector projector)
{
    public async ValueTask<ProtectDataPersistenceIntegrityDecision> HandleAsync(
        ProtectDataPersistenceIntegrityRequest request,
        CancellationToken cancellationToken)
    {
        var record = await repository.LoadAsync(
            request.SubjectId,
            request.CommunityId,
            cancellationToken) ?? new(
                request.SubjectId,
                request.CommunityId,
                "missing",
                request.ExpectedVersion,
                IsAuthorized: false,
                IsAvailable: false);
        var policy = new ProtectDataPersistenceIntegrityPolicy();
        var decision = request.Action switch
        {
            "RelationalSchemaEvolutionIsForwardAndRehearsable" => policy.RelationalSchemaEvolutionIsForwardAndRehearsable(record, request),
            "CommunityScopedReadsAreExplicitAndEfficient" => policy.CommunityScopedReadsAreExplicitAndEfficient(record, request),
            "TimeDemonstrationDataAndLifecycleStateAreDeliberate" => policy.TimeDemonstrationDataAndLifecycleStateAreDeliberate(record, request),
            _ => new(
                "unknown",
                FeatureDecisionKind.Invalid,
                "unknown_feature_action",
                record.State,
                record.Version)
        };

        if (!decision.IsAccepted)
        {
            return decision;
        }

        await repository.CommitAsync(record, decision, cancellationToken);
        await projector.EnqueueAsync(request, decision, cancellationToken);
        return decision;
    }
}
