// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;
using CommunityStarter.Domain.GeneratedFeatures;

namespace CommunityStarter.Application.GeneratedFeatures;

public interface IProtectSecretsDiagnosticsDataRepository
{
    ValueTask<ProtectSecretsDiagnosticsDataRecord?> LoadAsync(
        Guid subjectId,
        Guid? communityId,
        CancellationToken cancellationToken);

    ValueTask CommitAsync(
        ProtectSecretsDiagnosticsDataRecord current,
        ProtectSecretsDiagnosticsDataDecision decision,
        CancellationToken cancellationToken);
}

public sealed class ProtectSecretsDiagnosticsDataProjector(IFeatureProjectionSink sink)
{
    public ValueTask EnqueueAsync(
        ProtectSecretsDiagnosticsDataRequest request,
        ProtectSecretsDiagnosticsDataDecision decision,
        CancellationToken cancellationToken) =>
        sink.EnqueueAsync(
            ProtectSecretsDiagnosticsDataDescriptor.Slug,
            request.SubjectId,
            request.CommunityId,
            decision.RequirementId,
            decision.ResultingVersion,
            cancellationToken);
}

public sealed class ProtectSecretsDiagnosticsDataHandler(
    IProtectSecretsDiagnosticsDataRepository repository,
    ProtectSecretsDiagnosticsDataProjector projector)
{
    public async ValueTask<ProtectSecretsDiagnosticsDataDecision> HandleAsync(
        ProtectSecretsDiagnosticsDataRequest request,
        CancellationToken cancellationToken)
    {
        var record = await repository.LoadAsync(
            request.SubjectId,
            request.CommunityId,
            cancellationToken) ?? new(
                request.SubjectId,
                request.CommunityId,
                "missing",
                request.ExpectedVersion,
                IsAuthorized: false,
                IsAvailable: false);
        var policy = new ProtectSecretsDiagnosticsDataPolicy();
        var decision = request.Action switch
        {
            "SecretsStayOutsideSourceAndPlaceholdersFailSafely" => policy.SecretsStayOutsideSourceAndPlaceholdersFailSafely(record, request),
            "PublicFailuresAreSanitizedAndPrivateDiagnosticsAreRedacted" => policy.PublicFailuresAreSanitizedAndPrivateDiagnosticsAreRedacted(record, request),
            "SourceFixturesAndDemosContainNoRealPersonalData" => policy.SourceFixturesAndDemosContainNoRealPersonalData(record, request),
            "EncryptProtectedDataAndGovernKeys" => policy.EncryptProtectedDataAndGovernKeys(record, request),
            _ => new(
                "unknown",
                FeatureDecisionKind.Invalid,
                "unknown_feature_action",
                record.State,
                record.Version)
        };

        if (!decision.IsAccepted)
        {
            return decision;
        }

        await repository.CommitAsync(record, decision, cancellationToken);
        await projector.EnqueueAsync(request, decision, cancellationToken);
        return decision;
    }
}
