// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;
using CommunityStarter.Domain.GeneratedFeatures;

namespace CommunityStarter.Application.GeneratedFeatures;

public interface IProtectAuthenticatedSessionsRepository
{
    ValueTask<ProtectAuthenticatedSessionsRecord?> LoadAsync(
        Guid subjectId,
        Guid? communityId,
        CancellationToken cancellationToken);

    ValueTask CommitAsync(
        ProtectAuthenticatedSessionsRecord current,
        ProtectAuthenticatedSessionsDecision decision,
        CancellationToken cancellationToken);
}

public sealed class ProtectAuthenticatedSessionsProjector(IFeatureProjectionSink sink)
{
    public ValueTask EnqueueAsync(
        ProtectAuthenticatedSessionsRequest request,
        ProtectAuthenticatedSessionsDecision decision,
        CancellationToken cancellationToken) =>
        sink.EnqueueAsync(
            ProtectAuthenticatedSessionsDescriptor.Slug,
            request.SubjectId,
            request.CommunityId,
            decision.RequirementId,
            decision.ResultingVersion,
            cancellationToken);
}

public sealed class ProtectAuthenticatedSessionsHandler(
    IProtectAuthenticatedSessionsRepository repository,
    ProtectAuthenticatedSessionsProjector projector)
{
    public async ValueTask<ProtectAuthenticatedSessionsDecision> HandleAsync(
        ProtectAuthenticatedSessionsRequest request,
        CancellationToken cancellationToken)
    {
        var record = await repository.LoadAsync(
            request.SubjectId,
            request.CommunityId,
            cancellationToken) ?? new(
                request.SubjectId,
                request.CommunityId,
                "missing",
                request.ExpectedVersion,
                IsAuthorized: false,
                IsAvailable: false);
        var policy = new ProtectAuthenticatedSessionsPolicy();
        var decision = request.Action switch
        {
            "SignInWithoutEnumeration" => policy.SignInWithoutEnumeration(record, request),
            "RequireStrongerVerification" => policy.RequireStrongerVerification(record, request),
            "RotateAndRevokeSessions" => policy.RotateAndRevokeSessions(record, request),
            "IssueRestrictedRemediationSessions" => policy.IssueRestrictedRemediationSessions(record, request),
            "GovernStrongerFactorLifecycle" => policy.GovernStrongerFactorLifecycle(record, request),
            _ => new(
                "unknown",
                FeatureDecisionKind.Invalid,
                "unknown_feature_action",
                record.State,
                record.Version)
        };

        if (!decision.IsAccepted)
        {
            return decision;
        }

        await repository.CommitAsync(record, decision, cancellationToken);
        await projector.EnqueueAsync(request, decision, cancellationToken);
        return decision;
    }
}
