// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;
using CommunityStarter.Domain.GeneratedFeatures;

namespace CommunityStarter.Application.GeneratedFeatures;

public interface IProvideAngularComponentContractsRepository
{
    ValueTask<ProvideAngularComponentContractsRecord?> LoadAsync(
        Guid subjectId,
        Guid? communityId,
        CancellationToken cancellationToken);

    ValueTask CommitAsync(
        ProvideAngularComponentContractsRecord current,
        ProvideAngularComponentContractsDecision decision,
        CancellationToken cancellationToken);
}

public sealed class ProvideAngularComponentContractsProjector(IFeatureProjectionSink sink)
{
    public ValueTask EnqueueAsync(
        ProvideAngularComponentContractsRequest request,
        ProvideAngularComponentContractsDecision decision,
        CancellationToken cancellationToken) =>
        sink.EnqueueAsync(
            ProvideAngularComponentContractsDescriptor.Slug,
            request.SubjectId,
            request.CommunityId,
            decision.RequirementId,
            decision.ResultingVersion,
            cancellationToken);
}

public sealed class ProvideAngularComponentContractsHandler(
    IProvideAngularComponentContractsRepository repository,
    ProvideAngularComponentContractsProjector projector)
{
    public async ValueTask<ProvideAngularComponentContractsDecision> HandleAsync(
        ProvideAngularComponentContractsRequest request,
        CancellationToken cancellationToken)
    {
        var record = await repository.LoadAsync(
            request.SubjectId,
            request.CommunityId,
            cancellationToken) ?? new(
                request.SubjectId,
                request.CommunityId,
                "missing",
                request.ExpectedVersion,
                IsAuthorized: false,
                IsAvailable: false);
        var policy = new ProvideAngularComponentContractsPolicy();
        var decision = request.Action switch
        {
            "AngularSourceIsStrictFocusedAndAdjacent" => policy.AngularSourceIsStrictFocusedAndAdjacent(record, request),
            "PresentationalComponentsReceiveDataAndEmitIntent" => policy.PresentationalComponentsReceiveDataAndEmitIntent(record, request),
            "RemoteAndDerivedStateRemainExplicit" => policy.RemoteAndDerivedStateRemainExplicit(record, request),
            _ => new(
                "unknown",
                FeatureDecisionKind.Invalid,
                "unknown_feature_action",
                record.State,
                record.Version)
        };

        if (!decision.IsAccepted)
        {
            return decision;
        }

        await repository.CommitAsync(record, decision, cancellationToken);
        await projector.EnqueueAsync(request, decision, cancellationToken);
        return decision;
    }
}
