// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;
using CommunityStarter.Domain.GeneratedFeatures;

namespace CommunityStarter.Application.GeneratedFeatures;

public interface IPublishUnambiguousRoutesRepository
{
    ValueTask<PublishUnambiguousRoutesRecord?> LoadAsync(
        Guid subjectId,
        Guid? communityId,
        CancellationToken cancellationToken);

    ValueTask CommitAsync(
        PublishUnambiguousRoutesRecord current,
        PublishUnambiguousRoutesDecision decision,
        CancellationToken cancellationToken);
}

public sealed class PublishUnambiguousRoutesProjector(IFeatureProjectionSink sink)
{
    public ValueTask EnqueueAsync(
        PublishUnambiguousRoutesRequest request,
        PublishUnambiguousRoutesDecision decision,
        CancellationToken cancellationToken) =>
        sink.EnqueueAsync(
            PublishUnambiguousRoutesDescriptor.Slug,
            request.SubjectId,
            request.CommunityId,
            decision.RequirementId,
            decision.ResultingVersion,
            cancellationToken);
}

public sealed class PublishUnambiguousRoutesHandler(
    IPublishUnambiguousRoutesRepository repository,
    PublishUnambiguousRoutesProjector projector)
{
    public async ValueTask<PublishUnambiguousRoutesDecision> HandleAsync(
        PublishUnambiguousRoutesRequest request,
        CancellationToken cancellationToken)
    {
        var record = await repository.LoadAsync(
            request.SubjectId,
            request.CommunityId,
            cancellationToken) ?? new(
                request.SubjectId,
                request.CommunityId,
                "missing",
                request.ExpectedVersion,
                IsAuthorized: false,
                IsAvailable: false);
        var policy = new PublishUnambiguousRoutesPolicy();
        var decision = request.Action switch
        {
            "OneOriginPublishingAssemblesDeterministicAssets" => policy.OneOriginPublishingAssemblesDeterministicAssets(record, request),
            "RequestRoutingProtectsEveryRuntimeOwner" => policy.RequestRoutingProtectsEveryRuntimeOwner(record, request),
            "PublicToApplicationNavigationIsDeploymentConfigurable" => policy.PublicToApplicationNavigationIsDeploymentConfigurable(record, request),
            _ => new(
                "unknown",
                FeatureDecisionKind.Invalid,
                "unknown_feature_action",
                record.State,
                record.Version)
        };

        if (!decision.IsAccepted)
        {
            return decision;
        }

        await repository.CommitAsync(record, decision, cancellationToken);
        await projector.EnqueueAsync(request, decision, cancellationToken);
        return decision;
    }
}
