// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;
using CommunityStarter.Domain.GeneratedFeatures;

namespace CommunityStarter.Application.GeneratedFeatures;

public interface IRecordEngagementRepository
{
    ValueTask<RecordEngagementRecord?> LoadAsync(
        Guid subjectId,
        Guid? communityId,
        CancellationToken cancellationToken);

    ValueTask CommitAsync(
        RecordEngagementRecord current,
        RecordEngagementDecision decision,
        CancellationToken cancellationToken);
}

public sealed class RecordEngagementProjector(IFeatureProjectionSink sink)
{
    public ValueTask EnqueueAsync(
        RecordEngagementRequest request,
        RecordEngagementDecision decision,
        CancellationToken cancellationToken) =>
        sink.EnqueueAsync(
            RecordEngagementDescriptor.Slug,
            request.SubjectId,
            request.CommunityId,
            decision.RequirementId,
            decision.ResultingVersion,
            cancellationToken);
}

public sealed class RecordEngagementHandler(
    IRecordEngagementRepository repository,
    RecordEngagementProjector projector)
{
    public async ValueTask<RecordEngagementDecision> HandleAsync(
        RecordEngagementRequest request,
        CancellationToken cancellationToken)
    {
        var record = await repository.LoadAsync(
            request.SubjectId,
            request.CommunityId,
            cancellationToken) ?? new(
                request.SubjectId,
                request.CommunityId,
                "missing",
                request.ExpectedVersion,
                IsAuthorized: false,
                IsAvailable: false);
        var policy = new RecordEngagementPolicy();
        var decision = request.Action switch
        {
            "AddAndRemoveAReaction" => policy.AddAndRemoveAReaction(record, request),
            "SaveAndRemoveABookmark" => policy.SaveAndRemoveABookmark(record, request),
            "PresentEngagementState" => policy.PresentEngagementState(record, request),
            _ => new(
                "unknown",
                FeatureDecisionKind.Invalid,
                "unknown_feature_action",
                record.State,
                record.Version)
        };

        if (!decision.IsAccepted)
        {
            return decision;
        }

        await repository.CommitAsync(record, decision, cancellationToken);
        await projector.EnqueueAsync(request, decision, cancellationToken);
        return decision;
    }
}
