// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;
using CommunityStarter.Domain.GeneratedFeatures;

namespace CommunityStarter.Application.GeneratedFeatures;

public interface IReconcileRealtimeExperienceRepository
{
    ValueTask<ReconcileRealtimeExperienceRecord?> LoadAsync(
        Guid subjectId,
        Guid? communityId,
        CancellationToken cancellationToken);

    ValueTask CommitAsync(
        ReconcileRealtimeExperienceRecord current,
        ReconcileRealtimeExperienceDecision decision,
        CancellationToken cancellationToken);
}

public sealed class ReconcileRealtimeExperienceProjector(IFeatureProjectionSink sink)
{
    public ValueTask EnqueueAsync(
        ReconcileRealtimeExperienceRequest request,
        ReconcileRealtimeExperienceDecision decision,
        CancellationToken cancellationToken) =>
        sink.EnqueueAsync(
            ReconcileRealtimeExperienceDescriptor.Slug,
            request.SubjectId,
            request.CommunityId,
            decision.RequirementId,
            decision.ResultingVersion,
            cancellationToken);
}

public sealed class ReconcileRealtimeExperienceHandler(
    IReconcileRealtimeExperienceRepository repository,
    ReconcileRealtimeExperienceProjector projector)
{
    public async ValueTask<ReconcileRealtimeExperienceDecision> HandleAsync(
        ReconcileRealtimeExperienceRequest request,
        CancellationToken cancellationToken)
    {
        var record = await repository.LoadAsync(
            request.SubjectId,
            request.CommunityId,
            cancellationToken) ?? new(
                request.SubjectId,
                request.CommunityId,
                "missing",
                request.ExpectedVersion,
                IsAuthorized: false,
                IsAvailable: false);
        var policy = new ReconcileRealtimeExperiencePolicy();
        var decision = request.Action switch
        {
            "PublishOnlyCommittedMessageEvents" => policy.PublishOnlyCommittedMessageEvents(record, request),
            "ReconnectAndReconcileFromTheAPI" => policy.ReconnectAndReconcileFromTheAPI(record, request),
            "ScopeRealtimeSubscriptionsOnTheServer" => policy.ScopeRealtimeSubscriptionsOnTheServer(record, request),
            _ => new(
                "unknown",
                FeatureDecisionKind.Invalid,
                "unknown_feature_action",
                record.State,
                record.Version)
        };

        if (!decision.IsAccepted)
        {
            return decision;
        }

        await repository.CommitAsync(record, decision, cancellationToken);
        await projector.EnqueueAsync(request, decision, cancellationToken);
        return decision;
    }
}
