// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;
using CommunityStarter.Domain.GeneratedFeatures;

namespace CommunityStarter.Application.GeneratedFeatures;

public interface IRecoverDataServicesRepository
{
    ValueTask<RecoverDataServicesRecord?> LoadAsync(
        Guid subjectId,
        Guid? communityId,
        CancellationToken cancellationToken);

    ValueTask CommitAsync(
        RecoverDataServicesRecord current,
        RecoverDataServicesDecision decision,
        CancellationToken cancellationToken);
}

public sealed class RecoverDataServicesProjector(IFeatureProjectionSink sink)
{
    public ValueTask EnqueueAsync(
        RecoverDataServicesRequest request,
        RecoverDataServicesDecision decision,
        CancellationToken cancellationToken) =>
        sink.EnqueueAsync(
            RecoverDataServicesDescriptor.Slug,
            request.SubjectId,
            request.CommunityId,
            decision.RequirementId,
            decision.ResultingVersion,
            cancellationToken);
}

public sealed class RecoverDataServicesHandler(
    IRecoverDataServicesRepository repository,
    RecoverDataServicesProjector projector)
{
    public async ValueTask<RecoverDataServicesDecision> HandleAsync(
        RecoverDataServicesRequest request,
        CancellationToken cancellationToken)
    {
        var record = await repository.LoadAsync(
            request.SubjectId,
            request.CommunityId,
            cancellationToken) ?? new(
                request.SubjectId,
                request.CommunityId,
                "missing",
                request.ExpectedVersion,
                IsAuthorized: false,
                IsAvailable: false);
        var policy = new RecoverDataServicesPolicy();
        var decision = request.Action switch
        {
            "CreateAndVerifyProtectedBackups" => policy.CreateAndVerifyProtectedBackups(record, request),
            "ProveRecoveryObjectivesThroughRestoreDrills" => policy.ProveRecoveryObjectivesThroughRestoreDrills(record, request),
            "ReconcileDerivedStateAfterRecovery" => policy.ReconcileDerivedStateAfterRecovery(record, request),
            _ => new(
                "unknown",
                FeatureDecisionKind.Invalid,
                "unknown_feature_action",
                record.State,
                record.Version)
        };

        if (!decision.IsAccepted)
        {
            return decision;
        }

        await repository.CommitAsync(record, decision, cancellationToken);
        await projector.EnqueueAsync(request, decision, cancellationToken);
        return decision;
    }
}
