// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;
using CommunityStarter.Domain.GeneratedFeatures;

namespace CommunityStarter.Application.GeneratedFeatures;

public interface IReportPolicyHarmRepository
{
    ValueTask<ReportPolicyHarmRecord?> LoadAsync(
        Guid subjectId,
        Guid? communityId,
        CancellationToken cancellationToken);

    ValueTask CommitAsync(
        ReportPolicyHarmRecord current,
        ReportPolicyHarmDecision decision,
        CancellationToken cancellationToken);
}

public sealed class ReportPolicyHarmProjector(IFeatureProjectionSink sink)
{
    public ValueTask EnqueueAsync(
        ReportPolicyHarmRequest request,
        ReportPolicyHarmDecision decision,
        CancellationToken cancellationToken) =>
        sink.EnqueueAsync(
            ReportPolicyHarmDescriptor.Slug,
            request.SubjectId,
            request.CommunityId,
            decision.RequirementId,
            decision.ResultingVersion,
            cancellationToken);
}

public sealed class ReportPolicyHarmHandler(
    IReportPolicyHarmRepository repository,
    ReportPolicyHarmProjector projector)
{
    public async ValueTask<ReportPolicyHarmDecision> HandleAsync(
        ReportPolicyHarmRequest request,
        CancellationToken cancellationToken)
    {
        var record = await repository.LoadAsync(
            request.SubjectId,
            request.CommunityId,
            cancellationToken) ?? new(
                request.SubjectId,
                request.CommunityId,
                "missing",
                request.ExpectedVersion,
                IsAuthorized: false,
                IsAvailable: false);
        var policy = new ReportPolicyHarmPolicy();
        var decision = request.Action switch
        {
            "ApplyVersionedPolicyPrecedence" => policy.ApplyVersionedPolicyPrecedence(record, request),
            "SubmitASafeReport" => policy.SubmitASafeReport(record, request),
            "ProtectReportersAndLimitAbuse" => policy.ProtectReportersAndLimitAbuse(record, request),
            "PreserveABoundedPriorViewReportingPath" => policy.PreserveABoundedPriorViewReportingPath(record, request),
            _ => new(
                "unknown",
                FeatureDecisionKind.Invalid,
                "unknown_feature_action",
                record.State,
                record.Version)
        };

        if (!decision.IsAccepted)
        {
            return decision;
        }

        await repository.CommitAsync(record, decision, cancellationToken);
        await projector.EnqueueAsync(request, decision, cancellationToken);
        return decision;
    }
}
