// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;
using CommunityStarter.Domain.GeneratedFeatures;

namespace CommunityStarter.Application.GeneratedFeatures;

public interface IReproduceCleanCheckoutRepository
{
    ValueTask<ReproduceCleanCheckoutRecord?> LoadAsync(
        Guid subjectId,
        Guid? communityId,
        CancellationToken cancellationToken);

    ValueTask CommitAsync(
        ReproduceCleanCheckoutRecord current,
        ReproduceCleanCheckoutDecision decision,
        CancellationToken cancellationToken);
}

public sealed class ReproduceCleanCheckoutProjector(IFeatureProjectionSink sink)
{
    public ValueTask EnqueueAsync(
        ReproduceCleanCheckoutRequest request,
        ReproduceCleanCheckoutDecision decision,
        CancellationToken cancellationToken) =>
        sink.EnqueueAsync(
            ReproduceCleanCheckoutDescriptor.Slug,
            request.SubjectId,
            request.CommunityId,
            decision.RequirementId,
            decision.ResultingVersion,
            cancellationToken);
}

public sealed class ReproduceCleanCheckoutHandler(
    IReproduceCleanCheckoutRepository repository,
    ReproduceCleanCheckoutProjector projector)
{
    public async ValueTask<ReproduceCleanCheckoutDecision> HandleAsync(
        ReproduceCleanCheckoutRequest request,
        CancellationToken cancellationToken)
    {
        var record = await repository.LoadAsync(
            request.SubjectId,
            request.CommunityId,
            cancellationToken) ?? new(
                request.SubjectId,
                request.CommunityId,
                "missing",
                request.ExpectedVersion,
                IsAuthorized: false,
                IsAvailable: false);
        var policy = new ReproduceCleanCheckoutPolicy();
        var decision = request.Action switch
        {
            "PinAndValidateDevelopmentToolchains" => policy.PinAndValidateDevelopmentToolchains(record, request),
            "ExposeCanonicalRepositoryCommands" => policy.ExposeCanonicalRepositoryCommands(record, request),
            "ProvisionRepeatableLocalDependencies" => policy.ProvisionRepeatableLocalDependencies(record, request),
            "ValidateEnvironmentConfigurationAndSecrets" => policy.ValidateEnvironmentConfigurationAndSecrets(record, request),
            _ => new(
                "unknown",
                FeatureDecisionKind.Invalid,
                "unknown_feature_action",
                record.State,
                record.Version)
        };

        if (!decision.IsAccepted)
        {
            return decision;
        }

        await repository.CommitAsync(record, decision, cancellationToken);
        await projector.EnqueueAsync(request, decision, cancellationToken);
        return decision;
    }
}
