// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;
using CommunityStarter.Domain.GeneratedFeatures;

namespace CommunityStarter.Application.GeneratedFeatures;

public interface IRespondToIncidentsRepository
{
    ValueTask<RespondToIncidentsRecord?> LoadAsync(
        Guid subjectId,
        Guid? communityId,
        CancellationToken cancellationToken);

    ValueTask CommitAsync(
        RespondToIncidentsRecord current,
        RespondToIncidentsDecision decision,
        CancellationToken cancellationToken);
}

public sealed class RespondToIncidentsProjector(IFeatureProjectionSink sink)
{
    public ValueTask EnqueueAsync(
        RespondToIncidentsRequest request,
        RespondToIncidentsDecision decision,
        CancellationToken cancellationToken) =>
        sink.EnqueueAsync(
            RespondToIncidentsDescriptor.Slug,
            request.SubjectId,
            request.CommunityId,
            decision.RequirementId,
            decision.ResultingVersion,
            cancellationToken);
}

public sealed class RespondToIncidentsHandler(
    IRespondToIncidentsRepository repository,
    RespondToIncidentsProjector projector)
{
    public async ValueTask<RespondToIncidentsDecision> HandleAsync(
        RespondToIncidentsRequest request,
        CancellationToken cancellationToken)
    {
        var record = await repository.LoadAsync(
            request.SubjectId,
            request.CommunityId,
            cancellationToken) ?? new(
                request.SubjectId,
                request.CommunityId,
                "missing",
                request.ExpectedVersion,
                IsAuthorized: false,
                IsAvailable: false);
        var policy = new RespondToIncidentsPolicy();
        var decision = request.Action switch
        {
            "RouteActionableAlertsToAnOwner" => policy.RouteActionableAlertsToAnOwner(record, request),
            "RunAndReviewIncidentsConsistently" => policy.RunAndReviewIncidentsConsistently(record, request),
            "MaintainExecutableOperationalRunbooks" => policy.MaintainExecutableOperationalRunbooks(record, request),
            _ => new(
                "unknown",
                FeatureDecisionKind.Invalid,
                "unknown_feature_action",
                record.State,
                record.Version)
        };

        if (!decision.IsAccepted)
        {
            return decision;
        }

        await repository.CommitAsync(record, decision, cancellationToken);
        await projector.EnqueueAsync(request, decision, cancellationToken);
        return decision;
    }
}
