// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;
using CommunityStarter.Domain.GeneratedFeatures;

namespace CommunityStarter.Application.GeneratedFeatures;

public interface IReviewSafetyDecisionsRepository
{
    ValueTask<ReviewSafetyDecisionsRecord?> LoadAsync(
        Guid subjectId,
        Guid? communityId,
        CancellationToken cancellationToken);

    ValueTask CommitAsync(
        ReviewSafetyDecisionsRecord current,
        ReviewSafetyDecisionsDecision decision,
        CancellationToken cancellationToken);
}

public sealed class ReviewSafetyDecisionsProjector(IFeatureProjectionSink sink)
{
    public ValueTask EnqueueAsync(
        ReviewSafetyDecisionsRequest request,
        ReviewSafetyDecisionsDecision decision,
        CancellationToken cancellationToken) =>
        sink.EnqueueAsync(
            ReviewSafetyDecisionsDescriptor.Slug,
            request.SubjectId,
            request.CommunityId,
            decision.RequirementId,
            decision.ResultingVersion,
            cancellationToken);
}

public sealed class ReviewSafetyDecisionsHandler(
    IReviewSafetyDecisionsRepository repository,
    ReviewSafetyDecisionsProjector projector)
{
    public async ValueTask<ReviewSafetyDecisionsDecision> HandleAsync(
        ReviewSafetyDecisionsRequest request,
        CancellationToken cancellationToken)
    {
        var record = await repository.LoadAsync(
            request.SubjectId,
            request.CommunityId,
            cancellationToken) ?? new(
                request.SubjectId,
                request.CommunityId,
                "missing",
                request.ExpectedVersion,
                IsAuthorized: false,
                IsAvailable: false);
        var policy = new ReviewSafetyDecisionsPolicy();
        var decision = request.Action switch
        {
            "AdjudicateEligibleAppealsAndRepairState" => policy.AdjudicateEligibleAppealsAndRepairState(record, request),
            "AuditAndMeasureSafetyOutcomes" => policy.AuditAndMeasureSafetyOutcomes(record, request),
            _ => new(
                "unknown",
                FeatureDecisionKind.Invalid,
                "unknown_feature_action",
                record.State,
                record.Version)
        };

        if (!decision.IsAccepted)
        {
            return decision;
        }

        await repository.CommitAsync(record, decision, cancellationToken);
        await projector.EnqueueAsync(request, decision, cancellationToken);
        return decision;
    }
}
