// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;
using CommunityStarter.Domain.GeneratedFeatures;

namespace CommunityStarter.Application.GeneratedFeatures;

public interface ISearchAuthorizedContentRepository
{
    ValueTask<SearchAuthorizedContentRecord?> LoadAsync(
        Guid subjectId,
        Guid? communityId,
        CancellationToken cancellationToken);

    ValueTask CommitAsync(
        SearchAuthorizedContentRecord current,
        SearchAuthorizedContentDecision decision,
        CancellationToken cancellationToken);
}

public sealed class SearchAuthorizedContentProjector(IFeatureProjectionSink sink)
{
    public ValueTask EnqueueAsync(
        SearchAuthorizedContentRequest request,
        SearchAuthorizedContentDecision decision,
        CancellationToken cancellationToken) =>
        sink.EnqueueAsync(
            SearchAuthorizedContentDescriptor.Slug,
            request.SubjectId,
            request.CommunityId,
            decision.RequirementId,
            decision.ResultingVersion,
            cancellationToken);
}

public sealed class SearchAuthorizedContentHandler(
    ISearchAuthorizedContentRepository repository,
    SearchAuthorizedContentProjector projector)
{
    public async ValueTask<SearchAuthorizedContentDecision> HandleAsync(
        SearchAuthorizedContentRequest request,
        CancellationToken cancellationToken)
    {
        var record = await repository.LoadAsync(
            request.SubjectId,
            request.CommunityId,
            cancellationToken) ?? new(
                request.SubjectId,
                request.CommunityId,
                "missing",
                request.ExpectedVersion,
                IsAuthorized: false,
                IsAvailable: false);
        var policy = new SearchAuthorizedContentPolicy();
        var decision = request.Action switch
        {
            "SearchEligibleRecords" => policy.SearchEligibleRecords(record, request),
            "FilterAndPageSearchResults" => policy.FilterAndPageSearchResults(record, request),
            "RemoveStaleSearchResults" => policy.RemoveStaleSearchResults(record, request),
            _ => new(
                "unknown",
                FeatureDecisionKind.Invalid,
                "unknown_feature_action",
                record.State,
                record.Version)
        };

        if (!decision.IsAccepted)
        {
            return decision;
        }

        await repository.CommitAsync(record, decision, cancellationToken);
        await projector.EnqueueAsync(request, decision, cancellationToken);
        return decision;
    }
}
