// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;
using CommunityStarter.Domain.GeneratedFeatures;

namespace CommunityStarter.Application.GeneratedFeatures;

public interface ISpecializeStarterSafelyRepository
{
    ValueTask<SpecializeStarterSafelyRecord?> LoadAsync(
        Guid subjectId,
        Guid? communityId,
        CancellationToken cancellationToken);

    ValueTask CommitAsync(
        SpecializeStarterSafelyRecord current,
        SpecializeStarterSafelyDecision decision,
        CancellationToken cancellationToken);
}

public sealed class SpecializeStarterSafelyProjector(IFeatureProjectionSink sink)
{
    public ValueTask EnqueueAsync(
        SpecializeStarterSafelyRequest request,
        SpecializeStarterSafelyDecision decision,
        CancellationToken cancellationToken) =>
        sink.EnqueueAsync(
            SpecializeStarterSafelyDescriptor.Slug,
            request.SubjectId,
            request.CommunityId,
            decision.RequirementId,
            decision.ResultingVersion,
            cancellationToken);
}

public sealed class SpecializeStarterSafelyHandler(
    ISpecializeStarterSafelyRepository repository,
    SpecializeStarterSafelyProjector projector)
{
    public async ValueTask<SpecializeStarterSafelyDecision> HandleAsync(
        SpecializeStarterSafelyRequest request,
        CancellationToken cancellationToken)
    {
        var record = await repository.LoadAsync(
            request.SubjectId,
            request.CommunityId,
            cancellationToken) ?? new(
                request.SubjectId,
                request.CommunityId,
                "missing",
                request.ExpectedVersion,
                IsAuthorized: false,
                IsAvailable: false);
        var policy = new SpecializeStarterSafelyPolicy();
        var decision = request.Action switch
        {
            "ApplyAndVerifyProductIdentity" => policy.ApplyAndVerifyProductIdentity(record, request),
            "SpecializeTheSharedVisualLanguage" => policy.SpecializeTheSharedVisualLanguage(record, request),
            "ConfigureOptionalCapabilityProfiles" => policy.ConfigureOptionalCapabilityProfiles(record, request),
            "RecordProviderAndArchitectureDecisions" => policy.RecordProviderAndArchitectureDecisions(record, request),
            _ => new(
                "unknown",
                FeatureDecisionKind.Invalid,
                "unknown_feature_action",
                record.State,
                record.Version)
        };

        if (!decision.IsAccepted)
        {
            return decision;
        }

        await repository.CommitAsync(record, decision, cancellationToken);
        await projector.EnqueueAsync(request, decision, cancellationToken);
        return decision;
    }
}
