// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;
using CommunityStarter.Domain.GeneratedFeatures;

namespace CommunityStarter.Application.GeneratedFeatures;

public interface ISupportCommentConversationsRepository
{
    ValueTask<SupportCommentConversationsRecord?> LoadAsync(
        Guid subjectId,
        Guid? communityId,
        CancellationToken cancellationToken);

    ValueTask CommitAsync(
        SupportCommentConversationsRecord current,
        SupportCommentConversationsDecision decision,
        CancellationToken cancellationToken);
}

public sealed class SupportCommentConversationsProjector(IFeatureProjectionSink sink)
{
    public ValueTask EnqueueAsync(
        SupportCommentConversationsRequest request,
        SupportCommentConversationsDecision decision,
        CancellationToken cancellationToken) =>
        sink.EnqueueAsync(
            SupportCommentConversationsDescriptor.Slug,
            request.SubjectId,
            request.CommunityId,
            decision.RequirementId,
            decision.ResultingVersion,
            cancellationToken);
}

public sealed class SupportCommentConversationsHandler(
    ISupportCommentConversationsRepository repository,
    SupportCommentConversationsProjector projector)
{
    public async ValueTask<SupportCommentConversationsDecision> HandleAsync(
        SupportCommentConversationsRequest request,
        CancellationToken cancellationToken)
    {
        var record = await repository.LoadAsync(
            request.SubjectId,
            request.CommunityId,
            cancellationToken) ?? new(
                request.SubjectId,
                request.CommunityId,
                "missing",
                request.ExpectedVersion,
                IsAuthorized: false,
                IsAvailable: false);
        var policy = new SupportCommentConversationsPolicy();
        var decision = request.Action switch
        {
            "AddAComment" => policy.AddAComment(record, request),
            "EditAndRemoveAComment" => policy.EditAndRemoveAComment(record, request),
            "ControlCommentConversations" => policy.ControlCommentConversations(record, request),
            _ => new(
                "unknown",
                FeatureDecisionKind.Invalid,
                "unknown_feature_action",
                record.State,
                record.Version)
        };

        if (!decision.IsAccepted)
        {
            return decision;
        }

        await repository.CommitAsync(record, decision, cancellationToken);
        await projector.EnqueueAsync(request, decision, cancellationToken);
        return decision;
    }
}
