// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;
using CommunityStarter.Domain.GeneratedFeatures;

namespace CommunityStarter.Application.GeneratedFeatures;

public interface ITraceArchitectureToProductTruthRepository
{
    ValueTask<TraceArchitectureToProductTruthRecord?> LoadAsync(
        Guid subjectId,
        Guid? communityId,
        CancellationToken cancellationToken);

    ValueTask CommitAsync(
        TraceArchitectureToProductTruthRecord current,
        TraceArchitectureToProductTruthDecision decision,
        CancellationToken cancellationToken);
}

public sealed class TraceArchitectureToProductTruthProjector(IFeatureProjectionSink sink)
{
    public ValueTask EnqueueAsync(
        TraceArchitectureToProductTruthRequest request,
        TraceArchitectureToProductTruthDecision decision,
        CancellationToken cancellationToken) =>
        sink.EnqueueAsync(
            TraceArchitectureToProductTruthDescriptor.Slug,
            request.SubjectId,
            request.CommunityId,
            decision.RequirementId,
            decision.ResultingVersion,
            cancellationToken);
}

public sealed class TraceArchitectureToProductTruthHandler(
    ITraceArchitectureToProductTruthRepository repository,
    TraceArchitectureToProductTruthProjector projector)
{
    public async ValueTask<TraceArchitectureToProductTruthDecision> HandleAsync(
        TraceArchitectureToProductTruthRequest request,
        CancellationToken cancellationToken)
    {
        var record = await repository.LoadAsync(
            request.SubjectId,
            request.CommunityId,
            cancellationToken) ?? new(
                request.SubjectId,
                request.CommunityId,
                "missing",
                request.ExpectedVersion,
                IsAuthorized: false,
                IsAvailable: false);
        var policy = new TraceArchitectureToProductTruthPolicy();
        var decision = request.Action switch
        {
            "VocabularyInvariantsAndVerticalSlicesDriveImplementation" => policy.VocabularyInvariantsAndVerticalSlicesDriveImplementation(record, request),
            "ConsequentialDecisionsAndDocumentationRemainTraceable" => policy.ConsequentialDecisionsAndDocumentationRemainTraceable(record, request),
            _ => new(
                "unknown",
                FeatureDecisionKind.Invalid,
                "unknown_feature_action",
                record.State,
                record.Version)
        };

        if (!decision.IsAccepted)
        {
            return decision;
        }

        await repository.CommitAsync(record, decision, cancellationToken);
        await projector.EnqueueAsync(request, decision, cancellationToken);
        return decision;
    }
}
