// Generated by scripts/generate_feature_contracts.py. Do not edit manually.
export interface FeatureOperationDescriptor {
  readonly requirementId: string;
  readonly method: string;
}

export interface FeatureDescriptor {
  readonly subsystem: string;
  readonly slug: string;
  readonly title: string;
  readonly operations: readonly FeatureOperationDescriptor[];
}

export const featureCatalog: readonly FeatureDescriptor[] = [
  {
    "subsystem": "administration-insights",
    "slug": "administer-community-settings",
    "title": "Bounded Community administration",
    "operations": [
      {
        "requirementId": "L2-ADMN-001",
        "method": "ChangeVersionedCommunitySettings"
      },
      {
        "requirementId": "L2-ADMN-002",
        "method": "DelegateRolesWithoutPrivilegeEscalation"
      },
      {
        "requirementId": "L2-ADMN-003",
        "method": "PreviewAndExecuteHighImpactOperations"
      }
    ]
  },
  {
    "subsystem": "administration-insights",
    "slug": "control-platform-configuration",
    "title": "Controlled platform configuration",
    "operations": [
      {
        "requirementId": "L2-ADMN-008",
        "method": "PreserveConfigurationHistoryAndRollback"
      },
      {
        "requirementId": "L2-ADMN-009",
        "method": "GovernFeatureFlagsAndKillSwitches"
      }
    ]
  },
  {
    "subsystem": "administration-insights",
    "slug": "control-platform-support-access",
    "title": "Least-privilege platform and support access",
    "operations": [
      {
        "requirementId": "L2-ADMN-004",
        "method": "SeparateOperatorResponsibilities"
      },
      {
        "requirementId": "L2-ADMN-005",
        "method": "GrantPurposeBoundSupportAccess"
      },
      {
        "requirementId": "L2-ADMN-013",
        "method": "MaintainSupportCaseLifecycle"
      },
      {
        "requirementId": "L2-ADMN-014",
        "method": "ProvisionAndPreserveOperatorAuthority"
      }
    ]
  },
  {
    "subsystem": "administration-insights",
    "slug": "deliver-privacy-safe-insights",
    "title": "Privacy-safe actionable insights",
    "operations": [
      {
        "requirementId": "L2-ADMN-010",
        "method": "PublishGovernedMetricDefinitions"
      },
      {
        "requirementId": "L2-ADMN-011",
        "method": "EnforceInsightScopeAndPrivacy"
      }
    ]
  },
  {
    "subsystem": "communities-membership",
    "slug": "control-membership-lifecycle",
    "title": "Control Membership lifecycle",
    "operations": [
      {
        "requirementId": "L2-COMM-004",
        "method": "JoinAnOpenCommunity"
      },
      {
        "requirementId": "L2-COMM-005",
        "method": "RequestGatedMembership"
      },
      {
        "requirementId": "L2-COMM-006",
        "method": "InviteAnAccount"
      },
      {
        "requirementId": "L2-COMM-007",
        "method": "LeaveRemoveAndSuspend"
      },
      {
        "requirementId": "L2-COMM-017",
        "method": "RejoinWithoutDuplicatingMembershipIdentity"
      }
    ]
  },
  {
    "subsystem": "communities-membership",
    "slug": "delegate-community-authority",
    "title": "Delegate Community authority",
    "operations": [
      {
        "requirementId": "L2-COMM-008",
        "method": "ManageRolesAndPermissions"
      },
      {
        "requirementId": "L2-COMM-009",
        "method": "AssignARoleSafely"
      },
      {
        "requirementId": "L2-COMM-010",
        "method": "PreserveAdministrativeContinuity"
      }
    ]
  },
  {
    "subsystem": "communities-membership",
    "slug": "govern-community-identity",
    "title": "Govern Community identity",
    "operations": [
      {
        "requirementId": "L2-COMM-001",
        "method": "CreateACommunity"
      },
      {
        "requirementId": "L2-COMM-002",
        "method": "ConfigureCommunityIdentity"
      }
    ]
  },
  {
    "subsystem": "communities-membership",
    "slug": "govern-space-participation",
    "title": "Govern Spaces and participation rules",
    "operations": [
      {
        "requirementId": "L2-COMM-013",
        "method": "GovernSpaceLifecycle"
      },
      {
        "requirementId": "L2-COMM-014",
        "method": "EnforceSpaceAccess"
      },
      {
        "requirementId": "L2-COMM-015",
        "method": "DelegateSpaceAuthority"
      },
      {
        "requirementId": "L2-COMM-016",
        "method": "AcceptVersionedRules"
      }
    ]
  },
  {
    "subsystem": "communities-membership",
    "slug": "preserve-community-integrity",
    "title": "Preserve Community integrity",
    "operations": [
      {
        "requirementId": "L2-COMM-011",
        "method": "IsolateCommunityState"
      },
      {
        "requirementId": "L2-COMM-012",
        "method": "EnforceLimitsAndConcurrency"
      }
    ]
  },
  {
    "subsystem": "community-events",
    "slug": "coordinate-safe-participation",
    "title": "Coordinated and safe participation",
    "operations": [
      {
        "requirementId": "L2-EVNT-010",
        "method": "NotifyEligibleAttendeesOfChanges"
      },
      {
        "requirementId": "L2-EVNT-012",
        "method": "ReportAndModerateEventHarm"
      }
    ]
  },
  {
    "subsystem": "community-events",
    "slug": "enforce-event-access",
    "title": "Scoped Event access",
    "operations": [
      {
        "requirementId": "L2-EVNT-004",
        "method": "AuthorizeEventOrganizers"
      },
      {
        "requirementId": "L2-EVNT-005",
        "method": "EnforceEventAudienceAndDiscovery"
      },
      {
        "requirementId": "L2-EVNT-006",
        "method": "ProtectAttendeeAndLocationPrivacy"
      }
    ]
  },
  {
    "subsystem": "community-events",
    "slug": "manage-attendance",
    "title": "Consistent attendance management",
    "operations": [
      {
        "requirementId": "L2-EVNT-007",
        "method": "TransitionOneCurrentRSVP"
      },
      {
        "requirementId": "L2-EVNT-008",
        "method": "AllocateCapacityAndWaitlistFairly"
      },
      {
        "requirementId": "L2-EVNT-013",
        "method": "ReconcileAttendanceAfterAccessLoss"
      }
    ]
  },
  {
    "subsystem": "community-events",
    "slug": "manage-event-lifecycle",
    "title": "Trustworthy Event lifecycle",
    "operations": [
      {
        "requirementId": "L2-EVNT-001",
        "method": "CreateAValidEvent"
      },
      {
        "requirementId": "L2-EVNT-003",
        "method": "PublishReviseAndCancelAtomically"
      }
    ]
  },
  {
    "subsystem": "content-media",
    "slug": "govern-post-lifecycle",
    "title": "Govern Post lifecycle",
    "operations": [
      {
        "requirementId": "L2-CONT-001",
        "method": "DraftAndPublishAPost"
      },
      {
        "requirementId": "L2-CONT-002",
        "method": "EditAPostSafely"
      },
      {
        "requirementId": "L2-CONT-003",
        "method": "EnforcePostVisibility"
      },
      {
        "requirementId": "L2-CONT-004",
        "method": "RemoveAndRestoreAPost"
      }
    ]
  },
  {
    "subsystem": "content-media",
    "slug": "handle-attachments-safely",
    "title": "Handle Attachments safely",
    "operations": [
      {
        "requirementId": "L2-CONT-005",
        "method": "StageAnAttachment"
      },
      {
        "requirementId": "L2-CONT-006",
        "method": "ProcessAnAttachment"
      },
      {
        "requirementId": "L2-CONT-007",
        "method": "ProtectAttachmentAccess"
      }
    ]
  },
  {
    "subsystem": "content-media",
    "slug": "preserve-content-integrity",
    "title": "Preserve content integrity",
    "operations": [
      {
        "requirementId": "L2-CONT-011",
        "method": "ApplyTagsConsistently"
      },
      {
        "requirementId": "L2-CONT-012",
        "method": "ValidateAndRenderSafely"
      },
      {
        "requirementId": "L2-CONT-013",
        "method": "CommitContentAtomically"
      },
      {
        "requirementId": "L2-CONT-015",
        "method": "ResolveMentionsAndQuoteReferences"
      }
    ]
  },
  {
    "subsystem": "content-media",
    "slug": "support-comment-conversations",
    "title": "Support Comment conversations",
    "operations": [
      {
        "requirementId": "L2-CONT-008",
        "method": "AddAComment"
      },
      {
        "requirementId": "L2-CONT-009",
        "method": "EditAndRemoveAComment"
      },
      {
        "requirementId": "L2-CONT-010",
        "method": "ControlCommentConversations"
      }
    ]
  },
  {
    "subsystem": "delivery-quality",
    "slug": "build-layered-risk-evidence",
    "title": "Build layered evidence around product risk",
    "operations": [
      {
        "requirementId": "L2-QUAL-001",
        "method": "TestSelectionFollowsRiskAndEvidenceScope"
      },
      {
        "requirementId": "L2-QUAL-002",
        "method": "ProductRulesAndComponentBehaviorHaveFocusedTests"
      },
      {
        "requirementId": "L2-QUAL-003",
        "method": "IntegrationTestsUseRealProviderBehaviorWhereItMatters"
      },
      {
        "requirementId": "L2-QUAL-004",
        "method": "ContractsJourneysAndDeploymentsReceiveCrossStackEvidence"
      }
    ]
  },
  {
    "subsystem": "delivery-quality",
    "slug": "enforce-secure-artifact-promotion",
    "title": "Enforce one secure build-and-promotion pipeline",
    "operations": [
      {
        "requirementId": "L2-QUAL-012",
        "method": "CIRestoresFormatsAnalyzesAndBuildsEveryStack"
      },
      {
        "requirementId": "L2-QUAL-013",
        "method": "CIRunsLayeredTestsAndValidatesSourceArtifacts"
      },
      {
        "requirementId": "L2-QUAL-014",
        "method": "OneVerifiedArtifactIsPromotedWithProtectedCredentials"
      },
      {
        "requirementId": "L2-QUAL-015",
        "method": "DeploymentSmokeChecksReleaseCriticalBehavior"
      },
      {
        "requirementId": "L2-QUAL-021",
        "method": "ProvisionEnvironmentsThroughReviewedInfrastructureCode"
      },
      {
        "requirementId": "L2-QUAL-023",
        "method": "IsolatePreviewAndNonProductionEnvironments"
      }
    ]
  },
  {
    "subsystem": "delivery-quality",
    "slug": "keep-delivery-claims-honest",
    "title": "Keep delivery claims and documentation honest",
    "operations": [
      {
        "requirementId": "L2-QUAL-018",
        "method": "PullRequestsAndHandoffsExposeImpactAndVerification"
      },
      {
        "requirementId": "L2-QUAL-019",
        "method": "DocumentationAndDecisionEvidenceStayCurrentWithBehavior"
      },
      {
        "requirementId": "L2-QUAL-020",
        "method": "DefinitionOfDoneAndProductionReadinessClaimsMatchEvidence"
      }
    ]
  },
  {
    "subsystem": "delivery-quality",
    "slug": "keep-tests-deterministic",
    "title": "Keep tests deterministic, readable, and traceable",
    "operations": [
      {
        "requirementId": "L2-QUAL-005",
        "method": "TestsAreBehavioralIsolatedAndDeterministic"
      },
      {
        "requirementId": "L2-QUAL-006",
        "method": "BrowserJourneysUseStablePageObjectsAndFaithfulDependencies"
      },
      {
        "requirementId": "L2-QUAL-007",
        "method": "RequirementStatusIsBackedByAppropriatelyScopedEvidence"
      }
    ]
  },
  {
    "subsystem": "delivery-quality",
    "slug": "operate-telemetry-and-recovery",
    "title": "Operate the starter with actionable telemetry and recovery",
    "operations": [
      {
        "requirementId": "L2-QUAL-016",
        "method": "LogsMetricsTracesAndHealthExposeActionableSignals"
      },
      {
        "requirementId": "L2-QUAL-017",
        "method": "AlertsRecoveryMigrationRetentionAndIncidentsHaveOwnersAndRehearsal"
      }
    ]
  },
  {
    "subsystem": "delivery-quality",
    "slug": "reproduce-local-change-hygiene",
    "title": "Make local development and change hygiene reproducible",
    "operations": [
      {
        "requirementId": "L2-QUAL-008",
        "method": "CanonicalRestoreBuildTestAndE2eCommandsWorkCleanly"
      },
      {
        "requirementId": "L2-QUAL-009",
        "method": "RepositoryFormattingAndTrackedArtifactsAreGoverned"
      },
      {
        "requirementId": "L2-QUAL-010",
        "method": "IterationStartsNarrowAndEndsWithEveryRequiredGate"
      },
      {
        "requirementId": "L2-QUAL-011",
        "method": "DatabaseMarketingDeploymentAndDocumentationChangesHaveSpecializedChecks"
      }
    ]
  },
  {
    "subsystem": "experience-design-system",
    "slug": "establish-visual-language",
    "title": "Establish one canonical cross-surface visual language",
    "operations": [
      {
        "requirementId": "L2-UXDS-001",
        "method": "CanonicalFoundationsAndAssetsHaveOneSource"
      },
      {
        "requirementId": "L2-UXDS-002",
        "method": "SemanticTokensCoverAllProductRolesAndStates"
      },
      {
        "requirementId": "L2-UXDS-003",
        "method": "ComponentsProgressFromFoundationsToProductSignatures"
      }
    ]
  },
  {
    "subsystem": "experience-design-system",
    "slug": "make-interaction-states-resilient",
    "title": "Make every material interaction state resilient",
    "operations": [
      {
        "requirementId": "L2-UXDS-007",
        "method": "TemplatesAndNavigationUseSemanticWebBehavior"
      },
      {
        "requirementId": "L2-UXDS-008",
        "method": "StylingLayoutMotionIconsAndMediaFollowSystemRules"
      },
      {
        "requirementId": "L2-UXDS-009",
        "method": "FeatureStatesAreCompleteAndServerTruthIsReconciled"
      }
    ]
  },
  {
    "subsystem": "experience-design-system",
    "slug": "make-language-and-media-inclusive",
    "title": "Make language, locale, and media inclusive",
    "operations": [
      {
        "requirementId": "L2-UXDS-014",
        "method": "LocalizeEveryUserFacingContract"
      },
      {
        "requirementId": "L2-UXDS-015",
        "method": "RenderLocaleAndTimeZoneValuesConsistently"
      },
      {
        "requirementId": "L2-UXDS-017",
        "method": "RequireAccessibleMediaAlternatives"
      }
    ]
  },
  {
    "subsystem": "experience-design-system",
    "slug": "meet-accessibility-baseline",
    "title": "Meet an inclusive accessibility baseline",
    "operations": [
      {
        "requirementId": "L2-UXDS-010",
        "method": "SharedPrimitivesAreSemanticAndOperable"
      },
      {
        "requirementId": "L2-UXDS-011",
        "method": "DynamicStatusAndResponsiveCompositionRemainAccessible"
      }
    ]
  },
  {
    "subsystem": "experience-design-system",
    "slug": "provide-angular-component-contracts",
    "title": "Provide disciplined Angular component contracts",
    "operations": [
      {
        "requirementId": "L2-UXDS-004",
        "method": "AngularSourceIsStrictFocusedAndAdjacent"
      },
      {
        "requirementId": "L2-UXDS-005",
        "method": "PresentationalComponentsReceiveDataAndEmitIntent"
      },
      {
        "requirementId": "L2-UXDS-006",
        "method": "RemoteAndDerivedStateRemainExplicit"
      }
    ]
  },
  {
    "subsystem": "feeds-search-engagement",
    "slug": "deliver-useful-feeds",
    "title": "Deliver useful Feeds",
    "operations": [
      {
        "requirementId": "L2-DISC-001",
        "method": "BuildTheAccountFeed"
      },
      {
        "requirementId": "L2-DISC-002",
        "method": "BuildACommunityFeed"
      },
      {
        "requirementId": "L2-DISC-003",
        "method": "PageAFeedConsistently"
      },
      {
        "requirementId": "L2-DISC-004",
        "method": "ExplainAndControlRanking"
      }
    ]
  },
  {
    "subsystem": "feeds-search-engagement",
    "slug": "keep-discovery-trustworthy",
    "title": "Keep discovery trustworthy",
    "operations": [
      {
        "requirementId": "L2-DISC-011",
        "method": "ReconcileCommittedChanges"
      },
      {
        "requirementId": "L2-DISC-012",
        "method": "BoundAbuseAndDegradation"
      }
    ]
  },
  {
    "subsystem": "feeds-search-engagement",
    "slug": "record-engagement",
    "title": "Record private and public engagement",
    "operations": [
      {
        "requirementId": "L2-DISC-008",
        "method": "AddAndRemoveAReaction"
      },
      {
        "requirementId": "L2-DISC-009",
        "method": "SaveAndRemoveABookmark"
      },
      {
        "requirementId": "L2-DISC-010",
        "method": "PresentEngagementState"
      }
    ]
  },
  {
    "subsystem": "feeds-search-engagement",
    "slug": "search-authorized-content",
    "title": "Search authorized content",
    "operations": [
      {
        "requirementId": "L2-DISC-005",
        "method": "SearchEligibleRecords"
      },
      {
        "requirementId": "L2-DISC-006",
        "method": "FilterAndPageSearchResults"
      },
      {
        "requirementId": "L2-DISC-007",
        "method": "RemoveStaleSearchResults"
      }
    ]
  },
  {
    "subsystem": "identity-access",
    "slug": "enforce-server-authorization",
    "title": "Server-owned authorization",
    "operations": [
      {
        "requirementId": "L2-AUTH-008",
        "method": "EvaluateCurrentPermissions"
      },
      {
        "requirementId": "L2-AUTH-009",
        "method": "EnforceCommunityBoundaries"
      },
      {
        "requirementId": "L2-AUTH-010",
        "method": "ExposeAllowedActionsSafely"
      }
    ]
  },
  {
    "subsystem": "identity-access",
    "slug": "manage-safe-account-lifecycle",
    "title": "Safe Account lifecycle",
    "operations": [
      {
        "requirementId": "L2-AUTH-001",
        "method": "RegisterAnAccountSafely"
      },
      {
        "requirementId": "L2-AUTH-002",
        "method": "VerifyAccountOwnership"
      },
      {
        "requirementId": "L2-AUTH-003",
        "method": "RecoverAccountAccess"
      },
      {
        "requirementId": "L2-AUTH-004",
        "method": "EnterAccountDeactivationSafely"
      },
      {
        "requirementId": "L2-AUTH-014",
        "method": "ProtectLocalCredentialsAndActionSecrets"
      }
    ]
  },
  {
    "subsystem": "identity-access",
    "slug": "observe-access-protection",
    "title": "Observable access protection",
    "operations": [
      {
        "requirementId": "L2-AUTH-011",
        "method": "LimitSensitiveAttempts"
      },
      {
        "requirementId": "L2-AUTH-012",
        "method": "RecordSecurityEvents"
      }
    ]
  },
  {
    "subsystem": "identity-access",
    "slug": "protect-authenticated-sessions",
    "title": "Defensible authenticated sessions",
    "operations": [
      {
        "requirementId": "L2-AUTH-005",
        "method": "SignInWithoutEnumeration"
      },
      {
        "requirementId": "L2-AUTH-006",
        "method": "RequireStrongerVerification"
      },
      {
        "requirementId": "L2-AUTH-007",
        "method": "RotateAndRevokeSessions"
      },
      {
        "requirementId": "L2-AUTH-015",
        "method": "IssueRestrictedRemediationSessions"
      },
      {
        "requirementId": "L2-AUTH-016",
        "method": "GovernStrongerFactorLifecycle"
      }
    ]
  },
  {
    "subsystem": "marketing-public-web",
    "slug": "deliver-truthful-public-surface",
    "title": "Deliver an independent and truthful public surface",
    "operations": [
      {
        "requirementId": "L2-MKTG-001",
        "method": "MarketingRemainsStaticAndRuntimeIndependent"
      },
      {
        "requirementId": "L2-MKTG-002",
        "method": "ContentFollowsAClearOutcomeToActionNarrative"
      },
      {
        "requirementId": "L2-MKTG-003",
        "method": "CallsToActionAndProductClaimsAreHonestAndStable"
      }
    ]
  },
  {
    "subsystem": "marketing-public-web",
    "slug": "make-public-discovery-cache-safe",
    "title": "Make public discovery fast, private, and cache-safe",
    "operations": [
      {
        "requirementId": "L2-MKTG-007",
        "method": "PublicMetadataAndIndexingAreDeliberate"
      },
      {
        "requirementId": "L2-MKTG-008",
        "method": "PublicPerformanceHasAnExplicitBudget"
      },
      {
        "requirementId": "L2-MKTG-009",
        "method": "AnalyticsEmbedsAndAuthenticatedDataRemainPrivateByDesign"
      },
      {
        "requirementId": "L2-MKTG-010",
        "method": "CachePolicyDistinguishesImmutableAndRevalidatedContent"
      },
      {
        "requirementId": "L2-MKTG-013",
        "method": "PublishIndexableCommunitiesSafely"
      }
    ]
  },
  {
    "subsystem": "marketing-public-web",
    "slug": "publish-unambiguous-routes",
    "title": "Publish marketing and application routes without ambiguity",
    "operations": [
      {
        "requirementId": "L2-MKTG-004",
        "method": "OneOriginPublishingAssemblesDeterministicAssets"
      },
      {
        "requirementId": "L2-MKTG-005",
        "method": "RequestRoutingProtectsEveryRuntimeOwner"
      },
      {
        "requirementId": "L2-MKTG-006",
        "method": "PublicToApplicationNavigationIsDeploymentConfigurable"
      }
    ]
  },
  {
    "subsystem": "marketing-public-web",
    "slug": "verify-public-deployment",
    "title": "Evolve and verify public deployment safely",
    "operations": [
      {
        "requirementId": "L2-MKTG-012",
        "method": "PublishedPublicBehaviorIsReleaseBlockingEvidence"
      }
    ]
  },
  {
    "subsystem": "messaging-realtime",
    "slug": "authorize-conversation-access",
    "title": "Consent-based Conversation access",
    "operations": [
      {
        "requirementId": "L2-MESS-001",
        "method": "StartAnAuthorizedConversation"
      },
      {
        "requirementId": "L2-MESS-002",
        "method": "EnforceMessageRequestAndBlockPolicy"
      },
      {
        "requirementId": "L2-MESS-016",
        "method": "EndAndReEnterDirectConversationsDeterministically"
      }
    ]
  },
  {
    "subsystem": "messaging-realtime",
    "slug": "deliver-durable-messages",
    "title": "Durable and safe Messages",
    "operations": [
      {
        "requirementId": "L2-MESS-004",
        "method": "CommitOneValidatedMessage"
      },
      {
        "requirementId": "L2-MESS-006",
        "method": "PageMessagesAndTrackReadingPrivately"
      },
      {
        "requirementId": "L2-MESS-007",
        "method": "ApplyEditDeletionAndRetentionPolicy"
      },
      {
        "requirementId": "L2-MESS-008",
        "method": "ReportAMessageWithoutLosingEvidence"
      }
    ]
  },
  {
    "subsystem": "messaging-realtime",
    "slug": "reconcile-realtime-experience",
    "title": "Reconciled realtime experience",
    "operations": [
      {
        "requirementId": "L2-MESS-009",
        "method": "PublishOnlyCommittedMessageEvents"
      },
      {
        "requirementId": "L2-MESS-010",
        "method": "ReconnectAndReconcileFromTheAPI"
      },
      {
        "requirementId": "L2-MESS-011",
        "method": "ScopeRealtimeSubscriptionsOnTheServer"
      }
    ]
  },
  {
    "subsystem": "moderation-trust-safety",
    "slug": "enforce-proportionate-actions",
    "title": "Proportionate server-owned enforcement",
    "operations": [
      {
        "requirementId": "L2-SAFE-007",
        "method": "BoundModeratorAuthorityAndConflicts"
      },
      {
        "requirementId": "L2-SAFE-008",
        "method": "ApplyOneAuditableModerationAction"
      },
      {
        "requirementId": "L2-SAFE-009",
        "method": "NotifyExpireAndReverseActionsSafely"
      },
      {
        "requirementId": "L2-SAFE-013",
        "method": "EnforceTheModerationActionEffectMatrix"
      },
      {
        "requirementId": "L2-SAFE-014",
        "method": "RoutePunitiveChangesThroughModerationActions"
      },
      {
        "requirementId": "L2-SAFE-015",
        "method": "ResolveEnforcementAndOwnershipContinuityAtomically"
      }
    ]
  },
  {
    "subsystem": "moderation-trust-safety",
    "slug": "manage-moderation-cases",
    "title": "Durable Moderation Cases",
    "operations": [
      {
        "requirementId": "L2-SAFE-004",
        "method": "CreateACaseWithDurableEvidence"
      },
      {
        "requirementId": "L2-SAFE-005",
        "method": "TriageAssignAndEscalateCases"
      },
      {
        "requirementId": "L2-SAFE-006",
        "method": "RestrictAndRetainSensitiveEvidence"
      }
    ]
  },
  {
    "subsystem": "moderation-trust-safety",
    "slug": "report-policy-harm",
    "title": "Safe policy reporting",
    "operations": [
      {
        "requirementId": "L2-SAFE-001",
        "method": "ApplyVersionedPolicyPrecedence"
      },
      {
        "requirementId": "L2-SAFE-002",
        "method": "SubmitASafeReport"
      },
      {
        "requirementId": "L2-SAFE-003",
        "method": "ProtectReportersAndLimitAbuse"
      },
      {
        "requirementId": "L2-SAFE-016",
        "method": "PreserveABoundedPriorViewReportingPath"
      }
    ]
  },
  {
    "subsystem": "moderation-trust-safety",
    "slug": "review-safety-decisions",
    "title": "Reviewable and operable safety decisions",
    "operations": [
      {
        "requirementId": "L2-SAFE-010",
        "method": "AdjudicateEligibleAppealsAndRepairState"
      },
      {
        "requirementId": "L2-SAFE-012",
        "method": "AuditAndMeasureSafetyOutcomes"
      }
    ]
  },
  {
    "subsystem": "notifications-delivery",
    "slug": "control-recipient-attention",
    "title": "Recipient-controlled attention",
    "operations": [
      {
        "requirementId": "L2-NOTF-004",
        "method": "ApplyNotificationPreferences"
      },
      {
        "requirementId": "L2-NOTF-006",
        "method": "LocalizeAccessiblePrivacySafeContent"
      }
    ]
  },
  {
    "subsystem": "notifications-delivery",
    "slug": "deliver-external-notifications",
    "title": "Durable external Delivery",
    "operations": [
      {
        "requirementId": "L2-NOTF-007",
        "method": "AttemptEachDeliveryIdempotently"
      },
      {
        "requirementId": "L2-NOTF-008",
        "method": "RetryAndQuarantineTerminalFailures"
      },
      {
        "requirementId": "L2-NOTF-009",
        "method": "ProcessUnsubscribeAndProviderFeedback"
      },
      {
        "requirementId": "L2-NOTF-013",
        "method": "VerifyAndRetireEmailDestinations"
      }
    ]
  },
  {
    "subsystem": "notifications-delivery",
    "slug": "deliver-private-notifications",
    "title": "Relevant and private Notifications",
    "operations": [
      {
        "requirementId": "L2-NOTF-001",
        "method": "CreateNotificationsAfterCommit"
      },
      {
        "requirementId": "L2-NOTF-002",
        "method": "RecheckRecipientEligibility"
      },
      {
        "requirementId": "L2-NOTF-003",
        "method": "MaintainAUsableNotificationInbox"
      }
    ]
  },
  {
    "subsystem": "notifications-delivery",
    "slug": "operate-notification-channels",
    "title": "Safe templates and operable channels",
    "operations": [
      {
        "requirementId": "L2-NOTF-010",
        "method": "RenderSafeTemplatesAndActionLinks"
      },
      {
        "requirementId": "L2-NOTF-011",
        "method": "ObserveAndRepairDeliveryHealth"
      },
      {
        "requirementId": "L2-NOTF-012",
        "method": "DisableUnconfiguredChannelsCleanly"
      }
    ]
  },
  {
    "subsystem": "onboarding-discovery",
    "slug": "complete-resumable-onboarding",
    "title": "Complete resumable onboarding",
    "operations": [
      {
        "requirementId": "L2-ONBD-001",
        "method": "StartAndResumeOnboarding"
      },
      {
        "requirementId": "L2-ONBD-002",
        "method": "CompleteRequiredSteps"
      },
      {
        "requirementId": "L2-ONBD-003",
        "method": "ContinueFromAnInvitation"
      }
    ]
  },
  {
    "subsystem": "onboarding-discovery",
    "slug": "keep-onboarding-safe",
    "title": "Keep onboarding safe and inclusive",
    "operations": [
      {
        "requirementId": "L2-ONBD-010",
        "method": "RecordEligibilityAndConsent"
      },
      {
        "requirementId": "L2-ONBD-011",
        "method": "ExcludeUnsafeCommunitySuggestions"
      },
      {
        "requirementId": "L2-ONBD-012",
        "method": "RecoverFromEmptyAndErrorStates"
      }
    ]
  },
  {
    "subsystem": "onboarding-discovery",
    "slug": "offer-relevant-discovery",
    "title": "Offer relevant discovery",
    "operations": [
      {
        "requirementId": "L2-ONBD-004",
        "method": "DiscoverEligibleCommunities"
      }
    ]
  },
  {
    "subsystem": "onboarding-discovery",
    "slug": "reach-first-community-value",
    "title": "Reach first Community value",
    "operations": [
      {
        "requirementId": "L2-ONBD-007",
        "method": "PreviewACommunitySafely"
      },
      {
        "requirementId": "L2-ONBD-008",
        "method": "EnterTheMembershipPath"
      },
      {
        "requirementId": "L2-ONBD-009",
        "method": "EstablishTheFirstFeed"
      }
    ]
  },
  {
    "subsystem": "operations-reliability",
    "slug": "control-production-change",
    "title": "Production change remains controlled and supportable",
    "operations": [
      {
        "requirementId": "L2-OPER-015",
        "method": "OperateMigrationsAndBackfillsSafely"
      },
      {
        "requirementId": "L2-OPER-016",
        "method": "OperateDurableJobQueues"
      }
    ]
  },
  {
    "subsystem": "operations-reliability",
    "slug": "measure-reliability-capacity",
    "title": "Reliability and capacity are measurable",
    "operations": [
      {
        "requirementId": "L2-OPER-005",
        "method": "DefineAndReportServiceObjectives"
      },
      {
        "requirementId": "L2-OPER-006",
        "method": "EnforcePerformanceAndResourceBudgets"
      },
      {
        "requirementId": "L2-OPER-008",
        "method": "DegradeSafelyDuringDependencyFailure"
      }
    ]
  },
  {
    "subsystem": "operations-reliability",
    "slug": "observe-system-product-health",
    "title": "Operators can understand system and product health",
    "operations": [
      {
        "requirementId": "L2-OPER-001",
        "method": "CorrelateStructuredOperationalTelemetry"
      },
      {
        "requirementId": "L2-OPER-002",
        "method": "MeasureTechnicalAndProductHealth"
      },
      {
        "requirementId": "L2-OPER-003",
        "method": "DistinguishLivenessReadinessAndDependencyHealth"
      },
      {
        "requirementId": "L2-OPER-004",
        "method": "ProvideOwnedOperationalDashboards"
      }
    ]
  },
  {
    "subsystem": "operations-reliability",
    "slug": "recover-data-services",
    "title": "Data and service can be recovered",
    "operations": [
      {
        "requirementId": "L2-OPER-012",
        "method": "CreateAndVerifyProtectedBackups"
      },
      {
        "requirementId": "L2-OPER-013",
        "method": "ProveRecoveryObjectivesThroughRestoreDrills"
      },
      {
        "requirementId": "L2-OPER-014",
        "method": "ReconcileDerivedStateAfterRecovery"
      }
    ]
  },
  {
    "subsystem": "operations-reliability",
    "slug": "respond-to-incidents",
    "title": "Incidents have owned detection and response",
    "operations": [
      {
        "requirementId": "L2-OPER-009",
        "method": "RouteActionableAlertsToAnOwner"
      },
      {
        "requirementId": "L2-OPER-010",
        "method": "RunAndReviewIncidentsConsistently"
      },
      {
        "requirementId": "L2-OPER-011",
        "method": "MaintainExecutableOperationalRunbooks"
      }
    ]
  },
  {
    "subsystem": "platform-architecture",
    "slug": "enforce-implementation-discipline",
    "title": "Enforce production-grade implementation discipline",
    "operations": [
      {
        "requirementId": "L2-ARCH-010",
        "method": "CSharpCodeIsNullableSafeAsynchronousAndConventionEnforced"
      },
      {
        "requirementId": "L2-ARCH-011",
        "method": "ConfigurationCompositionHealthAndDependenciesAreGoverned"
      },
      {
        "requirementId": "L2-ARCH-012",
        "method": "UntrustedAndExternalWorkIsBoundedBehindUsefulSeams"
      }
    ]
  },
  {
    "subsystem": "platform-architecture",
    "slug": "evolve-runtime-topology",
    "title": "Evolve runtime topology without weakening correctness",
    "operations": [
      {
        "requirementId": "L2-ARCH-013",
        "method": "RealtimeDeliveryFollowsCommittedStateAndReconciles"
      },
      {
        "requirementId": "L2-ARCH-014",
        "method": "InitialDeploymentIsCohesiveWhileSourceBoundariesRemainSeparable"
      }
    ]
  },
  {
    "subsystem": "platform-architecture",
    "slug": "keep-behavior-server-authoritative",
    "title": "Keep community behavior server-authoritative",
    "operations": [
      {
        "requirementId": "L2-ARCH-004",
        "method": "ApplicationCodeIsOrganizedByCapabilityAndUseCase"
      },
      {
        "requirementId": "L2-ARCH-005",
        "method": "StateChangesFollowOneAuthoritativeSequence"
      },
      {
        "requirementId": "L2-ARCH-006",
        "method": "HTTPContractsAndFailuresAreStableAndExplicit"
      }
    ]
  },
  {
    "subsystem": "platform-architecture",
    "slug": "preserve-full-stack-boundaries",
    "title": "Preserve explicit full-stack boundaries",
    "operations": [
      {
        "requirementId": "L2-ARCH-001",
        "method": "RuntimeAndRepositorySurfacesAreExplicit"
      },
      {
        "requirementId": "L2-ARCH-002",
        "method": "BackendDependenciesPointInward"
      },
      {
        "requirementId": "L2-ARCH-003",
        "method": "AngularLibrariesHaveStableOwnership"
      }
    ]
  },
  {
    "subsystem": "platform-architecture",
    "slug": "protect-data-persistence-integrity",
    "title": "Protect Community data and persistence integrity",
    "operations": [
      {
        "requirementId": "L2-ARCH-007",
        "method": "RelationalSchemaEvolutionIsForwardAndRehearsable"
      },
      {
        "requirementId": "L2-ARCH-008",
        "method": "CommunityScopedReadsAreExplicitAndEfficient"
      },
      {
        "requirementId": "L2-ARCH-009",
        "method": "TimeDemonstrationDataAndLifecycleStateAreDeliberate"
      }
    ]
  },
  {
    "subsystem": "platform-architecture",
    "slug": "trace-architecture-to-product-truth",
    "title": "Make architecture traceable to product truth",
    "operations": [
      {
        "requirementId": "L2-ARCH-015",
        "method": "VocabularyInvariantsAndVerticalSlicesDriveImplementation"
      },
      {
        "requirementId": "L2-ARCH-016",
        "method": "ConsequentialDecisionsAndDocumentationRemainTraceable"
      }
    ]
  },
  {
    "subsystem": "privacy-data-lifecycle",
    "slug": "control-personal-data",
    "title": "People can access and control their data",
    "operations": [
      {
        "requirementId": "L2-PRIV-005",
        "method": "CorrectControllablePersonalData"
      },
      {
        "requirementId": "L2-PRIV-006",
        "method": "ExportPersonalDataSecurely"
      },
      {
        "requirementId": "L2-PRIV-007",
        "method": "DeactivateAndRestoreAnAccount"
      },
      {
        "requirementId": "L2-PRIV-008",
        "method": "CompleteAnAccountDeletionRequest"
      },
      {
        "requirementId": "L2-PRIV-016",
        "method": "ResolveDependentResponsibilitiesBeforeAccountExit"
      }
    ]
  },
  {
    "subsystem": "privacy-data-lifecycle",
    "slug": "enforce-provider-privacy",
    "title": "Telemetry and providers respect privacy boundaries",
    "operations": [
      {
        "requirementId": "L2-PRIV-013",
        "method": "KeepTelemetryFreeOfSensitiveContent"
      },
      {
        "requirementId": "L2-PRIV-014",
        "method": "GovernProductAnalyticsAndConsent"
      },
      {
        "requirementId": "L2-PRIV-015",
        "method": "ControlProcessorAndRegionalDataBoundaries"
      }
    ]
  },
  {
    "subsystem": "privacy-data-lifecycle",
    "slug": "govern-every-data-copy",
    "title": "Lifecycle rules cover every data copy",
    "operations": [
      {
        "requirementId": "L2-PRIV-009",
        "method": "EnforceRetentionSchedules"
      },
      {
        "requirementId": "L2-PRIV-010",
        "method": "PropagateDeletionToDerivedSystems"
      },
      {
        "requirementId": "L2-PRIV-011",
        "method": "PreserveSharedContentIntegrityWithoutRetainingIdentityUnnecessarily"
      },
      {
        "requirementId": "L2-PRIV-012",
        "method": "RestrictLegalHoldsAndSafetyEvidence"
      }
    ]
  },
  {
    "subsystem": "privacy-data-lifecycle",
    "slug": "minimize-personal-data-use",
    "title": "Personal data use is explicit and minimized",
    "operations": [
      {
        "requirementId": "L2-PRIV-001",
        "method": "MaintainAPersonalDataInventory"
      },
      {
        "requirementId": "L2-PRIV-002",
        "method": "ObtainAndHonorOptionalProcessingChoices"
      },
      {
        "requirementId": "L2-PRIV-003",
        "method": "ApplyPrivacyPreservingDefaults"
      }
    ]
  },
  {
    "subsystem": "profiles-relationships",
    "slug": "enforce-relationship-safety",
    "title": "Enforce relationship safety",
    "operations": [
      {
        "requirementId": "L2-PROF-008",
        "method": "BlockAnotherAccount"
      },
      {
        "requirementId": "L2-PROF-009",
        "method": "MuteAnotherAccount"
      },
      {
        "requirementId": "L2-PROF-010",
        "method": "ResolveBlockAndMutePrecedence"
      },
      {
        "requirementId": "L2-PROF-013",
        "method": "EnforceTheSharedCommunityBlockMatrix"
      }
    ]
  },
  {
    "subsystem": "profiles-relationships",
    "slug": "present-trustworthy-profile",
    "title": "Present a trustworthy Profile",
    "operations": [
      {
        "requirementId": "L2-PROF-001",
        "method": "ProvisionOneProfile"
      },
      {
        "requirementId": "L2-PROF-002",
        "method": "UpdateOwnedProfileFields"
      },
      {
        "requirementId": "L2-PROF-003",
        "method": "ControlProfileVisibility"
      },
      {
        "requirementId": "L2-PROF-004",
        "method": "ManageProfileImagery"
      }
    ]
  },
  {
    "subsystem": "profiles-relationships",
    "slug": "respect-community-context",
    "title": "Respect Community context",
    "operations": [
      {
        "requirementId": "L2-PROF-011",
        "method": "RenderCommunityContextSafely"
      },
      {
        "requirementId": "L2-PROF-012",
        "method": "RetireProfileDataSafely"
      },
      {
        "requirementId": "L2-PROF-014",
        "method": "ListAPrivacySafeMemberDirectory"
      }
    ]
  },
  {
    "subsystem": "security",
    "slug": "constrain-untrusted-boundaries",
    "title": "Constrain every untrusted boundary",
    "operations": [
      {
        "requirementId": "L2-SECU-007",
        "method": "UntrustedInputIsValidatedAndResourceBounded"
      },
      {
        "requirementId": "L2-SECU-008",
        "method": "UploadsValidateContentAndIsolateStoragePaths"
      },
      {
        "requirementId": "L2-SECU-009",
        "method": "SecuritySensitiveWorkflowTransitionsFailClosed"
      },
      {
        "requirementId": "L2-SECU-017",
        "method": "RenderUntrustedTextLinksAndExportsSafely"
      }
    ]
  },
  {
    "subsystem": "security",
    "slug": "harden-runtime-supply-chain",
    "title": "Harden browsers, dependencies, and deployment credentials",
    "operations": [
      {
        "requirementId": "L2-SECU-010",
        "method": "BrowserAndTransportHeadersMatchTheDeploymentThreatModel"
      },
      {
        "requirementId": "L2-SECU-011",
        "method": "DeploymentUsesProtectedEnvironmentsAndShortLivedCredentials"
      },
      {
        "requirementId": "L2-SECU-012",
        "method": "SupplyChainChangesAreReviewedAndContinuouslyScanned"
      }
    ]
  },
  {
    "subsystem": "security",
    "slug": "model-threats-and-identity",
    "title": "Model threats and enforce identity in Community context",
    "operations": [
      {
        "requirementId": "L2-SECU-001",
        "method": "HighRiskCommunityFlowsHaveMaintainedThreatModels"
      },
      {
        "requirementId": "L2-SECU-002",
        "method": "ProductionIdentityAndSessionBehaviorCannotInheritDevelopmentShortcuts"
      },
      {
        "requirementId": "L2-SECU-003",
        "method": "EveryProtectedResourceIsAuthorizedInCommunityContext"
      }
    ]
  },
  {
    "subsystem": "security",
    "slug": "operate-security-readiness",
    "title": "Operate with explicit privacy and security readiness",
    "operations": [
      {
        "requirementId": "L2-SECU-013",
        "method": "VulnerabilitiesHaveAPrivateReportingAndRemediationPath"
      },
      {
        "requirementId": "L2-SECU-014",
        "method": "PrivacyConsentRetentionAndAnalyticsPurposeAreDeclared"
      },
      {
        "requirementId": "L2-SECU-015",
        "method": "ProductionSecurityClaimsDistinguishChecksFromIndependentReview"
      }
    ]
  },
  {
    "subsystem": "security",
    "slug": "protect-secrets-diagnostics-data",
    "title": "Keep secrets, diagnostics, and personal data out of unsafe channels",
    "operations": [
      {
        "requirementId": "L2-SECU-004",
        "method": "SecretsStayOutsideSourceAndPlaceholdersFailSafely"
      },
      {
        "requirementId": "L2-SECU-005",
        "method": "PublicFailuresAreSanitizedAndPrivateDiagnosticsAreRedacted"
      },
      {
        "requirementId": "L2-SECU-006",
        "method": "SourceFixturesAndDemosContainNoRealPersonalData"
      },
      {
        "requirementId": "L2-SECU-016",
        "method": "EncryptProtectedDataAndGovernKeys"
      }
    ]
  },
  {
    "subsystem": "starter-experience",
    "slug": "isolate-development-data",
    "title": "Development data is useful and cannot leak into production",
    "operations": [
      {
        "requirementId": "L2-STRT-005",
        "method": "SeedDeterministicFictionalScenarios"
      },
      {
        "requirementId": "L2-STRT-006",
        "method": "IsolateDevelopmentOnlyIdentityAndProviders"
      }
    ]
  },
  {
    "subsystem": "starter-experience",
    "slug": "maintain-repository-knowledge",
    "title": "Repository knowledge stays current and actionable",
    "operations": [
      {
        "requirementId": "L2-STRT-012",
        "method": "MaintainAnOutcomeOrientedDocumentationMap"
      },
      {
        "requirementId": "L2-STRT-014",
        "method": "DocumentContributionOwnershipSupportAndDisclosure"
      },
      {
        "requirementId": "L2-STRT-015",
        "method": "TrackDependencyAndAssetProvenance"
      }
    ]
  },
  {
    "subsystem": "starter-experience",
    "slug": "reproduce-clean-checkout",
    "title": "A clean checkout is reproducible",
    "operations": [
      {
        "requirementId": "L2-STRT-001",
        "method": "PinAndValidateDevelopmentToolchains"
      },
      {
        "requirementId": "L2-STRT-002",
        "method": "ExposeCanonicalRepositoryCommands"
      },
      {
        "requirementId": "L2-STRT-003",
        "method": "ProvisionRepeatableLocalDependencies"
      },
      {
        "requirementId": "L2-STRT-004",
        "method": "ValidateEnvironmentConfigurationAndSecrets"
      }
    ]
  },
  {
    "subsystem": "starter-experience",
    "slug": "specialize-starter-safely",
    "title": "Teams can specialize the starter safely",
    "operations": [
      {
        "requirementId": "L2-STRT-008",
        "method": "ApplyAndVerifyProductIdentity"
      },
      {
        "requirementId": "L2-STRT-009",
        "method": "SpecializeTheSharedVisualLanguage"
      },
      {
        "requirementId": "L2-STRT-010",
        "method": "ConfigureOptionalCapabilityProfiles"
      },
      {
        "requirementId": "L2-STRT-011",
        "method": "RecordProviderAndArchitectureDecisions"
      }
    ]
  }
];
