#!/usr/bin/env python3
"""Generate traceable feature contracts from docs/detailed-designs.

The design READMEs remain canonical. Generated files are deterministic and fail when a feature has
no policy operations, a requirement is duplicated, or a C# symbol is inconsistent.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DESIGNS = ROOT / "docs" / "detailed-designs"
DOMAIN_OUT = ROOT / "backend" / "src" / "CommunityStarter.Domain" / "GeneratedFeatures"
APPLICATION_OUT = ROOT / "backend" / "src" / "CommunityStarter.Application" / "GeneratedFeatures"
FRONTEND_OUT = ROOT / "frontend" / "src" / "app" / "core" / "feature-catalog.generated.ts"

OPERATION_RE = re.compile(
    r"- \*\*`(?P<policy>[A-Za-z0-9]+Policy)\.(?P<method>[A-Za-z0-9]+)"
    r"\(record, request\)`\*\*.*?`(?P<requirement>L2-[A-Z]+-[0-9]+)`"
)


@dataclass(frozen=True)
class Operation:
    method: str
    requirement: str


@dataclass(frozen=True)
class Feature:
    subsystem: str
    slug: str
    title: str
    prefix: str
    operations: tuple[Operation, ...]


def load_features() -> list[Feature]:
    features: list[Feature] = []
    requirements: set[str] = set()
    for readme in sorted(DESIGNS.glob("*/*/README.md")):
        text = readme.read_text(encoding="utf-8")
        title_match = re.search(r"^# (.+)$", text, re.MULTILINE)
        matches = list(OPERATION_RE.finditer(text))
        if not title_match or not matches:
            raise SystemExit(f"Missing title or policy operations in {readme.relative_to(ROOT)}")

        policies = {match.group("policy") for match in matches}
        if len(policies) != 1:
            raise SystemExit(f"Expected one policy in {readme.relative_to(ROOT)}")
        policy = policies.pop()
        prefix = policy.removesuffix("Policy")
        operations = tuple(
            Operation(match.group("method"), match.group("requirement")) for match in matches
        )
        for operation in operations:
            if operation.requirement in requirements:
                raise SystemExit(f"Duplicate requirement {operation.requirement}")
            requirements.add(operation.requirement)

        features.append(
            Feature(
                subsystem=readme.parent.parent.name,
                slug=readme.parent.name,
                title=title_match.group(1),
                prefix=prefix,
                operations=operations,
            )
        )

    if len(features) != 82 or len(requirements) != 260:
        raise SystemExit(
            f"Expected 82 features and 260 requirements; found {len(features)} and {len(requirements)}"
        )
    return features


def domain_source(feature: Feature) -> str:
    methods = "\n\n".join(
        f"""    public {feature.prefix}Decision {operation.method}(
        {feature.prefix}Record record,
        {feature.prefix}Request request) =>
        {feature.prefix}Decision.From(FeaturePolicyEvaluator.Evaluate(
            \"{operation.requirement}\", record.ToState(), request.ToInput()));"""
        for operation in feature.operations
    )
    descriptor_lines = ",\n".join(
        f'        new("{operation.requirement}", "{operation.method}")'
        for operation in feature.operations
    )
    return f"""// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;

namespace CommunityStarter.Domain.GeneratedFeatures;

public sealed record {feature.prefix}Request(
    Guid SubjectId,
    string Action,
    long ExpectedVersion,
    Guid? CommunityId,
    IReadOnlyDictionary<string, string> Values)
{{
    public FeatureInput ToInput() => new(SubjectId, Action, ExpectedVersion, CommunityId, Values);
}}

public sealed record {feature.prefix}Record(
    Guid Id,
    Guid? CommunityId,
    string State,
    long Version,
    bool IsAuthorized,
    bool IsAvailable)
{{
    public FeatureState ToState() => new(Id, CommunityId, State, Version, IsAuthorized, IsAvailable);
}}

public sealed record {feature.prefix}Decision(
    string RequirementId,
    FeatureDecisionKind Kind,
    string Code,
    string ResultingState,
    long ResultingVersion)
{{
    public bool IsAccepted => Kind == FeatureDecisionKind.Accepted;

    public static {feature.prefix}Decision From(FeatureDecision decision) =>
        new(decision.RequirementId, decision.Kind, decision.Code, decision.ResultingState, decision.ResultingVersion);
}}

public sealed class {feature.prefix}Policy
{{
{methods}
}}

public static class {feature.prefix}Descriptor
{{
    public const string Subsystem = "{feature.subsystem}";
    public const string Slug = "{feature.slug}";
    public const string Title = "{escape_csharp(feature.title)}";

    public static IReadOnlyList<FeatureOperationDescriptor> Operations {{ get; }} =
    [
{descriptor_lines}
    ];
}}
"""


def application_source(feature: Feature) -> str:
    cases = "\n".join(
        f'            "{operation.method}" => policy.{operation.method}(record, request),'
        for operation in feature.operations
    )
    return f"""// <auto-generated />
#nullable enable
using CommunityStarter.Domain.Common;
using CommunityStarter.Domain.GeneratedFeatures;

namespace CommunityStarter.Application.GeneratedFeatures;

public interface I{feature.prefix}Repository
{{
    ValueTask<{feature.prefix}Record?> LoadAsync(
        Guid subjectId,
        Guid? communityId,
        CancellationToken cancellationToken);

    ValueTask CommitAsync(
        {feature.prefix}Record current,
        {feature.prefix}Decision decision,
        CancellationToken cancellationToken);
}}

public sealed class {feature.prefix}Projector(IFeatureProjectionSink sink)
{{
    public ValueTask EnqueueAsync(
        {feature.prefix}Request request,
        {feature.prefix}Decision decision,
        CancellationToken cancellationToken) =>
        sink.EnqueueAsync(
            {feature.prefix}Descriptor.Slug,
            request.SubjectId,
            request.CommunityId,
            decision.RequirementId,
            decision.ResultingVersion,
            cancellationToken);
}}

public sealed class {feature.prefix}Handler(
    I{feature.prefix}Repository repository,
    {feature.prefix}Projector projector)
{{
    public async ValueTask<{feature.prefix}Decision> HandleAsync(
        {feature.prefix}Request request,
        CancellationToken cancellationToken)
    {{
        var record = await repository.LoadAsync(
            request.SubjectId,
            request.CommunityId,
            cancellationToken) ?? new(
                request.SubjectId,
                request.CommunityId,
                "missing",
                request.ExpectedVersion,
                IsAuthorized: false,
                IsAvailable: false);
        var policy = new {feature.prefix}Policy();
        var decision = request.Action switch
        {{
{cases}
            _ => new(
                "unknown",
                FeatureDecisionKind.Invalid,
                "unknown_feature_action",
                record.State,
                record.Version)
        }};

        if (!decision.IsAccepted)
        {{
            return decision;
        }}

        await repository.CommitAsync(record, decision, cancellationToken);
        await projector.EnqueueAsync(request, decision, cancellationToken);
        return decision;
    }}
}}
"""


def catalog_source(features: list[Feature]) -> str:
    features_body = ",\n".join(
        f"""        new(
            \"{feature.subsystem}\",
            \"{feature.slug}\",
            \"{escape_csharp(feature.title)}\",
            {feature.prefix}Descriptor.Operations)"""
        for feature in features
    )
    return f"""// <auto-generated />
#nullable enable
namespace CommunityStarter.Domain.GeneratedFeatures;

public sealed record FeatureOperationDescriptor(string RequirementId, string Method);

public sealed record FeatureDescriptor(
    string Subsystem,
    string Slug,
    string Title,
    IReadOnlyList<FeatureOperationDescriptor> Operations);

public static class GeneratedFeatureCatalog
{{
    public static IReadOnlyList<FeatureDescriptor> Features {{ get; }} =
    [
{features_body}
    ];
}}
"""


def application_abstractions_source() -> str:
    return """// <auto-generated />
#nullable enable
namespace CommunityStarter.Application.GeneratedFeatures;

public interface IFeatureProjectionSink
{
    ValueTask EnqueueAsync(
        string featureSlug,
        Guid subjectId,
        Guid? communityId,
        string requirementId,
        long committedVersion,
        CancellationToken cancellationToken);
}
"""


def frontend_source(features: list[Feature]) -> str:
    data = [
        {
            "subsystem": feature.subsystem,
            "slug": feature.slug,
            "title": feature.title,
            "operations": [
                {"requirementId": operation.requirement, "method": operation.method}
                for operation in feature.operations
            ],
        }
        for feature in features
    ]
    encoded = json.dumps(data, ensure_ascii=False, indent=2)
    return f"""// Generated by scripts/generate_feature_contracts.py. Do not edit manually.
export interface FeatureOperationDescriptor {{
  readonly requirementId: string;
  readonly method: string;
}}

export interface FeatureDescriptor {{
  readonly subsystem: string;
  readonly slug: string;
  readonly title: string;
  readonly operations: readonly FeatureOperationDescriptor[];
}}

export const featureCatalog: readonly FeatureDescriptor[] = {encoded};
"""


def escape_csharp(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content.replace("\r\n", "\n"), encoding="utf-8", newline="\n")


def main() -> None:
    features = load_features()
    DOMAIN_OUT.mkdir(parents=True, exist_ok=True)
    APPLICATION_OUT.mkdir(parents=True, exist_ok=True)
    for stale in [*DOMAIN_OUT.glob("*.g.cs"), *APPLICATION_OUT.glob("*.g.cs")]:
        stale.unlink()

    for feature in features:
        write(DOMAIN_OUT / f"{feature.prefix}.g.cs", domain_source(feature))
        write(APPLICATION_OUT / f"{feature.prefix}.g.cs", application_source(feature))
    write(DOMAIN_OUT / "GeneratedFeatureCatalog.g.cs", catalog_source(features))
    write(APPLICATION_OUT / "GeneratedFeatureAbstractions.g.cs", application_abstractions_source())
    write(FRONTEND_OUT, frontend_source(features))
    print(f"Generated {len(features)} feature contracts and 260 traced operations.")


if __name__ == "__main__":
    main()
